import * as pulumi from "@pulumi/pulumi";
import * as webflow from "@jdetmar/pulumi-webflow";

// Create a Pulumi config object
const config = new pulumi.Config();

// Get configuration values
const workspaceId = config.require("workspaceId");
const displayName = config.require("displayName");

/**
 * Site Example - Creating and Managing Webflow Sites
 *
 * This example demonstrates how to create and manage Webflow sites using Pulumi.
 * Sites are the primary resource in the Webflow provider.
 *
 * Required inputs: workspaceId (Enterprise workspace) and displayName.
 * `shortName` and `timeZone` are read-only outputs generated by Webflow.
 */

// Example 1: Basic Site Creation
const basicSite = new webflow.Site("basic-site", {
  workspaceId: workspaceId,
  displayName: displayName,
});

// Example 2: Multi-Environment Site Configuration
const environments = ["development", "staging", "production"];
const environmentSites = environments.map(
  (env) =>
    new webflow.Site(`site-${env}`, {
      workspaceId: workspaceId,
      displayName: `${displayName}-${env}`,
    })
);

// Example 3: Site with Optional Configuration
const configuredSite = new webflow.Site("configured-site", {
  workspaceId: workspaceId,
  displayName: `${displayName}-configured`,
  // Optional: organize the site in a workspace folder
  parentFolderId: config.get("parentFolderId"),
  // Optional and IMMUTABLE: changing it later replaces (deletes + recreates) the site
  templateName: config.get("templateName"),
  // Publish after every create/update once you run `pulumi config set publish true`.
  // With publishToWebflowSubdomain the site goes to its webflow.io subdomain;
  // add custom domain IDs with publishCustomDomains, or publish a single page
  // with publishPageId. Leave publish off until the site is ready to go live.
  publish: config.getBoolean("publish") ?? false,
  publishToWebflowSubdomain: true,
  // publishCustomDomains: ["your-custom-domain-id"], // domain IDs, not host names
  // publishPageId: "your-page-id", // publish only this page instead of the whole site
});

// Export the site resources for reference
export const basicSiteId = basicSite.id;
export const basicSiteName = basicSite.displayName;
// shortName and timeZone are generated by Webflow and available as outputs
export const basicSiteShortName = basicSite.shortName;
export const basicSiteTimeZone = basicSite.timeZone;
export const environmentSiteIds = environmentSites.map((s) => s.id);
export const configuredSiteId = configuredSite.id;
// publishScope reports what the last provider-initiated publish targeted
// (the webflow.io subdomain, custom domains, or a single page)
export const configuredSitePublishScope = configuredSite.publishScope;
export const configuredSiteLastPublished = configuredSite.lastPublished;

// Print deployment success message
const message = pulumi.interpolate`✅ Successfully created ${environmentSites.length + 2} sites`;
message.apply((m) => console.log(m));
