import * as pulumi from "@pulumi/pulumi";
import * as webflow from "@jdetmar/pulumi-webflow";

// Example: Create multiple Webflow sites in a single Pulumi program
// This demonstrates the basic pattern for managing multiple sites programmatically

// Site creation requires an Enterprise workspace ID (pulumi config set workspaceId ...)
const config = new pulumi.Config();
const workspaceId = config.require("workspaceId");

// Define site configurations as an array.
// shortName and timeZone are generated by Webflow and exposed as outputs, not inputs.
const siteConfigs = [
  {
    name: "marketing-site",
    displayName: "Marketing Site",
  },
  {
    name: "docs-site",
    displayName: "Documentation Site",
  },
  {
    name: "blog-site",
    displayName: "Blog Site",
  },
];

// Create all sites using map pattern
const sites = siteConfigs.map((siteConfig) => {
  const site = new webflow.Site(siteConfig.name, {
    workspaceId: workspaceId,
    displayName: siteConfig.displayName,
  });

  // Configure robots.txt for each site
  new webflow.RobotsTxt(`${siteConfig.name}-robots`, {
    siteId: site.id,
    content: `User-agent: *
Allow: /`,
  });

  return site;
});

// Export site IDs (and the Webflow-generated short names) keyed by site name.
// Stack outputs in TypeScript are top-level `export`s.
export const siteIds: Record<string, pulumi.Output<string>> = {};
export const siteShortNames: Record<string, pulumi.Output<string | undefined>> = {};
siteConfigs.forEach((siteConfig, index) => {
  siteIds[siteConfig.name] = sites[index].id;
  siteShortNames[siteConfig.name] = sites[index].shortName;
});

// Export all site IDs as a list
export const allSiteIds = sites.map((site) => site.id);
