// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package webflow

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-webflow/sdk/go/webflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages fields for a Webflow CMS collection. Collection fields define the structure of content items in a collection. Only displayName, helpText and isRequired can be updated in place; type and metadata cannot be changed after creation and changing them requires replacement (delete + recreate). The Webflow API does not accept a slug or validations when creating a field: the slug is generated from displayName and both are reported as outputs only.
type CollectionField struct {
	pulumi.CustomResourceState

	// The Webflow collection ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
	CollectionId pulumi.StringOutput `pulumi:"collectionId"`
	// The human-readable name of the field (e.g., 'Title', 'Description', 'Author'). This name appears in the Webflow CMS interface. Maximum length: 255 characters.
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// The Webflow-assigned field ID (read-only). This ID is automatically generated when the field is created.
	FieldId pulumi.StringPtrOutput `pulumi:"fieldId"`
	// Optional help text shown in the CMS interface (e.g., 'Enter the article title'). Helps content editors understand what to enter in this field.
	HelpText pulumi.StringPtrOutput `pulumi:"helpText"`
	// Whether the field can be edited (read-only). System fields may not be editable.
	IsEditable pulumi.BoolPtrOutput `pulumi:"isEditable"`
	// Whether the field is required (optional, defaults to false). When true, content items must provide a value for this field.
	IsRequired pulumi.BoolPtrOutput `pulumi:"isRequired"`
	// Type-specific configuration (create-only). Required for Option fields: {"options": [{"name": "Draft"}, {"name": "Published"}]}. Required for Reference and MultiReference fields: {"collectionId": "<referenced collection ID>"}. Not accepted for other field types. Changing metadata requires replacement.
	Metadata pulumi.MapOutput `pulumi:"metadata"`
	// Deprecated: the Webflow Create Field endpoint does not accept a slug; Webflow generates the slug from displayName. This input is ignored - it is never sent to the API and never causes a diff. The generated slug (used in API requests and exports) is reported in the outputs.
	//
	// Deprecated: The Webflow API does not accept a slug when creating a field; Webflow generates it from displayName. This input is ignored; read the generated slug from the outputs.
	Slug pulumi.StringPtrOutput `pulumi:"slug"`
	// The field type (e.g., 'PlainText', 'RichText', 'Image', 'Number'). Supported types: Color, DateTime, Email, File, Image, Link, MultiImage, Number, Phone, PlainText, RichText, Switch, VideoLink, Option, MultiReference, Reference. IMPORTANT: Cannot be changed after creation - changing this requires replacement.
	Type pulumi.StringOutput `pulumi:"type"`
	// Deprecated: the Webflow API does not accept validations when creating a field ("field validation is currently not available through the API"). This input is ignored - it is never sent to the API and never causes a diff. The validations Webflow reports for the field are available in the outputs.
	//
	// Deprecated: The Webflow API does not accept field validations; this input is ignored. The validations Webflow reports are available in the outputs.
	Validations pulumi.MapOutput `pulumi:"validations"`
}

// NewCollectionField registers a new resource with the given unique name, arguments, and options.
func NewCollectionField(ctx *pulumi.Context,
	name string, args *CollectionFieldArgs, opts ...pulumi.ResourceOption) (*CollectionField, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CollectionId == nil {
		return nil, errors.New("invalid value for required argument 'CollectionId'")
	}
	if args.DisplayName == nil {
		return nil, errors.New("invalid value for required argument 'DisplayName'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CollectionField
	err := ctx.RegisterResource("webflow:index:CollectionField", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCollectionField gets an existing CollectionField resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCollectionField(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CollectionFieldState, opts ...pulumi.ResourceOption) (*CollectionField, error) {
	var resource CollectionField
	err := ctx.ReadResource("webflow:index:CollectionField", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CollectionField resources.
type collectionFieldState struct {
}

type CollectionFieldState struct {
}

func (CollectionFieldState) ElementType() reflect.Type {
	return reflect.TypeOf((*collectionFieldState)(nil)).Elem()
}

type collectionFieldArgs struct {
	// The Webflow collection ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
	CollectionId string `pulumi:"collectionId"`
	// The human-readable name of the field (e.g., 'Title', 'Description', 'Author'). This name appears in the Webflow CMS interface. Maximum length: 255 characters.
	DisplayName string `pulumi:"displayName"`
	// Optional help text shown in the CMS interface (e.g., 'Enter the article title'). Helps content editors understand what to enter in this field.
	HelpText *string `pulumi:"helpText"`
	// Whether the field is required (optional, defaults to false). When true, content items must provide a value for this field.
	IsRequired *bool `pulumi:"isRequired"`
	// Type-specific configuration (create-only). Required for Option fields: {"options": [{"name": "Draft"}, {"name": "Published"}]}. Required for Reference and MultiReference fields: {"collectionId": "<referenced collection ID>"}. Not accepted for other field types. Changing metadata requires replacement.
	Metadata map[string]interface{} `pulumi:"metadata"`
	// Deprecated: the Webflow Create Field endpoint does not accept a slug; Webflow generates the slug from displayName. This input is ignored - it is never sent to the API and never causes a diff. The generated slug (used in API requests and exports) is reported in the outputs.
	//
	// Deprecated: The Webflow API does not accept a slug when creating a field; Webflow generates it from displayName. This input is ignored; read the generated slug from the outputs.
	Slug *string `pulumi:"slug"`
	// The field type (e.g., 'PlainText', 'RichText', 'Image', 'Number'). Supported types: Color, DateTime, Email, File, Image, Link, MultiImage, Number, Phone, PlainText, RichText, Switch, VideoLink, Option, MultiReference, Reference. IMPORTANT: Cannot be changed after creation - changing this requires replacement.
	Type string `pulumi:"type"`
	// Deprecated: the Webflow API does not accept validations when creating a field ("field validation is currently not available through the API"). This input is ignored - it is never sent to the API and never causes a diff. The validations Webflow reports for the field are available in the outputs.
	//
	// Deprecated: The Webflow API does not accept field validations; this input is ignored. The validations Webflow reports are available in the outputs.
	Validations map[string]interface{} `pulumi:"validations"`
}

// The set of arguments for constructing a CollectionField resource.
type CollectionFieldArgs struct {
	// The Webflow collection ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
	CollectionId pulumi.StringInput
	// The human-readable name of the field (e.g., 'Title', 'Description', 'Author'). This name appears in the Webflow CMS interface. Maximum length: 255 characters.
	DisplayName pulumi.StringInput
	// Optional help text shown in the CMS interface (e.g., 'Enter the article title'). Helps content editors understand what to enter in this field.
	HelpText pulumi.StringPtrInput
	// Whether the field is required (optional, defaults to false). When true, content items must provide a value for this field.
	IsRequired pulumi.BoolPtrInput
	// Type-specific configuration (create-only). Required for Option fields: {"options": [{"name": "Draft"}, {"name": "Published"}]}. Required for Reference and MultiReference fields: {"collectionId": "<referenced collection ID>"}. Not accepted for other field types. Changing metadata requires replacement.
	Metadata pulumi.MapInput
	// Deprecated: the Webflow Create Field endpoint does not accept a slug; Webflow generates the slug from displayName. This input is ignored - it is never sent to the API and never causes a diff. The generated slug (used in API requests and exports) is reported in the outputs.
	//
	// Deprecated: The Webflow API does not accept a slug when creating a field; Webflow generates it from displayName. This input is ignored; read the generated slug from the outputs.
	Slug pulumi.StringPtrInput
	// The field type (e.g., 'PlainText', 'RichText', 'Image', 'Number'). Supported types: Color, DateTime, Email, File, Image, Link, MultiImage, Number, Phone, PlainText, RichText, Switch, VideoLink, Option, MultiReference, Reference. IMPORTANT: Cannot be changed after creation - changing this requires replacement.
	Type pulumi.StringInput
	// Deprecated: the Webflow API does not accept validations when creating a field ("field validation is currently not available through the API"). This input is ignored - it is never sent to the API and never causes a diff. The validations Webflow reports for the field are available in the outputs.
	//
	// Deprecated: The Webflow API does not accept field validations; this input is ignored. The validations Webflow reports are available in the outputs.
	Validations pulumi.MapInput
}

func (CollectionFieldArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*collectionFieldArgs)(nil)).Elem()
}

type CollectionFieldInput interface {
	pulumi.Input

	ToCollectionFieldOutput() CollectionFieldOutput
	ToCollectionFieldOutputWithContext(ctx context.Context) CollectionFieldOutput
}

func (*CollectionField) ElementType() reflect.Type {
	return reflect.TypeOf((**CollectionField)(nil)).Elem()
}

func (i *CollectionField) ToCollectionFieldOutput() CollectionFieldOutput {
	return i.ToCollectionFieldOutputWithContext(context.Background())
}

func (i *CollectionField) ToCollectionFieldOutputWithContext(ctx context.Context) CollectionFieldOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CollectionFieldOutput)
}

type CollectionFieldOutput struct{ *pulumi.OutputState }

func (CollectionFieldOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CollectionField)(nil)).Elem()
}

func (o CollectionFieldOutput) ToCollectionFieldOutput() CollectionFieldOutput {
	return o
}

func (o CollectionFieldOutput) ToCollectionFieldOutputWithContext(ctx context.Context) CollectionFieldOutput {
	return o
}

// The Webflow collection ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
func (o CollectionFieldOutput) CollectionId() pulumi.StringOutput {
	return o.ApplyT(func(v *CollectionField) pulumi.StringOutput { return v.CollectionId }).(pulumi.StringOutput)
}

// The human-readable name of the field (e.g., 'Title', 'Description', 'Author'). This name appears in the Webflow CMS interface. Maximum length: 255 characters.
func (o CollectionFieldOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v *CollectionField) pulumi.StringOutput { return v.DisplayName }).(pulumi.StringOutput)
}

// The Webflow-assigned field ID (read-only). This ID is automatically generated when the field is created.
func (o CollectionFieldOutput) FieldId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CollectionField) pulumi.StringPtrOutput { return v.FieldId }).(pulumi.StringPtrOutput)
}

// Optional help text shown in the CMS interface (e.g., 'Enter the article title'). Helps content editors understand what to enter in this field.
func (o CollectionFieldOutput) HelpText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CollectionField) pulumi.StringPtrOutput { return v.HelpText }).(pulumi.StringPtrOutput)
}

// Whether the field can be edited (read-only). System fields may not be editable.
func (o CollectionFieldOutput) IsEditable() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *CollectionField) pulumi.BoolPtrOutput { return v.IsEditable }).(pulumi.BoolPtrOutput)
}

// Whether the field is required (optional, defaults to false). When true, content items must provide a value for this field.
func (o CollectionFieldOutput) IsRequired() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *CollectionField) pulumi.BoolPtrOutput { return v.IsRequired }).(pulumi.BoolPtrOutput)
}

// Type-specific configuration (create-only). Required for Option fields: {"options": [{"name": "Draft"}, {"name": "Published"}]}. Required for Reference and MultiReference fields: {"collectionId": "<referenced collection ID>"}. Not accepted for other field types. Changing metadata requires replacement.
func (o CollectionFieldOutput) Metadata() pulumi.MapOutput {
	return o.ApplyT(func(v *CollectionField) pulumi.MapOutput { return v.Metadata }).(pulumi.MapOutput)
}

// Deprecated: the Webflow Create Field endpoint does not accept a slug; Webflow generates the slug from displayName. This input is ignored - it is never sent to the API and never causes a diff. The generated slug (used in API requests and exports) is reported in the outputs.
//
// Deprecated: The Webflow API does not accept a slug when creating a field; Webflow generates it from displayName. This input is ignored; read the generated slug from the outputs.
func (o CollectionFieldOutput) Slug() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CollectionField) pulumi.StringPtrOutput { return v.Slug }).(pulumi.StringPtrOutput)
}

// The field type (e.g., 'PlainText', 'RichText', 'Image', 'Number'). Supported types: Color, DateTime, Email, File, Image, Link, MultiImage, Number, Phone, PlainText, RichText, Switch, VideoLink, Option, MultiReference, Reference. IMPORTANT: Cannot be changed after creation - changing this requires replacement.
func (o CollectionFieldOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *CollectionField) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// Deprecated: the Webflow API does not accept validations when creating a field ("field validation is currently not available through the API"). This input is ignored - it is never sent to the API and never causes a diff. The validations Webflow reports for the field are available in the outputs.
//
// Deprecated: The Webflow API does not accept field validations; this input is ignored. The validations Webflow reports are available in the outputs.
func (o CollectionFieldOutput) Validations() pulumi.MapOutput {
	return o.ApplyT(func(v *CollectionField) pulumi.MapOutput { return v.Validations }).(pulumi.MapOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CollectionFieldInput)(nil)).Elem(), &CollectionField{})
	pulumi.RegisterOutputType(CollectionFieldOutput{})
}
