// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package webflow

import (
	"context"
	"reflect"

	"github.com/JDetmar/pulumi-webflow/sdk/go/webflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Returns the top values of a chosen dimension (country, region, device type, OS, browser, language, locale, referrer, traffic source, UTM parameters or audience) for a Webflow site, ranked by sessions or users (Analyze API, beta). Requires the 'sites:read' scope and a Webflow workspace with the Analyze add-on. Webflow allows one Analyze request in flight per access token; concurrent requests are retried. The reporting window must start on or after 2025-04-09 and span at most 100 days.
func GetAnalyticsTopDimensions(ctx *pulumi.Context, args *GetAnalyticsTopDimensionsArgs, opts ...pulumi.InvokeOption) (*GetAnalyticsTopDimensionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAnalyticsTopDimensionsResult
	err := ctx.Invoke("webflow:index:getAnalyticsTopDimensions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetAnalyticsTopDimensionsArgs struct {
	// Restrict the report to a single browser name (e.g., 'Chrome').
	Browser *string `pulumi:"browser"`
	// Restrict the report to a single country, as an ISO 3166-1 alpha-2 code (e.g., 'US'). Normalized to uppercase.
	Country *string `pulumi:"country"`
	// Restrict the report to a single device type: 'desktop', 'mobile' or 'tablet'.
	DeviceType *string `pulumi:"deviceType"`
	// The dimension to rank. One of: 'country', 'region', 'deviceType', 'os', 'browser', 'language', 'locale', 'referrer', 'trafficSource', 'utmCampaign', 'utmContent', 'utmMedium', 'utmSource', 'utmTerm', 'audienceIds'.
	Dimension string `pulumi:"dimension"`
	// Exclusive end of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be after startTime and within 100 days of it.
	EndTime string `pulumi:"endTime"`
	// Advanced filters keyed by dimension (e.g., 'country', 'deviceType', 'pagePath', 'referrer', 'trafficSource', 'utmCampaign', 'os', 'language', 'locale', 'region', 'audienceIds', 'collectionId', 'itemSlug', 'pageId', 'dayOfWeek', 'timeOfDay', 'visitStatus', ...). Each entry supports 'eq', 'in', 'ne' and 'nin'. Filter a given dimension either here or with the matching single-value input, not both.
	Filters map[string]AnalyticsDimensionFilter `pulumi:"filters"`
	// Maximum number of rows to return. Defaults to 25, up to a maximum of 100.
	Limit *int `pulumi:"limit"`
	// Unit of each row's count: 'session' or 'user'.
	MetricScope string `pulumi:"metricScope"`
	// Restrict the report to a single page path (e.g., '/pricing').
	PagePath *string `pulumi:"pagePath"`
	// Restrict the report to a single referrer domain (e.g., 'google.com').
	Referrer *string `pulumi:"referrer"`
	// The Webflow site ID (24-character lowercase hexadecimal string).
	SiteId string `pulumi:"siteId"`
	// Inclusive start of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be on or after 2025-04-09T00:00:00Z.
	StartTime string `pulumi:"startTime"`
	// Restrict the report to a single traffic source code (e.g., 'SO' for Organic Search).
	TrafficSource *string `pulumi:"trafficSource"`
	// Restrict the report to a single utm_campaign value.
	UtmCampaign *string `pulumi:"utmCampaign"`
	// Restrict the report to a single utm_medium value.
	UtmMedium *string `pulumi:"utmMedium"`
	// Restrict the report to a single utm_source value.
	UtmSource *string `pulumi:"utmSource"`
}

type GetAnalyticsTopDimensionsResult struct {
	// The ranked dimension values, highest count first.
	Data []AnalyticsDimensionRow `pulumi:"data"`
	// The dimension whose values were ranked.
	Dimension string `pulumi:"dimension"`
	// The filters that were applied, keyed by dimension.
	Filters map[string]AnalyticsDimensionFilter `pulumi:"filters"`
	// The row cap that was applied (echoes the request value, including the default).
	Limit int `pulumi:"limit"`
	// The unit each count is measured in: 'session' or 'user'.
	MetricScope string `pulumi:"metricScope"`
	// The report name, always 'top_dimensions'.
	Report string `pulumi:"report"`
	// The reporting window that was applied.
	Window AnalyticsWindow `pulumi:"window"`
}

func GetAnalyticsTopDimensionsOutput(ctx *pulumi.Context, args GetAnalyticsTopDimensionsOutputArgs, opts ...pulumi.InvokeOption) GetAnalyticsTopDimensionsResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("webflow:index:getAnalyticsTopDimensions", args, GetAnalyticsTopDimensionsResultOutput{}, options).(GetAnalyticsTopDimensionsResultOutput)
}

type GetAnalyticsTopDimensionsOutputArgs struct {
	// Restrict the report to a single browser name (e.g., 'Chrome').
	Browser pulumi.StringPtrInput `pulumi:"browser"`
	// Restrict the report to a single country, as an ISO 3166-1 alpha-2 code (e.g., 'US'). Normalized to uppercase.
	Country pulumi.StringPtrInput `pulumi:"country"`
	// Restrict the report to a single device type: 'desktop', 'mobile' or 'tablet'.
	DeviceType pulumi.StringPtrInput `pulumi:"deviceType"`
	// The dimension to rank. One of: 'country', 'region', 'deviceType', 'os', 'browser', 'language', 'locale', 'referrer', 'trafficSource', 'utmCampaign', 'utmContent', 'utmMedium', 'utmSource', 'utmTerm', 'audienceIds'.
	Dimension pulumi.StringInput `pulumi:"dimension"`
	// Exclusive end of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be after startTime and within 100 days of it.
	EndTime pulumi.StringInput `pulumi:"endTime"`
	// Advanced filters keyed by dimension (e.g., 'country', 'deviceType', 'pagePath', 'referrer', 'trafficSource', 'utmCampaign', 'os', 'language', 'locale', 'region', 'audienceIds', 'collectionId', 'itemSlug', 'pageId', 'dayOfWeek', 'timeOfDay', 'visitStatus', ...). Each entry supports 'eq', 'in', 'ne' and 'nin'. Filter a given dimension either here or with the matching single-value input, not both.
	Filters AnalyticsDimensionFilterMapInput `pulumi:"filters"`
	// Maximum number of rows to return. Defaults to 25, up to a maximum of 100.
	Limit pulumi.IntPtrInput `pulumi:"limit"`
	// Unit of each row's count: 'session' or 'user'.
	MetricScope pulumi.StringInput `pulumi:"metricScope"`
	// Restrict the report to a single page path (e.g., '/pricing').
	PagePath pulumi.StringPtrInput `pulumi:"pagePath"`
	// Restrict the report to a single referrer domain (e.g., 'google.com').
	Referrer pulumi.StringPtrInput `pulumi:"referrer"`
	// The Webflow site ID (24-character lowercase hexadecimal string).
	SiteId pulumi.StringInput `pulumi:"siteId"`
	// Inclusive start of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be on or after 2025-04-09T00:00:00Z.
	StartTime pulumi.StringInput `pulumi:"startTime"`
	// Restrict the report to a single traffic source code (e.g., 'SO' for Organic Search).
	TrafficSource pulumi.StringPtrInput `pulumi:"trafficSource"`
	// Restrict the report to a single utm_campaign value.
	UtmCampaign pulumi.StringPtrInput `pulumi:"utmCampaign"`
	// Restrict the report to a single utm_medium value.
	UtmMedium pulumi.StringPtrInput `pulumi:"utmMedium"`
	// Restrict the report to a single utm_source value.
	UtmSource pulumi.StringPtrInput `pulumi:"utmSource"`
}

func (GetAnalyticsTopDimensionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAnalyticsTopDimensionsArgs)(nil)).Elem()
}

type GetAnalyticsTopDimensionsResultOutput struct{ *pulumi.OutputState }

func (GetAnalyticsTopDimensionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAnalyticsTopDimensionsResult)(nil)).Elem()
}

func (o GetAnalyticsTopDimensionsResultOutput) ToGetAnalyticsTopDimensionsResultOutput() GetAnalyticsTopDimensionsResultOutput {
	return o
}

func (o GetAnalyticsTopDimensionsResultOutput) ToGetAnalyticsTopDimensionsResultOutputWithContext(ctx context.Context) GetAnalyticsTopDimensionsResultOutput {
	return o
}

// The ranked dimension values, highest count first.
func (o GetAnalyticsTopDimensionsResultOutput) Data() AnalyticsDimensionRowArrayOutput {
	return o.ApplyT(func(v GetAnalyticsTopDimensionsResult) []AnalyticsDimensionRow { return v.Data }).(AnalyticsDimensionRowArrayOutput)
}

// The dimension whose values were ranked.
func (o GetAnalyticsTopDimensionsResultOutput) Dimension() pulumi.StringOutput {
	return o.ApplyT(func(v GetAnalyticsTopDimensionsResult) string { return v.Dimension }).(pulumi.StringOutput)
}

// The filters that were applied, keyed by dimension.
func (o GetAnalyticsTopDimensionsResultOutput) Filters() AnalyticsDimensionFilterMapOutput {
	return o.ApplyT(func(v GetAnalyticsTopDimensionsResult) map[string]AnalyticsDimensionFilter { return v.Filters }).(AnalyticsDimensionFilterMapOutput)
}

// The row cap that was applied (echoes the request value, including the default).
func (o GetAnalyticsTopDimensionsResultOutput) Limit() pulumi.IntOutput {
	return o.ApplyT(func(v GetAnalyticsTopDimensionsResult) int { return v.Limit }).(pulumi.IntOutput)
}

// The unit each count is measured in: 'session' or 'user'.
func (o GetAnalyticsTopDimensionsResultOutput) MetricScope() pulumi.StringOutput {
	return o.ApplyT(func(v GetAnalyticsTopDimensionsResult) string { return v.MetricScope }).(pulumi.StringOutput)
}

// The report name, always 'top_dimensions'.
func (o GetAnalyticsTopDimensionsResultOutput) Report() pulumi.StringOutput {
	return o.ApplyT(func(v GetAnalyticsTopDimensionsResult) string { return v.Report }).(pulumi.StringOutput)
}

// The reporting window that was applied.
func (o GetAnalyticsTopDimensionsResultOutput) Window() AnalyticsWindowOutput {
	return o.ApplyT(func(v GetAnalyticsTopDimensionsResult) AnalyticsWindow { return v.Window }).(AnalyticsWindowOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAnalyticsTopDimensionsResultOutput{})
}
