// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package webflow

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-webflow/sdk/go/webflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages a single Google Tag ID (Google Analytics 4, Google Tag, Google Ads or Campaign Manager) configured on a Webflow site via the Google Tag Manager integration API. Each resource manages one entry in the site's tag list, so multiple GoogleTag resources may target the same site. Tags on the site that are not managed by Pulumi are left untouched. Requires the 'sites:read' and 'sites:write' scopes. Webflow allows up to 25 tags per site and rejects legacy Universal Analytics 'UA-' IDs.
type GoogleTag struct {
	pulumi.CustomResourceState

	// A human-readable label for the tag shown in the Webflow dashboard (e.g., 'Primary Google Analytics').
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// The display position Webflow reports for this tag. This reflects any automatic assignment or renormalization performed by Webflow and may differ from 'order'. Read-only.
	EffectiveOrder pulumi.IntPtrOutput `pulumi:"effectiveOrder"`
	// Optional display position of the tag within the site's tag list. When omitted, Webflow assigns the position automatically (see 'effectiveOrder'). Webflow renormalizes positions after a tag is deleted, so only set this when you need to control ordering explicitly.
	Order pulumi.IntPtrOutput `pulumi:"order"`
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). Changing this value replaces the resource.
	SiteId pulumi.StringOutput `pulumi:"siteId"`
	// The Google Tag ID to configure, e.g., 'G-1A2B3C4D5E' (GA4 measurement ID), 'GT-ABC123' (Google Tag), 'AW-123456789' (Google Ads) or 'DC-1234567' (Campaign Manager). Webflow rejects Universal Analytics 'UA-' IDs. Changing this value replaces the resource.
	TagId pulumi.StringOutput `pulumi:"tagId"`
}

// NewGoogleTag registers a new resource with the given unique name, arguments, and options.
func NewGoogleTag(ctx *pulumi.Context,
	name string, args *GoogleTagArgs, opts ...pulumi.ResourceOption) (*GoogleTag, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DisplayName == nil {
		return nil, errors.New("invalid value for required argument 'DisplayName'")
	}
	if args.SiteId == nil {
		return nil, errors.New("invalid value for required argument 'SiteId'")
	}
	if args.TagId == nil {
		return nil, errors.New("invalid value for required argument 'TagId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource GoogleTag
	err := ctx.RegisterResource("webflow:index:GoogleTag", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGoogleTag gets an existing GoogleTag resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGoogleTag(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GoogleTagState, opts ...pulumi.ResourceOption) (*GoogleTag, error) {
	var resource GoogleTag
	err := ctx.ReadResource("webflow:index:GoogleTag", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering GoogleTag resources.
type googleTagState struct {
}

type GoogleTagState struct {
}

func (GoogleTagState) ElementType() reflect.Type {
	return reflect.TypeOf((*googleTagState)(nil)).Elem()
}

type googleTagArgs struct {
	// A human-readable label for the tag shown in the Webflow dashboard (e.g., 'Primary Google Analytics').
	DisplayName string `pulumi:"displayName"`
	// Optional display position of the tag within the site's tag list. When omitted, Webflow assigns the position automatically (see 'effectiveOrder'). Webflow renormalizes positions after a tag is deleted, so only set this when you need to control ordering explicitly.
	Order *int `pulumi:"order"`
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). Changing this value replaces the resource.
	SiteId string `pulumi:"siteId"`
	// The Google Tag ID to configure, e.g., 'G-1A2B3C4D5E' (GA4 measurement ID), 'GT-ABC123' (Google Tag), 'AW-123456789' (Google Ads) or 'DC-1234567' (Campaign Manager). Webflow rejects Universal Analytics 'UA-' IDs. Changing this value replaces the resource.
	TagId string `pulumi:"tagId"`
}

// The set of arguments for constructing a GoogleTag resource.
type GoogleTagArgs struct {
	// A human-readable label for the tag shown in the Webflow dashboard (e.g., 'Primary Google Analytics').
	DisplayName pulumi.StringInput
	// Optional display position of the tag within the site's tag list. When omitted, Webflow assigns the position automatically (see 'effectiveOrder'). Webflow renormalizes positions after a tag is deleted, so only set this when you need to control ordering explicitly.
	Order pulumi.IntPtrInput
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). Changing this value replaces the resource.
	SiteId pulumi.StringInput
	// The Google Tag ID to configure, e.g., 'G-1A2B3C4D5E' (GA4 measurement ID), 'GT-ABC123' (Google Tag), 'AW-123456789' (Google Ads) or 'DC-1234567' (Campaign Manager). Webflow rejects Universal Analytics 'UA-' IDs. Changing this value replaces the resource.
	TagId pulumi.StringInput
}

func (GoogleTagArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*googleTagArgs)(nil)).Elem()
}

type GoogleTagInput interface {
	pulumi.Input

	ToGoogleTagOutput() GoogleTagOutput
	ToGoogleTagOutputWithContext(ctx context.Context) GoogleTagOutput
}

func (*GoogleTag) ElementType() reflect.Type {
	return reflect.TypeOf((**GoogleTag)(nil)).Elem()
}

func (i *GoogleTag) ToGoogleTagOutput() GoogleTagOutput {
	return i.ToGoogleTagOutputWithContext(context.Background())
}

func (i *GoogleTag) ToGoogleTagOutputWithContext(ctx context.Context) GoogleTagOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GoogleTagOutput)
}

type GoogleTagOutput struct{ *pulumi.OutputState }

func (GoogleTagOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**GoogleTag)(nil)).Elem()
}

func (o GoogleTagOutput) ToGoogleTagOutput() GoogleTagOutput {
	return o
}

func (o GoogleTagOutput) ToGoogleTagOutputWithContext(ctx context.Context) GoogleTagOutput {
	return o
}

// A human-readable label for the tag shown in the Webflow dashboard (e.g., 'Primary Google Analytics').
func (o GoogleTagOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v *GoogleTag) pulumi.StringOutput { return v.DisplayName }).(pulumi.StringOutput)
}

// The display position Webflow reports for this tag. This reflects any automatic assignment or renormalization performed by Webflow and may differ from 'order'. Read-only.
func (o GoogleTagOutput) EffectiveOrder() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *GoogleTag) pulumi.IntPtrOutput { return v.EffectiveOrder }).(pulumi.IntPtrOutput)
}

// Optional display position of the tag within the site's tag list. When omitted, Webflow assigns the position automatically (see 'effectiveOrder'). Webflow renormalizes positions after a tag is deleted, so only set this when you need to control ordering explicitly.
func (o GoogleTagOutput) Order() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *GoogleTag) pulumi.IntPtrOutput { return v.Order }).(pulumi.IntPtrOutput)
}

// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). Changing this value replaces the resource.
func (o GoogleTagOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *GoogleTag) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

// The Google Tag ID to configure, e.g., 'G-1A2B3C4D5E' (GA4 measurement ID), 'GT-ABC123' (Google Tag), 'AW-123456789' (Google Ads) or 'DC-1234567' (Campaign Manager). Webflow rejects Universal Analytics 'UA-' IDs. Changing this value replaces the resource.
func (o GoogleTagOutput) TagId() pulumi.StringOutput {
	return o.ApplyT(func(v *GoogleTag) pulumi.StringOutput { return v.TagId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GoogleTagInput)(nil)).Elem(), &GoogleTag{})
	pulumi.RegisterOutputType(GoogleTagOutput{})
}
