// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package webflow

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-webflow/sdk/go/webflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Registers inline JavaScript in a Webflow site's script registry (POST /v2/sites/{site_id}/registered_scripts/inline). Registered scripts are applied to a site or page with the SiteCustomCode and PageCustomCode resources.
//
// **Authentication:** this resource calls Webflow custom code endpoints, which require an OAuth Data Client app token with the `custom_code:read` and `custom_code:write` scopes. Webflow documents that these scopes are available only to Data Client apps: site API tokens cannot access custom code endpoints.
//
// **IMPORTANT LIMITATION:** Webflow has no endpoint to update or unregister a registered script. Registrations are versioned and permanent (a site can hold up to 800). Changing sourceCode, displayName, scriptVersion, canCopy or integrityHash therefore registers a new script (a new version when only scriptVersion changes) and the previous registration remains in the registry. Destroying the resource is a logged no-op: the script stays registered and Pulumi simply stops managing it. Applied code is removed by SiteCustomCode and PageCustomCode. The list endpoint does not return sourceCode, so after an import the source is unknown until it is set in the program; Diff does not report a change for it in that case.
type InlineScript struct {
	pulumi.CustomResourceState

	// Indicates whether the script can be copied when the site is duplicated. Default: false. When true, the script will be included when creating a copy of the site.
	CanCopy pulumi.BoolPtrOutput `pulumi:"canCopy"`
	// The timestamp when the script was created (RFC3339 format). This is automatically set by Webflow when the script is created and is read-only.
	CreatedOn pulumi.StringPtrOutput `pulumi:"createdOn"`
	// The user-facing name for the script (1-50 characters: letters, digits and spaces). This name is used to identify the script in the Webflow interface and derives the scriptId. Changing it registers a new script; the previous registration remains. Example valid names: 'CMS Slider', 'AnalyticsScript', 'MyCustomScript123'.
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// The URI for the hosted version of the inline script (read-only). This is automatically set by Webflow after the inline script is registered.
	HostedLocation pulumi.StringPtrOutput `pulumi:"hostedLocation"`
	// The Sub-Resource Integrity (SRI) hash for the script (optional). Format: 'sha384-<hash>', 'sha256-<hash>', or 'sha512-<hash>'. SRI hashes help ensure that the script hasn't been modified in transit. You can generate an SRI hash using https://www.srihash.org/
	IntegrityHash pulumi.StringPtrOutput `pulumi:"integrityHash"`
	// The timestamp when the script was last updated (RFC3339 format). This is automatically updated by Webflow when the script is modified and is read-only.
	LastUpdated pulumi.StringPtrOutput `pulumi:"lastUpdated"`
	// The Webflow-assigned script ID (read-only). This is typically the lowercase version of displayName. Use this value when referencing the script in SiteCustomCode or PageCustomCode resources.
	ScriptId pulumi.StringOutput `pulumi:"scriptId"`
	// The Semantic Version (SemVer) string for the script (e.g., '1.0.0', '2.3.1'). Required by the Webflow register endpoint. Registered scripts are versioned: changing this value registers a new version of the script and the previous version remains registered. See https://semver.org/ for more information on semantic versioning.
	ScriptVersion pulumi.StringOutput `pulumi:"scriptVersion"`
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
	SiteId pulumi.StringOutput `pulumi:"siteId"`
	// The inline JavaScript code to register, limited to 2000 characters. This code will be directly embedded in your Webflow site. If your script exceeds 2000 characters, consider hosting it externally and using the RegisteredScript resource with a hostedLocation instead. Webflow does not return the source code when listing scripts, so it cannot be read back after import.
	SourceCode pulumi.StringOutput `pulumi:"sourceCode"`
}

// NewInlineScript registers a new resource with the given unique name, arguments, and options.
func NewInlineScript(ctx *pulumi.Context,
	name string, args *InlineScriptArgs, opts ...pulumi.ResourceOption) (*InlineScript, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DisplayName == nil {
		return nil, errors.New("invalid value for required argument 'DisplayName'")
	}
	if args.ScriptVersion == nil {
		return nil, errors.New("invalid value for required argument 'ScriptVersion'")
	}
	if args.SiteId == nil {
		return nil, errors.New("invalid value for required argument 'SiteId'")
	}
	if args.SourceCode == nil {
		return nil, errors.New("invalid value for required argument 'SourceCode'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource InlineScript
	err := ctx.RegisterResource("webflow:index:InlineScript", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetInlineScript gets an existing InlineScript resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetInlineScript(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *InlineScriptState, opts ...pulumi.ResourceOption) (*InlineScript, error) {
	var resource InlineScript
	err := ctx.ReadResource("webflow:index:InlineScript", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering InlineScript resources.
type inlineScriptState struct {
}

type InlineScriptState struct {
}

func (InlineScriptState) ElementType() reflect.Type {
	return reflect.TypeOf((*inlineScriptState)(nil)).Elem()
}

type inlineScriptArgs struct {
	// Indicates whether the script can be copied when the site is duplicated. Default: false. When true, the script will be included when creating a copy of the site.
	CanCopy *bool `pulumi:"canCopy"`
	// The user-facing name for the script (1-50 characters: letters, digits and spaces). This name is used to identify the script in the Webflow interface and derives the scriptId. Changing it registers a new script; the previous registration remains. Example valid names: 'CMS Slider', 'AnalyticsScript', 'MyCustomScript123'.
	DisplayName string `pulumi:"displayName"`
	// The Sub-Resource Integrity (SRI) hash for the script (optional). Format: 'sha384-<hash>', 'sha256-<hash>', or 'sha512-<hash>'. SRI hashes help ensure that the script hasn't been modified in transit. You can generate an SRI hash using https://www.srihash.org/
	IntegrityHash *string `pulumi:"integrityHash"`
	// The Semantic Version (SemVer) string for the script (e.g., '1.0.0', '2.3.1'). Required by the Webflow register endpoint. Registered scripts are versioned: changing this value registers a new version of the script and the previous version remains registered. See https://semver.org/ for more information on semantic versioning.
	ScriptVersion string `pulumi:"scriptVersion"`
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
	SiteId string `pulumi:"siteId"`
	// The inline JavaScript code to register, limited to 2000 characters. This code will be directly embedded in your Webflow site. If your script exceeds 2000 characters, consider hosting it externally and using the RegisteredScript resource with a hostedLocation instead. Webflow does not return the source code when listing scripts, so it cannot be read back after import.
	SourceCode string `pulumi:"sourceCode"`
}

// The set of arguments for constructing a InlineScript resource.
type InlineScriptArgs struct {
	// Indicates whether the script can be copied when the site is duplicated. Default: false. When true, the script will be included when creating a copy of the site.
	CanCopy pulumi.BoolPtrInput
	// The user-facing name for the script (1-50 characters: letters, digits and spaces). This name is used to identify the script in the Webflow interface and derives the scriptId. Changing it registers a new script; the previous registration remains. Example valid names: 'CMS Slider', 'AnalyticsScript', 'MyCustomScript123'.
	DisplayName pulumi.StringInput
	// The Sub-Resource Integrity (SRI) hash for the script (optional). Format: 'sha384-<hash>', 'sha256-<hash>', or 'sha512-<hash>'. SRI hashes help ensure that the script hasn't been modified in transit. You can generate an SRI hash using https://www.srihash.org/
	IntegrityHash pulumi.StringPtrInput
	// The Semantic Version (SemVer) string for the script (e.g., '1.0.0', '2.3.1'). Required by the Webflow register endpoint. Registered scripts are versioned: changing this value registers a new version of the script and the previous version remains registered. See https://semver.org/ for more information on semantic versioning.
	ScriptVersion pulumi.StringInput
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
	SiteId pulumi.StringInput
	// The inline JavaScript code to register, limited to 2000 characters. This code will be directly embedded in your Webflow site. If your script exceeds 2000 characters, consider hosting it externally and using the RegisteredScript resource with a hostedLocation instead. Webflow does not return the source code when listing scripts, so it cannot be read back after import.
	SourceCode pulumi.StringInput
}

func (InlineScriptArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*inlineScriptArgs)(nil)).Elem()
}

type InlineScriptInput interface {
	pulumi.Input

	ToInlineScriptOutput() InlineScriptOutput
	ToInlineScriptOutputWithContext(ctx context.Context) InlineScriptOutput
}

func (*InlineScript) ElementType() reflect.Type {
	return reflect.TypeOf((**InlineScript)(nil)).Elem()
}

func (i *InlineScript) ToInlineScriptOutput() InlineScriptOutput {
	return i.ToInlineScriptOutputWithContext(context.Background())
}

func (i *InlineScript) ToInlineScriptOutputWithContext(ctx context.Context) InlineScriptOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InlineScriptOutput)
}

type InlineScriptOutput struct{ *pulumi.OutputState }

func (InlineScriptOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**InlineScript)(nil)).Elem()
}

func (o InlineScriptOutput) ToInlineScriptOutput() InlineScriptOutput {
	return o
}

func (o InlineScriptOutput) ToInlineScriptOutputWithContext(ctx context.Context) InlineScriptOutput {
	return o
}

// Indicates whether the script can be copied when the site is duplicated. Default: false. When true, the script will be included when creating a copy of the site.
func (o InlineScriptOutput) CanCopy() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *InlineScript) pulumi.BoolPtrOutput { return v.CanCopy }).(pulumi.BoolPtrOutput)
}

// The timestamp when the script was created (RFC3339 format). This is automatically set by Webflow when the script is created and is read-only.
func (o InlineScriptOutput) CreatedOn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *InlineScript) pulumi.StringPtrOutput { return v.CreatedOn }).(pulumi.StringPtrOutput)
}

// The user-facing name for the script (1-50 characters: letters, digits and spaces). This name is used to identify the script in the Webflow interface and derives the scriptId. Changing it registers a new script; the previous registration remains. Example valid names: 'CMS Slider', 'AnalyticsScript', 'MyCustomScript123'.
func (o InlineScriptOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v *InlineScript) pulumi.StringOutput { return v.DisplayName }).(pulumi.StringOutput)
}

// The URI for the hosted version of the inline script (read-only). This is automatically set by Webflow after the inline script is registered.
func (o InlineScriptOutput) HostedLocation() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *InlineScript) pulumi.StringPtrOutput { return v.HostedLocation }).(pulumi.StringPtrOutput)
}

// The Sub-Resource Integrity (SRI) hash for the script (optional). Format: 'sha384-<hash>', 'sha256-<hash>', or 'sha512-<hash>'. SRI hashes help ensure that the script hasn't been modified in transit. You can generate an SRI hash using https://www.srihash.org/
func (o InlineScriptOutput) IntegrityHash() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *InlineScript) pulumi.StringPtrOutput { return v.IntegrityHash }).(pulumi.StringPtrOutput)
}

// The timestamp when the script was last updated (RFC3339 format). This is automatically updated by Webflow when the script is modified and is read-only.
func (o InlineScriptOutput) LastUpdated() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *InlineScript) pulumi.StringPtrOutput { return v.LastUpdated }).(pulumi.StringPtrOutput)
}

// The Webflow-assigned script ID (read-only). This is typically the lowercase version of displayName. Use this value when referencing the script in SiteCustomCode or PageCustomCode resources.
func (o InlineScriptOutput) ScriptId() pulumi.StringOutput {
	return o.ApplyT(func(v *InlineScript) pulumi.StringOutput { return v.ScriptId }).(pulumi.StringOutput)
}

// The Semantic Version (SemVer) string for the script (e.g., '1.0.0', '2.3.1'). Required by the Webflow register endpoint. Registered scripts are versioned: changing this value registers a new version of the script and the previous version remains registered. See https://semver.org/ for more information on semantic versioning.
func (o InlineScriptOutput) ScriptVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *InlineScript) pulumi.StringOutput { return v.ScriptVersion }).(pulumi.StringOutput)
}

// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
func (o InlineScriptOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *InlineScript) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

// The inline JavaScript code to register, limited to 2000 characters. This code will be directly embedded in your Webflow site. If your script exceeds 2000 characters, consider hosting it externally and using the RegisteredScript resource with a hostedLocation instead. Webflow does not return the source code when listing scripts, so it cannot be read back after import.
func (o InlineScriptOutput) SourceCode() pulumi.StringOutput {
	return o.ApplyT(func(v *InlineScript) pulumi.StringOutput { return v.SourceCode }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*InlineScriptInput)(nil)).Elem(), &InlineScript{})
	pulumi.RegisterOutputType(InlineScriptOutput{})
}
