// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package webflow

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-webflow/sdk/go/webflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Registers an externally hosted script in a Webflow site's script registry (POST /v2/sites/{site_id}/registered_scripts/hosted). Registered scripts are applied to a site or page with the SiteCustomCode and PageCustomCode resources. scriptVersion is required: the register endpoint rejects requests without one.
//
// **Authentication:** this resource calls Webflow custom code endpoints, which require an OAuth Data Client app token with the `custom_code:read` and `custom_code:write` scopes. Webflow documents that these scopes are available only to Data Client apps: site API tokens cannot access custom code endpoints.
//
// **IMPORTANT LIMITATION:** Webflow has no endpoint to update or unregister a registered script. Registrations are versioned and permanent (a site can hold up to 800). Changing displayName, hostedLocation, integrityHash, scriptVersion or canCopy therefore registers a new script (a new version when only scriptVersion changes) and the previous registration remains in the registry. Destroying the resource is a logged no-op: the script stays registered and Pulumi simply stops managing it. Applied code is removed by SiteCustomCode and PageCustomCode.
type RegisteredScript struct {
	pulumi.CustomResourceState

	// Indicates whether the script can be copied when the site is duplicated. Default: false. When true, the script will be included when creating a copy of the site.
	CanCopy pulumi.BoolPtrOutput `pulumi:"canCopy"`
	// The timestamp when the script was created (RFC3339 format). This is automatically set by Webflow when the script is created and is read-only.
	CreatedOn pulumi.StringPtrOutput `pulumi:"createdOn"`
	// The user-facing name for the script (1-50 characters: letters, digits and spaces). This name is used to identify the script in the Webflow interface and derives the scriptId. Changing it registers a new script; the previous registration remains. Example valid names: 'CMS Slider', 'AnalyticsScript', 'MyCustomScript123'.
	DisplayName pulumi.StringOutput `pulumi:"displayName"`
	// The URI for the externally hosted script (e.g., 'https://cdn.example.com/my-script.js'). Must be a valid HTTP or HTTPS URL. The script should be publicly accessible and properly configured for cross-origin requests.
	HostedLocation pulumi.StringOutput `pulumi:"hostedLocation"`
	// The Sub-Resource Integrity (SRI) hash for the script. Format: 'sha384-<hash>', 'sha256-<hash>', or 'sha512-<hash>'. SRI hashes help ensure that the script hasn't been modified in transit. You can generate an SRI hash using https://www.srihash.org/
	IntegrityHash pulumi.StringOutput `pulumi:"integrityHash"`
	// The timestamp when the script was last updated (RFC3339 format). This is automatically updated by Webflow when the script is modified and is read-only.
	LastUpdated pulumi.StringPtrOutput `pulumi:"lastUpdated"`
	// The Webflow-assigned script ID (read-only). This is typically the lowercase version of displayName. Use this value when referencing the script in SiteCustomCode or PageCustomCode resources.
	ScriptId pulumi.StringOutput `pulumi:"scriptId"`
	// The Semantic Version (SemVer) string for the script (e.g., '1.0.0', '2.3.1'). Required by the Webflow register endpoint. Registered scripts are versioned: changing this value registers a new version of the script and the previous version remains registered. See https://semver.org/ for more information on semantic versioning.
	ScriptVersion pulumi.StringOutput `pulumi:"scriptVersion"`
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
	SiteId pulumi.StringOutput `pulumi:"siteId"`
}

// NewRegisteredScript registers a new resource with the given unique name, arguments, and options.
func NewRegisteredScript(ctx *pulumi.Context,
	name string, args *RegisteredScriptArgs, opts ...pulumi.ResourceOption) (*RegisteredScript, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DisplayName == nil {
		return nil, errors.New("invalid value for required argument 'DisplayName'")
	}
	if args.HostedLocation == nil {
		return nil, errors.New("invalid value for required argument 'HostedLocation'")
	}
	if args.IntegrityHash == nil {
		return nil, errors.New("invalid value for required argument 'IntegrityHash'")
	}
	if args.ScriptVersion == nil {
		return nil, errors.New("invalid value for required argument 'ScriptVersion'")
	}
	if args.SiteId == nil {
		return nil, errors.New("invalid value for required argument 'SiteId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RegisteredScript
	err := ctx.RegisterResource("webflow:index:RegisteredScript", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRegisteredScript gets an existing RegisteredScript resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRegisteredScript(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RegisteredScriptState, opts ...pulumi.ResourceOption) (*RegisteredScript, error) {
	var resource RegisteredScript
	err := ctx.ReadResource("webflow:index:RegisteredScript", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RegisteredScript resources.
type registeredScriptState struct {
}

type RegisteredScriptState struct {
}

func (RegisteredScriptState) ElementType() reflect.Type {
	return reflect.TypeOf((*registeredScriptState)(nil)).Elem()
}

type registeredScriptArgs struct {
	// Indicates whether the script can be copied when the site is duplicated. Default: false. When true, the script will be included when creating a copy of the site.
	CanCopy *bool `pulumi:"canCopy"`
	// The user-facing name for the script (1-50 characters: letters, digits and spaces). This name is used to identify the script in the Webflow interface and derives the scriptId. Changing it registers a new script; the previous registration remains. Example valid names: 'CMS Slider', 'AnalyticsScript', 'MyCustomScript123'.
	DisplayName string `pulumi:"displayName"`
	// The URI for the externally hosted script (e.g., 'https://cdn.example.com/my-script.js'). Must be a valid HTTP or HTTPS URL. The script should be publicly accessible and properly configured for cross-origin requests.
	HostedLocation string `pulumi:"hostedLocation"`
	// The Sub-Resource Integrity (SRI) hash for the script. Format: 'sha384-<hash>', 'sha256-<hash>', or 'sha512-<hash>'. SRI hashes help ensure that the script hasn't been modified in transit. You can generate an SRI hash using https://www.srihash.org/
	IntegrityHash string `pulumi:"integrityHash"`
	// The Semantic Version (SemVer) string for the script (e.g., '1.0.0', '2.3.1'). Required by the Webflow register endpoint. Registered scripts are versioned: changing this value registers a new version of the script and the previous version remains registered. See https://semver.org/ for more information on semantic versioning.
	ScriptVersion string `pulumi:"scriptVersion"`
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
	SiteId string `pulumi:"siteId"`
}

// The set of arguments for constructing a RegisteredScript resource.
type RegisteredScriptArgs struct {
	// Indicates whether the script can be copied when the site is duplicated. Default: false. When true, the script will be included when creating a copy of the site.
	CanCopy pulumi.BoolPtrInput
	// The user-facing name for the script (1-50 characters: letters, digits and spaces). This name is used to identify the script in the Webflow interface and derives the scriptId. Changing it registers a new script; the previous registration remains. Example valid names: 'CMS Slider', 'AnalyticsScript', 'MyCustomScript123'.
	DisplayName pulumi.StringInput
	// The URI for the externally hosted script (e.g., 'https://cdn.example.com/my-script.js'). Must be a valid HTTP or HTTPS URL. The script should be publicly accessible and properly configured for cross-origin requests.
	HostedLocation pulumi.StringInput
	// The Sub-Resource Integrity (SRI) hash for the script. Format: 'sha384-<hash>', 'sha256-<hash>', or 'sha512-<hash>'. SRI hashes help ensure that the script hasn't been modified in transit. You can generate an SRI hash using https://www.srihash.org/
	IntegrityHash pulumi.StringInput
	// The Semantic Version (SemVer) string for the script (e.g., '1.0.0', '2.3.1'). Required by the Webflow register endpoint. Registered scripts are versioned: changing this value registers a new version of the script and the previous version remains registered. See https://semver.org/ for more information on semantic versioning.
	ScriptVersion pulumi.StringInput
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
	SiteId pulumi.StringInput
}

func (RegisteredScriptArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*registeredScriptArgs)(nil)).Elem()
}

type RegisteredScriptInput interface {
	pulumi.Input

	ToRegisteredScriptOutput() RegisteredScriptOutput
	ToRegisteredScriptOutputWithContext(ctx context.Context) RegisteredScriptOutput
}

func (*RegisteredScript) ElementType() reflect.Type {
	return reflect.TypeOf((**RegisteredScript)(nil)).Elem()
}

func (i *RegisteredScript) ToRegisteredScriptOutput() RegisteredScriptOutput {
	return i.ToRegisteredScriptOutputWithContext(context.Background())
}

func (i *RegisteredScript) ToRegisteredScriptOutputWithContext(ctx context.Context) RegisteredScriptOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RegisteredScriptOutput)
}

type RegisteredScriptOutput struct{ *pulumi.OutputState }

func (RegisteredScriptOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RegisteredScript)(nil)).Elem()
}

func (o RegisteredScriptOutput) ToRegisteredScriptOutput() RegisteredScriptOutput {
	return o
}

func (o RegisteredScriptOutput) ToRegisteredScriptOutputWithContext(ctx context.Context) RegisteredScriptOutput {
	return o
}

// Indicates whether the script can be copied when the site is duplicated. Default: false. When true, the script will be included when creating a copy of the site.
func (o RegisteredScriptOutput) CanCopy() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *RegisteredScript) pulumi.BoolPtrOutput { return v.CanCopy }).(pulumi.BoolPtrOutput)
}

// The timestamp when the script was created (RFC3339 format). This is automatically set by Webflow when the script is created and is read-only.
func (o RegisteredScriptOutput) CreatedOn() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RegisteredScript) pulumi.StringPtrOutput { return v.CreatedOn }).(pulumi.StringPtrOutput)
}

// The user-facing name for the script (1-50 characters: letters, digits and spaces). This name is used to identify the script in the Webflow interface and derives the scriptId. Changing it registers a new script; the previous registration remains. Example valid names: 'CMS Slider', 'AnalyticsScript', 'MyCustomScript123'.
func (o RegisteredScriptOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredScript) pulumi.StringOutput { return v.DisplayName }).(pulumi.StringOutput)
}

// The URI for the externally hosted script (e.g., 'https://cdn.example.com/my-script.js'). Must be a valid HTTP or HTTPS URL. The script should be publicly accessible and properly configured for cross-origin requests.
func (o RegisteredScriptOutput) HostedLocation() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredScript) pulumi.StringOutput { return v.HostedLocation }).(pulumi.StringOutput)
}

// The Sub-Resource Integrity (SRI) hash for the script. Format: 'sha384-<hash>', 'sha256-<hash>', or 'sha512-<hash>'. SRI hashes help ensure that the script hasn't been modified in transit. You can generate an SRI hash using https://www.srihash.org/
func (o RegisteredScriptOutput) IntegrityHash() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredScript) pulumi.StringOutput { return v.IntegrityHash }).(pulumi.StringOutput)
}

// The timestamp when the script was last updated (RFC3339 format). This is automatically updated by Webflow when the script is modified and is read-only.
func (o RegisteredScriptOutput) LastUpdated() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RegisteredScript) pulumi.StringPtrOutput { return v.LastUpdated }).(pulumi.StringPtrOutput)
}

// The Webflow-assigned script ID (read-only). This is typically the lowercase version of displayName. Use this value when referencing the script in SiteCustomCode or PageCustomCode resources.
func (o RegisteredScriptOutput) ScriptId() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredScript) pulumi.StringOutput { return v.ScriptId }).(pulumi.StringOutput)
}

// The Semantic Version (SemVer) string for the script (e.g., '1.0.0', '2.3.1'). Required by the Webflow register endpoint. Registered scripts are versioned: changing this value registers a new version of the script and the previous version remains registered. See https://semver.org/ for more information on semantic versioning.
func (o RegisteredScriptOutput) ScriptVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredScript) pulumi.StringOutput { return v.ScriptVersion }).(pulumi.StringOutput)
}

// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
func (o RegisteredScriptOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *RegisteredScript) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RegisteredScriptInput)(nil)).Elem(), &RegisteredScript{})
	pulumi.RegisterOutputType(RegisteredScriptOutput{})
}
