// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package webflow

import (
	"context"
	"reflect"

	"errors"
	"github.com/JDetmar/pulumi-webflow/sdk/go/webflow/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Manages robots.txt configuration for a Webflow site. This resource allows you to define crawler access rules and sitemap references.
type RobotsTxt struct {
	pulumi.CustomResourceState

	// The robots.txt content in traditional format. Supports User-agent, Allow, Disallow, and Sitemap directives. Comments and other directives are not stored by Webflow and are dropped with a warning. Formatting differences (blank lines, spacing, directive casing) do not cause a diff.
	Content pulumi.StringOutput `pulumi:"content"`
	// RFC3339 timestamp of the last modification.
	LastModified pulumi.StringOutput `pulumi:"lastModified"`
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3').
	SiteId pulumi.StringOutput `pulumi:"siteId"`
}

// NewRobotsTxt registers a new resource with the given unique name, arguments, and options.
func NewRobotsTxt(ctx *pulumi.Context,
	name string, args *RobotsTxtArgs, opts ...pulumi.ResourceOption) (*RobotsTxt, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Content == nil {
		return nil, errors.New("invalid value for required argument 'Content'")
	}
	if args.SiteId == nil {
		return nil, errors.New("invalid value for required argument 'SiteId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RobotsTxt
	err := ctx.RegisterResource("webflow:index:RobotsTxt", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRobotsTxt gets an existing RobotsTxt resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRobotsTxt(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RobotsTxtState, opts ...pulumi.ResourceOption) (*RobotsTxt, error) {
	var resource RobotsTxt
	err := ctx.ReadResource("webflow:index:RobotsTxt", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RobotsTxt resources.
type robotsTxtState struct {
}

type RobotsTxtState struct {
}

func (RobotsTxtState) ElementType() reflect.Type {
	return reflect.TypeOf((*robotsTxtState)(nil)).Elem()
}

type robotsTxtArgs struct {
	// The robots.txt content in traditional format. Supports User-agent, Allow, Disallow, and Sitemap directives. Comments and other directives are not stored by Webflow and are dropped with a warning. Formatting differences (blank lines, spacing, directive casing) do not cause a diff.
	Content string `pulumi:"content"`
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3').
	SiteId string `pulumi:"siteId"`
}

// The set of arguments for constructing a RobotsTxt resource.
type RobotsTxtArgs struct {
	// The robots.txt content in traditional format. Supports User-agent, Allow, Disallow, and Sitemap directives. Comments and other directives are not stored by Webflow and are dropped with a warning. Formatting differences (blank lines, spacing, directive casing) do not cause a diff.
	Content pulumi.StringInput
	// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3').
	SiteId pulumi.StringInput
}

func (RobotsTxtArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*robotsTxtArgs)(nil)).Elem()
}

type RobotsTxtInput interface {
	pulumi.Input

	ToRobotsTxtOutput() RobotsTxtOutput
	ToRobotsTxtOutputWithContext(ctx context.Context) RobotsTxtOutput
}

func (*RobotsTxt) ElementType() reflect.Type {
	return reflect.TypeOf((**RobotsTxt)(nil)).Elem()
}

func (i *RobotsTxt) ToRobotsTxtOutput() RobotsTxtOutput {
	return i.ToRobotsTxtOutputWithContext(context.Background())
}

func (i *RobotsTxt) ToRobotsTxtOutputWithContext(ctx context.Context) RobotsTxtOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RobotsTxtOutput)
}

type RobotsTxtOutput struct{ *pulumi.OutputState }

func (RobotsTxtOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RobotsTxt)(nil)).Elem()
}

func (o RobotsTxtOutput) ToRobotsTxtOutput() RobotsTxtOutput {
	return o
}

func (o RobotsTxtOutput) ToRobotsTxtOutputWithContext(ctx context.Context) RobotsTxtOutput {
	return o
}

// The robots.txt content in traditional format. Supports User-agent, Allow, Disallow, and Sitemap directives. Comments and other directives are not stored by Webflow and are dropped with a warning. Formatting differences (blank lines, spacing, directive casing) do not cause a diff.
func (o RobotsTxtOutput) Content() pulumi.StringOutput {
	return o.ApplyT(func(v *RobotsTxt) pulumi.StringOutput { return v.Content }).(pulumi.StringOutput)
}

// RFC3339 timestamp of the last modification.
func (o RobotsTxtOutput) LastModified() pulumi.StringOutput {
	return o.ApplyT(func(v *RobotsTxt) pulumi.StringOutput { return v.LastModified }).(pulumi.StringOutput)
}

// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3').
func (o RobotsTxtOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *RobotsTxt) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RobotsTxtInput)(nil)).Elem(), &RobotsTxt{})
	pulumi.RegisterOutputType(RobotsTxtOutput{})
}
