import * as pulumi from "@pulumi/pulumi";
import * as webflow from "@jdetmar/pulumi-webflow";
import * as fs from "fs";
import * as yaml from "js-yaml";

// Example: Configuration-driven multi-site management
// Load site configurations from YAML for scalable fleet management

// Site creation requires an Enterprise workspace ID (pulumi config set workspaceId ...)
const pulumiConfig = new pulumi.Config();
const workspaceId = pulumiConfig.require("workspaceId");

// shortName and timeZone are generated by Webflow and exposed as outputs, so they
// are not part of the per-site configuration.
interface SiteConfig {
  name: string;
  displayName: string;
  // Webflow redirects are always 301; there is no status code to configure.
  redirects?: Array<{
    sourcePath: string;
    destinationPath: string;
  }>;
  robotsTxtContent?: string;
}

interface ConfigFile {
  sites: SiteConfig[];
  defaults?: {
    robotsTxtContent?: string;
  };
}

// Load configuration from YAML file
const configPath = "./sites.yaml";
const configContent = fs.readFileSync(configPath, "utf8");
const config = yaml.load(configContent) as ConfigFile;

// Get default values
const defaultRobotsTxt =
  config.defaults?.robotsTxtContent ||
  `User-agent: *
Allow: /`;

// Create all sites from configuration
const sites = config.sites.map((siteConfig) => {
  // Use defaults where not specified
  const robotsTxtContent = siteConfig.robotsTxtContent || defaultRobotsTxt;

  // Create the site
  const site = new webflow.Site(siteConfig.name, {
    workspaceId: workspaceId,
    displayName: siteConfig.displayName,
  });

  // Add robots.txt configuration
  new webflow.RobotsTxt(`${siteConfig.name}-robots`, {
    siteId: site.id,
    content: robotsTxtContent,
  });

  // Add redirects if specified
  if (siteConfig.redirects && siteConfig.redirects.length > 0) {
    siteConfig.redirects.forEach((redirect, idx) => {
      new webflow.Redirect(`${siteConfig.name}-redirect-${idx}`, {
        siteId: site.id,
        sourcePath: redirect.sourcePath,
        destinationPath: redirect.destinationPath,
      });
    });
  }

  return site;
});

// Export information about deployed sites
// (stack outputs in TypeScript are top-level `export`s)
export const deployedSites = config.sites.length;
export const siteNames = config.sites.map((s) => s.name);

// Export individual site IDs and the Webflow-generated short names, keyed by site name
export const siteIds: Record<string, pulumi.Output<string>> = {};
export const siteShortNames: Record<string, pulumi.Output<string | undefined>> = {};
config.sites.forEach((siteConfig, idx) => {
  siteIds[siteConfig.name] = sites[idx].id;
  siteShortNames[siteConfig.name] = sites[idx].shortName;
});

// Export all site IDs
export const allSiteIds = sites.map((site) => site.id);
