package main

import (
	"fmt"

	"github.com/JDetmar/pulumi-webflow/sdk/go/webflow"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// Site Example - Creating and Managing Webflow Sites
//
// Required inputs: WorkspaceId (Enterprise workspace) and DisplayName.
// ShortName and TimeZone are read-only outputs generated by Webflow.
func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		cfg := config.New(ctx, "")
		workspaceID := cfg.Require("workspaceId")
		displayName := cfg.Require("displayName")

		// Example 1: Basic Site Creation
		basicSite, err := webflow.NewSite(ctx, "basic-site", &webflow.SiteArgs{
			WorkspaceId: pulumi.String(workspaceID),
			DisplayName: pulumi.String(displayName),
		})
		if err != nil {
			return fmt.Errorf("failed to create basic site: %w", err)
		}

		// Example 2: Multi-Environment Site Configuration
		environments := []string{"development", "staging", "production"}
		environmentSites := make([]*webflow.Site, 0)
		for _, env := range environments {
			site, err := webflow.NewSite(ctx, fmt.Sprintf("site-%s", env), &webflow.SiteArgs{
				WorkspaceId: pulumi.String(workspaceID),
				DisplayName: pulumi.String(fmt.Sprintf("%s-%s", displayName, env)),
			})
			if err != nil {
				return fmt.Errorf("failed to create site %s: %w", env, err)
			}
			environmentSites = append(environmentSites, site)
		}

		// Example 3: Site with Optional Configuration
		configuredArgs := &webflow.SiteArgs{
			WorkspaceId: pulumi.String(workspaceID),
			DisplayName: pulumi.String(fmt.Sprintf("%s-configured", displayName)),
			// Do not auto-publish; enable after the first manual publish in the Designer
			Publish: pulumi.Bool(false),
		}
		// Optional: organize the site in a workspace folder
		if v := cfg.Get("parentFolderId"); v != "" {
			configuredArgs.ParentFolderId = pulumi.String(v)
		}
		// Optional and IMMUTABLE: changing it later replaces (deletes + recreates) the site
		if v := cfg.Get("templateName"); v != "" {
			configuredArgs.TemplateName = pulumi.String(v)
		}
		configuredSite, err := webflow.NewSite(ctx, "configured-site", configuredArgs)
		if err != nil {
			return fmt.Errorf("failed to create configured site: %w", err)
		}

		// Export values
		ctx.Export("basicSiteId", basicSite.ID())
		ctx.Export("basicSiteName", basicSite.DisplayName)
		// ShortName and TimeZone are generated by Webflow and available as outputs
		ctx.Export("basicSiteShortName", basicSite.ShortName)
		ctx.Export("basicSiteTimeZone", basicSite.TimeZone)

		siteIds := make(pulumi.StringArray, len(environmentSites))
		for i, site := range environmentSites {
			siteIds[i] = site.ID().ToStringOutput()
		}
		ctx.Export("environmentSiteIds", siteIds)
		ctx.Export("configuredSiteId", configuredSite.ID())

		ctx.Log.Info(
			fmt.Sprintf("✅ Successfully created %d sites", len(environmentSites)+2),
			nil,
		)

		return nil
	})
}
