// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class AnalyticsTimeseriesArgs extends com.pulumi.resources.InvokeArgs {

    public static final AnalyticsTimeseriesArgs Empty = new AnalyticsTimeseriesArgs();

    /**
     * IANA time zone used to align daily bucket boundaries (e.g., &#39;UTC&#39;, &#39;America/New_York&#39;). Bucket timestamps are returned as UTC instants of local midnight in this zone.
     * 
     */
    @Import(name="bucketTimeZone", required=true)
    private String bucketTimeZone;

    /**
     * @return IANA time zone used to align daily bucket boundaries (e.g., &#39;UTC&#39;, &#39;America/New_York&#39;). Bucket timestamps are returned as UTC instants of local midnight in this zone.
     * 
     */
    public String bucketTimeZone() {
        return this.bucketTimeZone;
    }

    private AnalyticsTimeseriesArgs() {}

    private AnalyticsTimeseriesArgs(AnalyticsTimeseriesArgs $) {
        this.bucketTimeZone = $.bucketTimeZone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AnalyticsTimeseriesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AnalyticsTimeseriesArgs $;

        public Builder() {
            $ = new AnalyticsTimeseriesArgs();
        }

        public Builder(AnalyticsTimeseriesArgs defaults) {
            $ = new AnalyticsTimeseriesArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param bucketTimeZone IANA time zone used to align daily bucket boundaries (e.g., &#39;UTC&#39;, &#39;America/New_York&#39;). Bucket timestamps are returned as UTC instants of local midnight in this zone.
         * 
         * @return builder
         * 
         */
        public Builder bucketTimeZone(String bucketTimeZone) {
            $.bucketTimeZone = bucketTimeZone;
            return this;
        }

        public AnalyticsTimeseriesArgs build() {
            if ($.bucketTimeZone == null) {
                throw new MissingRequiredPropertyException("AnalyticsTimeseriesArgs", "bucketTimeZone");
            }
            return $;
        }
    }

}
