// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AnalyticsDimensionFilter extends com.pulumi.resources.InvokeArgs {

    public static final AnalyticsDimensionFilter Empty = new AnalyticsDimensionFilter();

    /**
     * Keep only rows whose dimension value equals this value.
     * 
     */
    @Import(name="eq")
    private @Nullable String eq;

    /**
     * @return Keep only rows whose dimension value equals this value.
     * 
     */
    public Optional<String> eq() {
        return Optional.ofNullable(this.eq);
    }

    /**
     * Keep only rows whose dimension value is one of these values.
     * 
     */
    @Import(name="in")
    private @Nullable List<String> in;

    /**
     * @return Keep only rows whose dimension value is one of these values.
     * 
     */
    public Optional<List<String>> in() {
        return Optional.ofNullable(this.in);
    }

    /**
     * Exclude rows whose dimension value equals this value.
     * 
     */
    @Import(name="ne")
    private @Nullable String ne;

    /**
     * @return Exclude rows whose dimension value equals this value.
     * 
     */
    public Optional<String> ne() {
        return Optional.ofNullable(this.ne);
    }

    /**
     * Exclude rows whose dimension value is one of these values.
     * 
     */
    @Import(name="nin")
    private @Nullable List<String> nin;

    /**
     * @return Exclude rows whose dimension value is one of these values.
     * 
     */
    public Optional<List<String>> nin() {
        return Optional.ofNullable(this.nin);
    }

    private AnalyticsDimensionFilter() {}

    private AnalyticsDimensionFilter(AnalyticsDimensionFilter $) {
        this.eq = $.eq;
        this.in = $.in;
        this.ne = $.ne;
        this.nin = $.nin;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AnalyticsDimensionFilter defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AnalyticsDimensionFilter $;

        public Builder() {
            $ = new AnalyticsDimensionFilter();
        }

        public Builder(AnalyticsDimensionFilter defaults) {
            $ = new AnalyticsDimensionFilter(Objects.requireNonNull(defaults));
        }

        /**
         * @param eq Keep only rows whose dimension value equals this value.
         * 
         * @return builder
         * 
         */
        public Builder eq(@Nullable String eq) {
            $.eq = eq;
            return this;
        }

        /**
         * @param in Keep only rows whose dimension value is one of these values.
         * 
         * @return builder
         * 
         */
        public Builder in(@Nullable List<String> in) {
            $.in = in;
            return this;
        }

        /**
         * @param in Keep only rows whose dimension value is one of these values.
         * 
         * @return builder
         * 
         */
        public Builder in(String... in) {
            return in(List.of(in));
        }

        /**
         * @param ne Exclude rows whose dimension value equals this value.
         * 
         * @return builder
         * 
         */
        public Builder ne(@Nullable String ne) {
            $.ne = ne;
            return this;
        }

        /**
         * @param nin Exclude rows whose dimension value is one of these values.
         * 
         * @return builder
         * 
         */
        public Builder nin(@Nullable List<String> nin) {
            $.nin = nin;
            return this;
        }

        /**
         * @param nin Exclude rows whose dimension value is one of these values.
         * 
         * @return builder
         * 
         */
        public Builder nin(String... nin) {
            return nin(List.of(nin));
        }

        public AnalyticsDimensionFilter build() {
            return $;
        }
    }

}
