// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.jdetmar.pulumi.webflow.inputs.AnalyticsDimensionFilter;
import io.github.jdetmar.pulumi.webflow.inputs.AnalyticsTimeseriesArgs;
import java.lang.Integer;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetAnalyticsTopEventsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAnalyticsTopEventsPlainArgs Empty = new GetAnalyticsTopEventsPlainArgs();

    /**
     * Restrict the report to a single browser name (e.g., &#39;Chrome&#39;).
     * 
     */
    @Import(name="browser")
    private @Nullable String browser;

    /**
     * @return Restrict the report to a single browser name (e.g., &#39;Chrome&#39;).
     * 
     */
    public Optional<String> browser() {
        return Optional.ofNullable(this.browser);
    }

    /**
     * Restrict the report to a single country, as an ISO 3166-1 alpha-2 code (e.g., &#39;US&#39;). Normalized to uppercase.
     * 
     */
    @Import(name="country")
    private @Nullable String country;

    /**
     * @return Restrict the report to a single country, as an ISO 3166-1 alpha-2 code (e.g., &#39;US&#39;). Normalized to uppercase.
     * 
     */
    public Optional<String> country() {
        return Optional.ofNullable(this.country);
    }

    /**
     * Restrict the report to a single device type: &#39;desktop&#39;, &#39;mobile&#39; or &#39;tablet&#39;.
     * 
     */
    @Import(name="deviceType")
    private @Nullable String deviceType;

    /**
     * @return Restrict the report to a single device type: &#39;desktop&#39;, &#39;mobile&#39; or &#39;tablet&#39;.
     * 
     */
    public Optional<String> deviceType() {
        return Optional.ofNullable(this.deviceType);
    }

    /**
     * Exclusive end of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in &#39;Z&#39; (e.g., &#39;2026-04-01T00:00:00Z&#39;). Numeric offsets are not accepted. Must be after startTime and within 100 days of it.
     * 
     */
    @Import(name="endTime", required=true)
    private String endTime;

    /**
     * @return Exclusive end of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in &#39;Z&#39; (e.g., &#39;2026-04-01T00:00:00Z&#39;). Numeric offsets are not accepted. Must be after startTime and within 100 days of it.
     * 
     */
    public String endTime() {
        return this.endTime;
    }

    /**
     * Advanced filters keyed by dimension (e.g., &#39;country&#39;, &#39;deviceType&#39;, &#39;pagePath&#39;, &#39;referrer&#39;, &#39;trafficSource&#39;, &#39;utmCampaign&#39;, &#39;os&#39;, &#39;language&#39;, &#39;locale&#39;, &#39;region&#39;, &#39;audienceIds&#39;, &#39;collectionId&#39;, &#39;itemSlug&#39;, &#39;pageId&#39;, &#39;dayOfWeek&#39;, &#39;timeOfDay&#39;, &#39;visitStatus&#39;, ...). Each entry supports &#39;eq&#39;, &#39;in&#39;, &#39;ne&#39; and &#39;nin&#39;. Filter a given dimension either here or with the matching single-value input, not both.
     * 
     */
    @Import(name="filters")
    private @Nullable Map<String,AnalyticsDimensionFilter> filters;

    /**
     * @return Advanced filters keyed by dimension (e.g., &#39;country&#39;, &#39;deviceType&#39;, &#39;pagePath&#39;, &#39;referrer&#39;, &#39;trafficSource&#39;, &#39;utmCampaign&#39;, &#39;os&#39;, &#39;language&#39;, &#39;locale&#39;, &#39;region&#39;, &#39;audienceIds&#39;, &#39;collectionId&#39;, &#39;itemSlug&#39;, &#39;pageId&#39;, &#39;dayOfWeek&#39;, &#39;timeOfDay&#39;, &#39;visitStatus&#39;, ...). Each entry supports &#39;eq&#39;, &#39;in&#39;, &#39;ne&#39; and &#39;nin&#39;. Filter a given dimension either here or with the matching single-value input, not both.
     * 
     */
    public Optional<Map<String,AnalyticsDimensionFilter>> filters() {
        return Optional.ofNullable(this.filters);
    }

    /**
     * Maximum number of rows to return. Defaults to 25, up to a maximum of 250.
     * 
     */
    @Import(name="limit")
    private @Nullable Integer limit;

    /**
     * @return Maximum number of rows to return. Defaults to 25, up to a maximum of 250.
     * 
     */
    public Optional<Integer> limit() {
        return Optional.ofNullable(this.limit);
    }

    /**
     * Restrict the report to a single page path (e.g., &#39;/pricing&#39;).
     * 
     */
    @Import(name="pagePath")
    private @Nullable String pagePath;

    /**
     * @return Restrict the report to a single page path (e.g., &#39;/pricing&#39;).
     * 
     */
    public Optional<String> pagePath() {
        return Optional.ofNullable(this.pagePath);
    }

    /**
     * Restrict the report to a single referrer domain (e.g., &#39;google.com&#39;).
     * 
     */
    @Import(name="referrer")
    private @Nullable String referrer;

    /**
     * @return Restrict the report to a single referrer domain (e.g., &#39;google.com&#39;).
     * 
     */
    public Optional<String> referrer() {
        return Optional.ofNullable(this.referrer);
    }

    /**
     * The Webflow site ID (24-character lowercase hexadecimal string).
     * 
     */
    @Import(name="siteId", required=true)
    private String siteId;

    /**
     * @return The Webflow site ID (24-character lowercase hexadecimal string).
     * 
     */
    public String siteId() {
        return this.siteId;
    }

    /**
     * Inclusive start of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in &#39;Z&#39; (e.g., &#39;2026-04-01T00:00:00Z&#39;). Numeric offsets are not accepted. Must be on or after 2025-04-09T00:00:00Z.
     * 
     */
    @Import(name="startTime", required=true)
    private String startTime;

    /**
     * @return Inclusive start of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in &#39;Z&#39; (e.g., &#39;2026-04-01T00:00:00Z&#39;). Numeric offsets are not accepted. Must be on or after 2025-04-09T00:00:00Z.
     * 
     */
    public String startTime() {
        return this.startTime;
    }

    /**
     * Include a daily event count time series for each event, bucketed in the given IANA time zone. Omit to return ranked rows only.
     * 
     */
    @Import(name="timeseries")
    private @Nullable AnalyticsTimeseriesArgs timeseries;

    /**
     * @return Include a daily event count time series for each event, bucketed in the given IANA time zone. Omit to return ranked rows only.
     * 
     */
    public Optional<AnalyticsTimeseriesArgs> timeseries() {
        return Optional.ofNullable(this.timeseries);
    }

    /**
     * Restrict the report to a single traffic source code (e.g., &#39;SO&#39; for Organic Search).
     * 
     */
    @Import(name="trafficSource")
    private @Nullable String trafficSource;

    /**
     * @return Restrict the report to a single traffic source code (e.g., &#39;SO&#39; for Organic Search).
     * 
     */
    public Optional<String> trafficSource() {
        return Optional.ofNullable(this.trafficSource);
    }

    /**
     * Restrict the report to a single utm_campaign value.
     * 
     */
    @Import(name="utmCampaign")
    private @Nullable String utmCampaign;

    /**
     * @return Restrict the report to a single utm_campaign value.
     * 
     */
    public Optional<String> utmCampaign() {
        return Optional.ofNullable(this.utmCampaign);
    }

    /**
     * Restrict the report to a single utm_medium value.
     * 
     */
    @Import(name="utmMedium")
    private @Nullable String utmMedium;

    /**
     * @return Restrict the report to a single utm_medium value.
     * 
     */
    public Optional<String> utmMedium() {
        return Optional.ofNullable(this.utmMedium);
    }

    /**
     * Restrict the report to a single utm_source value.
     * 
     */
    @Import(name="utmSource")
    private @Nullable String utmSource;

    /**
     * @return Restrict the report to a single utm_source value.
     * 
     */
    public Optional<String> utmSource() {
        return Optional.ofNullable(this.utmSource);
    }

    private GetAnalyticsTopEventsPlainArgs() {}

    private GetAnalyticsTopEventsPlainArgs(GetAnalyticsTopEventsPlainArgs $) {
        this.browser = $.browser;
        this.country = $.country;
        this.deviceType = $.deviceType;
        this.endTime = $.endTime;
        this.filters = $.filters;
        this.limit = $.limit;
        this.pagePath = $.pagePath;
        this.referrer = $.referrer;
        this.siteId = $.siteId;
        this.startTime = $.startTime;
        this.timeseries = $.timeseries;
        this.trafficSource = $.trafficSource;
        this.utmCampaign = $.utmCampaign;
        this.utmMedium = $.utmMedium;
        this.utmSource = $.utmSource;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAnalyticsTopEventsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAnalyticsTopEventsPlainArgs $;

        public Builder() {
            $ = new GetAnalyticsTopEventsPlainArgs();
        }

        public Builder(GetAnalyticsTopEventsPlainArgs defaults) {
            $ = new GetAnalyticsTopEventsPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param browser Restrict the report to a single browser name (e.g., &#39;Chrome&#39;).
         * 
         * @return builder
         * 
         */
        public Builder browser(@Nullable String browser) {
            $.browser = browser;
            return this;
        }

        /**
         * @param country Restrict the report to a single country, as an ISO 3166-1 alpha-2 code (e.g., &#39;US&#39;). Normalized to uppercase.
         * 
         * @return builder
         * 
         */
        public Builder country(@Nullable String country) {
            $.country = country;
            return this;
        }

        /**
         * @param deviceType Restrict the report to a single device type: &#39;desktop&#39;, &#39;mobile&#39; or &#39;tablet&#39;.
         * 
         * @return builder
         * 
         */
        public Builder deviceType(@Nullable String deviceType) {
            $.deviceType = deviceType;
            return this;
        }

        /**
         * @param endTime Exclusive end of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in &#39;Z&#39; (e.g., &#39;2026-04-01T00:00:00Z&#39;). Numeric offsets are not accepted. Must be after startTime and within 100 days of it.
         * 
         * @return builder
         * 
         */
        public Builder endTime(String endTime) {
            $.endTime = endTime;
            return this;
        }

        /**
         * @param filters Advanced filters keyed by dimension (e.g., &#39;country&#39;, &#39;deviceType&#39;, &#39;pagePath&#39;, &#39;referrer&#39;, &#39;trafficSource&#39;, &#39;utmCampaign&#39;, &#39;os&#39;, &#39;language&#39;, &#39;locale&#39;, &#39;region&#39;, &#39;audienceIds&#39;, &#39;collectionId&#39;, &#39;itemSlug&#39;, &#39;pageId&#39;, &#39;dayOfWeek&#39;, &#39;timeOfDay&#39;, &#39;visitStatus&#39;, ...). Each entry supports &#39;eq&#39;, &#39;in&#39;, &#39;ne&#39; and &#39;nin&#39;. Filter a given dimension either here or with the matching single-value input, not both.
         * 
         * @return builder
         * 
         */
        public Builder filters(@Nullable Map<String,AnalyticsDimensionFilter> filters) {
            $.filters = filters;
            return this;
        }

        /**
         * @param limit Maximum number of rows to return. Defaults to 25, up to a maximum of 250.
         * 
         * @return builder
         * 
         */
        public Builder limit(@Nullable Integer limit) {
            $.limit = limit;
            return this;
        }

        /**
         * @param pagePath Restrict the report to a single page path (e.g., &#39;/pricing&#39;).
         * 
         * @return builder
         * 
         */
        public Builder pagePath(@Nullable String pagePath) {
            $.pagePath = pagePath;
            return this;
        }

        /**
         * @param referrer Restrict the report to a single referrer domain (e.g., &#39;google.com&#39;).
         * 
         * @return builder
         * 
         */
        public Builder referrer(@Nullable String referrer) {
            $.referrer = referrer;
            return this;
        }

        /**
         * @param siteId The Webflow site ID (24-character lowercase hexadecimal string).
         * 
         * @return builder
         * 
         */
        public Builder siteId(String siteId) {
            $.siteId = siteId;
            return this;
        }

        /**
         * @param startTime Inclusive start of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in &#39;Z&#39; (e.g., &#39;2026-04-01T00:00:00Z&#39;). Numeric offsets are not accepted. Must be on or after 2025-04-09T00:00:00Z.
         * 
         * @return builder
         * 
         */
        public Builder startTime(String startTime) {
            $.startTime = startTime;
            return this;
        }

        /**
         * @param timeseries Include a daily event count time series for each event, bucketed in the given IANA time zone. Omit to return ranked rows only.
         * 
         * @return builder
         * 
         */
        public Builder timeseries(@Nullable AnalyticsTimeseriesArgs timeseries) {
            $.timeseries = timeseries;
            return this;
        }

        /**
         * @param trafficSource Restrict the report to a single traffic source code (e.g., &#39;SO&#39; for Organic Search).
         * 
         * @return builder
         * 
         */
        public Builder trafficSource(@Nullable String trafficSource) {
            $.trafficSource = trafficSource;
            return this;
        }

        /**
         * @param utmCampaign Restrict the report to a single utm_campaign value.
         * 
         * @return builder
         * 
         */
        public Builder utmCampaign(@Nullable String utmCampaign) {
            $.utmCampaign = utmCampaign;
            return this;
        }

        /**
         * @param utmMedium Restrict the report to a single utm_medium value.
         * 
         * @return builder
         * 
         */
        public Builder utmMedium(@Nullable String utmMedium) {
            $.utmMedium = utmMedium;
            return this;
        }

        /**
         * @param utmSource Restrict the report to a single utm_source value.
         * 
         * @return builder
         * 
         */
        public Builder utmSource(@Nullable String utmSource) {
            $.utmSource = utmSource;
            return this;
        }

        public GetAnalyticsTopEventsPlainArgs build() {
            if ($.endTime == null) {
                throw new MissingRequiredPropertyException("GetAnalyticsTopEventsPlainArgs", "endTime");
            }
            if ($.siteId == null) {
                throw new MissingRequiredPropertyException("GetAnalyticsTopEventsPlainArgs", "siteId");
            }
            if ($.startTime == null) {
                throw new MissingRequiredPropertyException("GetAnalyticsTopEventsPlainArgs", "startTime");
            }
            return $;
        }
    }

}
