// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPagePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetPagePlainArgs Empty = new GetPagePlainArgs();

    /**
     * Optional locale ID. When omitted the primary locale is returned.
     * 
     */
    @Import(name="localeId")
    private @Nullable String localeId;

    /**
     * @return Optional locale ID. When omitted the primary locale is returned.
     * 
     */
    public Optional<String> localeId() {
        return Optional.ofNullable(this.localeId);
    }

    /**
     * The Webflow page ID (24-character lowercase hexadecimal string).
     * 
     */
    @Import(name="pageId", required=true)
    private String pageId;

    /**
     * @return The Webflow page ID (24-character lowercase hexadecimal string).
     * 
     */
    public String pageId() {
        return this.pageId;
    }

    /**
     * Optional ID of the secondary locale you are translating into (24-character lowercase hexadecimal string), sent verbatim as ?translatable=&lt;localeId&gt; to return the page&#39;s translatable content for that locale. Webflow returns a 400 error when this is the primary locale ID or any other value, and a 403 error when translation exclusions are not enabled for the site.
     * 
     */
    @Import(name="translatable")
    private @Nullable String translatable;

    /**
     * @return Optional ID of the secondary locale you are translating into (24-character lowercase hexadecimal string), sent verbatim as ?translatable=&lt;localeId&gt; to return the page&#39;s translatable content for that locale. Webflow returns a 400 error when this is the primary locale ID or any other value, and a 403 error when translation exclusions are not enabled for the site.
     * 
     */
    public Optional<String> translatable() {
        return Optional.ofNullable(this.translatable);
    }

    private GetPagePlainArgs() {}

    private GetPagePlainArgs(GetPagePlainArgs $) {
        this.localeId = $.localeId;
        this.pageId = $.pageId;
        this.translatable = $.translatable;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPagePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPagePlainArgs $;

        public Builder() {
            $ = new GetPagePlainArgs();
        }

        public Builder(GetPagePlainArgs defaults) {
            $ = new GetPagePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param localeId Optional locale ID. When omitted the primary locale is returned.
         * 
         * @return builder
         * 
         */
        public Builder localeId(@Nullable String localeId) {
            $.localeId = localeId;
            return this;
        }

        /**
         * @param pageId The Webflow page ID (24-character lowercase hexadecimal string).
         * 
         * @return builder
         * 
         */
        public Builder pageId(String pageId) {
            $.pageId = pageId;
            return this;
        }

        /**
         * @param translatable Optional ID of the secondary locale you are translating into (24-character lowercase hexadecimal string), sent verbatim as ?translatable=&lt;localeId&gt; to return the page&#39;s translatable content for that locale. Webflow returns a 400 error when this is the primary locale ID or any other value, and a 403 error when translation exclusions are not enabled for the site.
         * 
         * @return builder
         * 
         */
        public Builder translatable(@Nullable String translatable) {
            $.translatable = translatable;
            return this;
        }

        public GetPagePlainArgs build() {
            if ($.pageId == null) {
                throw new MissingRequiredPropertyException("GetPagePlainArgs", "pageId");
            }
            return $;
        }
    }

}
