// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPageArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetPageArgs Empty = new GetPageArgs();

    /**
     * Optional locale ID. When omitted the primary locale is returned.
     * 
     */
    @Import(name="localeId")
    private @Nullable Output<String> localeId;

    /**
     * @return Optional locale ID. When omitted the primary locale is returned.
     * 
     */
    public Optional<Output<String>> localeId() {
        return Optional.ofNullable(this.localeId);
    }

    /**
     * The Webflow page ID (24-character lowercase hexadecimal string).
     * 
     */
    @Import(name="pageId", required=true)
    private Output<String> pageId;

    /**
     * @return The Webflow page ID (24-character lowercase hexadecimal string).
     * 
     */
    public Output<String> pageId() {
        return this.pageId;
    }

    /**
     * Optional ID of the secondary locale you are translating into (24-character lowercase hexadecimal string), sent verbatim as ?translatable=&lt;localeId&gt; to return the page&#39;s translatable content for that locale. Webflow returns a 400 error when this is the primary locale ID or any other value, and a 403 error when translation exclusions are not enabled for the site.
     * 
     */
    @Import(name="translatable")
    private @Nullable Output<String> translatable;

    /**
     * @return Optional ID of the secondary locale you are translating into (24-character lowercase hexadecimal string), sent verbatim as ?translatable=&lt;localeId&gt; to return the page&#39;s translatable content for that locale. Webflow returns a 400 error when this is the primary locale ID or any other value, and a 403 error when translation exclusions are not enabled for the site.
     * 
     */
    public Optional<Output<String>> translatable() {
        return Optional.ofNullable(this.translatable);
    }

    private GetPageArgs() {}

    private GetPageArgs(GetPageArgs $) {
        this.localeId = $.localeId;
        this.pageId = $.pageId;
        this.translatable = $.translatable;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPageArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPageArgs $;

        public Builder() {
            $ = new GetPageArgs();
        }

        public Builder(GetPageArgs defaults) {
            $ = new GetPageArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param localeId Optional locale ID. When omitted the primary locale is returned.
         * 
         * @return builder
         * 
         */
        public Builder localeId(@Nullable Output<String> localeId) {
            $.localeId = localeId;
            return this;
        }

        /**
         * @param localeId Optional locale ID. When omitted the primary locale is returned.
         * 
         * @return builder
         * 
         */
        public Builder localeId(String localeId) {
            return localeId(Output.of(localeId));
        }

        /**
         * @param pageId The Webflow page ID (24-character lowercase hexadecimal string).
         * 
         * @return builder
         * 
         */
        public Builder pageId(Output<String> pageId) {
            $.pageId = pageId;
            return this;
        }

        /**
         * @param pageId The Webflow page ID (24-character lowercase hexadecimal string).
         * 
         * @return builder
         * 
         */
        public Builder pageId(String pageId) {
            return pageId(Output.of(pageId));
        }

        /**
         * @param translatable Optional ID of the secondary locale you are translating into (24-character lowercase hexadecimal string), sent verbatim as ?translatable=&lt;localeId&gt; to return the page&#39;s translatable content for that locale. Webflow returns a 400 error when this is the primary locale ID or any other value, and a 403 error when translation exclusions are not enabled for the site.
         * 
         * @return builder
         * 
         */
        public Builder translatable(@Nullable Output<String> translatable) {
            $.translatable = translatable;
            return this;
        }

        /**
         * @param translatable Optional ID of the secondary locale you are translating into (24-character lowercase hexadecimal string), sent verbatim as ?translatable=&lt;localeId&gt; to return the page&#39;s translatable content for that locale. Webflow returns a 400 error when this is the primary locale ID or any other value, and a 403 error when translation exclusions are not enabled for the site.
         * 
         * @return builder
         * 
         */
        public Builder translatable(String translatable) {
            return translatable(Output.of(translatable));
        }

        public GetPageArgs build() {
            if ($.pageId == null) {
                throw new MissingRequiredPropertyException("GetPageArgs", "pageId");
            }
            return $;
        }
    }

}
