// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPageSchemaMarkupArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetPageSchemaMarkupArgs Empty = new GetPageSchemaMarkupArgs();

    /**
     * Optional secondary locale ID (24-character lowercase hexadecimal string). Omit to read the primary locale&#39;s markup.
     * 
     */
    @Import(name="localeId")
    private @Nullable Output<String> localeId;

    /**
     * @return Optional secondary locale ID (24-character lowercase hexadecimal string). Omit to read the primary locale&#39;s markup.
     * 
     */
    public Optional<Output<String>> localeId() {
        return Optional.ofNullable(this.localeId);
    }

    /**
     * The Webflow page ID (24-character lowercase hexadecimal string, e.g., &#39;6596da6045e56dee495bcbba&#39;).
     * 
     */
    @Import(name="pageId", required=true)
    private Output<String> pageId;

    /**
     * @return The Webflow page ID (24-character lowercase hexadecimal string, e.g., &#39;6596da6045e56dee495bcbba&#39;).
     * 
     */
    public Output<String> pageId() {
        return this.pageId;
    }

    private GetPageSchemaMarkupArgs() {}

    private GetPageSchemaMarkupArgs(GetPageSchemaMarkupArgs $) {
        this.localeId = $.localeId;
        this.pageId = $.pageId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPageSchemaMarkupArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPageSchemaMarkupArgs $;

        public Builder() {
            $ = new GetPageSchemaMarkupArgs();
        }

        public Builder(GetPageSchemaMarkupArgs defaults) {
            $ = new GetPageSchemaMarkupArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param localeId Optional secondary locale ID (24-character lowercase hexadecimal string). Omit to read the primary locale&#39;s markup.
         * 
         * @return builder
         * 
         */
        public Builder localeId(@Nullable Output<String> localeId) {
            $.localeId = localeId;
            return this;
        }

        /**
         * @param localeId Optional secondary locale ID (24-character lowercase hexadecimal string). Omit to read the primary locale&#39;s markup.
         * 
         * @return builder
         * 
         */
        public Builder localeId(String localeId) {
            return localeId(Output.of(localeId));
        }

        /**
         * @param pageId The Webflow page ID (24-character lowercase hexadecimal string, e.g., &#39;6596da6045e56dee495bcbba&#39;).
         * 
         * @return builder
         * 
         */
        public Builder pageId(Output<String> pageId) {
            $.pageId = pageId;
            return this;
        }

        /**
         * @param pageId The Webflow page ID (24-character lowercase hexadecimal string, e.g., &#39;6596da6045e56dee495bcbba&#39;).
         * 
         * @return builder
         * 
         */
        public Builder pageId(String pageId) {
            return pageId(Output.of(pageId));
        }

        public GetPageSchemaMarkupArgs build() {
            if ($.pageId == null) {
                throw new MissingRequiredPropertyException("GetPageSchemaMarkupArgs", "pageId");
            }
            return $;
        }
    }

}
