// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow.Inputs
{

    public sealed class AnalyticsTimeOnPageTimeseriesArgsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// IANA time zone used to align bucket boundaries (e.g., 'UTC', 'America/New_York').
        /// </summary>
        [Input("bucketTimeZone", required: true)]
        public Input<string> BucketTimeZone { get; set; } = null!;

        /// <summary>
        /// Size of each bucket: 'day' or 'week'.
        /// </summary>
        [Input("granularityPeriod", required: true)]
        public Input<string> GranularityPeriod { get; set; } = null!;

        public AnalyticsTimeOnPageTimeseriesArgsArgs()
        {
        }
        public static new AnalyticsTimeOnPageTimeseriesArgsArgs Empty => new AnalyticsTimeOnPageTimeseriesArgsArgs();
    }
}
