# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetAnalyticsTrafficResult',
    'AwaitableGetAnalyticsTrafficResult',
    'get_analytics_traffic',
    'get_analytics_traffic_output',
]

@pulumi.output_type
class GetAnalyticsTrafficResult:
    def __init__(__self__, bucketing=None, data=None, filters=None, metric_scope=None, report=None, window=None):
        if bucketing and not isinstance(bucketing, dict):
            raise TypeError("Expected argument 'bucketing' to be a dict")
        pulumi.set(__self__, "bucketing", bucketing)
        if data and not isinstance(data, list):
            raise TypeError("Expected argument 'data' to be a list")
        pulumi.set(__self__, "data", data)
        if filters and not isinstance(filters, dict):
            raise TypeError("Expected argument 'filters' to be a dict")
        pulumi.set(__self__, "filters", filters)
        if metric_scope and not isinstance(metric_scope, str):
            raise TypeError("Expected argument 'metric_scope' to be a str")
        pulumi.set(__self__, "metric_scope", metric_scope)
        if report and not isinstance(report, str):
            raise TypeError("Expected argument 'report' to be a str")
        pulumi.set(__self__, "report", report)
        if window and not isinstance(window, dict):
            raise TypeError("Expected argument 'window' to be a dict")
        pulumi.set(__self__, "window", window)

    @_builtins.property
    @pulumi.getter
    def bucketing(self) -> Optional['outputs.AnalyticsBucketing']:
        """
        The bucketing applied to the time series (daily, in the requested time zone).
        """
        return pulumi.get(self, "bucketing")

    @_builtins.property
    @pulumi.getter
    def data(self) -> Sequence['outputs.AnalyticsCountPoint']:
        """
        One data point per day, ordered by timestamp.
        """
        return pulumi.get(self, "data")

    @_builtins.property
    @pulumi.getter
    def filters(self) -> Optional[Mapping[str, 'outputs.AnalyticsDimensionFilter']]:
        """
        The filters that were applied, keyed by dimension.
        """
        return pulumi.get(self, "filters")

    @_builtins.property
    @pulumi.getter(name="metricScope")
    def metric_scope(self) -> _builtins.str:
        """
        The unit each count is measured in: 'session', 'user' or 'pageview'.
        """
        return pulumi.get(self, "metric_scope")

    @_builtins.property
    @pulumi.getter
    def report(self) -> _builtins.str:
        """
        The report name, always 'traffic'.
        """
        return pulumi.get(self, "report")

    @_builtins.property
    @pulumi.getter
    def window(self) -> 'outputs.AnalyticsWindow':
        """
        The reporting window that was applied.
        """
        return pulumi.get(self, "window")


class AwaitableGetAnalyticsTrafficResult(GetAnalyticsTrafficResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAnalyticsTrafficResult(
            bucketing=self.bucketing,
            data=self.data,
            filters=self.filters,
            metric_scope=self.metric_scope,
            report=self.report,
            window=self.window)


def get_analytics_traffic(browser: Optional[_builtins.str] = None,
                          bucket_time_zone: Optional[_builtins.str] = None,
                          country: Optional[_builtins.str] = None,
                          device_type: Optional[_builtins.str] = None,
                          end_time: Optional[_builtins.str] = None,
                          filters: Optional[Mapping[str, Union['AnalyticsDimensionFilter', 'AnalyticsDimensionFilterDict']]] = None,
                          metric_scope: Optional[_builtins.str] = None,
                          page_path: Optional[_builtins.str] = None,
                          referrer: Optional[_builtins.str] = None,
                          site_id: Optional[_builtins.str] = None,
                          start_time: Optional[_builtins.str] = None,
                          traffic_source: Optional[_builtins.str] = None,
                          utm_campaign: Optional[_builtins.str] = None,
                          utm_medium: Optional[_builtins.str] = None,
                          utm_source: Optional[_builtins.str] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAnalyticsTrafficResult:
    """
    Returns a daily time series of sessions, users or pageviews for a Webflow site over a chosen window, optionally filtered by device, country, page, traffic source, referrer, browser or UTM parameters (Analyze API, beta). Requires the 'sites:read' scope and a Webflow workspace with the Analyze add-on. Webflow allows one Analyze request in flight per access token; concurrent requests are retried. The reporting window must start on or after 2025-04-09 and span at most 100 days.

    :param _builtins.str browser: Restrict the report to a single browser name (e.g., 'Chrome').
    :param _builtins.str bucket_time_zone: IANA time zone used to align daily bucket boundaries (e.g., 'UTC', 'America/New_York').
    :param _builtins.str country: Restrict the report to a single country, as an ISO 3166-1 alpha-2 code (e.g., 'US'). Normalized to uppercase.
    :param _builtins.str device_type: Restrict the report to a single device type: 'desktop', 'mobile' or 'tablet'.
    :param _builtins.str end_time: Exclusive end of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be after startTime and within 100 days of it.
    :param Mapping[str, Union['AnalyticsDimensionFilter', 'AnalyticsDimensionFilterDict']] filters: Advanced filters keyed by dimension (e.g., 'country', 'deviceType', 'pagePath', 'referrer', 'trafficSource', 'utmCampaign', 'os', 'language', 'locale', 'region', 'audienceIds', 'collectionId', 'itemSlug', 'pageId', 'dayOfWeek', 'timeOfDay', 'visitStatus', ...). Each entry supports 'eq', 'in', 'ne' and 'nin'. Filter a given dimension either here or with the matching single-value input, not both.
    :param _builtins.str metric_scope: Unit of each data point: 'session' (sessions), 'user' (unique users) or 'pageview'.
    :param _builtins.str page_path: Restrict the report to a single page path (e.g., '/pricing').
    :param _builtins.str referrer: Restrict the report to a single referrer domain (e.g., 'google.com').
    :param _builtins.str site_id: The Webflow site ID (24-character lowercase hexadecimal string).
    :param _builtins.str start_time: Inclusive start of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be on or after 2025-04-09T00:00:00Z.
    :param _builtins.str traffic_source: Restrict the report to a single traffic source code (e.g., 'SO' for Organic Search).
    :param _builtins.str utm_campaign: Restrict the report to a single utm_campaign value.
    :param _builtins.str utm_medium: Restrict the report to a single utm_medium value.
    :param _builtins.str utm_source: Restrict the report to a single utm_source value.
    """
    __args__ = dict()
    __args__['browser'] = browser
    __args__['bucketTimeZone'] = bucket_time_zone
    __args__['country'] = country
    __args__['deviceType'] = device_type
    __args__['endTime'] = end_time
    __args__['filters'] = filters
    __args__['metricScope'] = metric_scope
    __args__['pagePath'] = page_path
    __args__['referrer'] = referrer
    __args__['siteId'] = site_id
    __args__['startTime'] = start_time
    __args__['trafficSource'] = traffic_source
    __args__['utmCampaign'] = utm_campaign
    __args__['utmMedium'] = utm_medium
    __args__['utmSource'] = utm_source
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('webflow:index:getAnalyticsTraffic', __args__, opts=opts, typ=GetAnalyticsTrafficResult).value

    return AwaitableGetAnalyticsTrafficResult(
        bucketing=pulumi.get(__ret__, 'bucketing'),
        data=pulumi.get(__ret__, 'data'),
        filters=pulumi.get(__ret__, 'filters'),
        metric_scope=pulumi.get(__ret__, 'metric_scope'),
        report=pulumi.get(__ret__, 'report'),
        window=pulumi.get(__ret__, 'window'))
def get_analytics_traffic_output(browser: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                 bucket_time_zone: pulumi.Input[Optional[_builtins.str]] = None,
                                 country: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                 device_type: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                 end_time: pulumi.Input[Optional[_builtins.str]] = None,
                                 filters: pulumi.Input[Optional[Optional[Mapping[str, Union['AnalyticsDimensionFilter', 'AnalyticsDimensionFilterDict']]]]] = None,
                                 metric_scope: pulumi.Input[Optional[_builtins.str]] = None,
                                 page_path: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                 referrer: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                 site_id: pulumi.Input[Optional[_builtins.str]] = None,
                                 start_time: pulumi.Input[Optional[_builtins.str]] = None,
                                 traffic_source: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                 utm_campaign: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                 utm_medium: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                 utm_source: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                                 opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAnalyticsTrafficResult]:
    """
    Returns a daily time series of sessions, users or pageviews for a Webflow site over a chosen window, optionally filtered by device, country, page, traffic source, referrer, browser or UTM parameters (Analyze API, beta). Requires the 'sites:read' scope and a Webflow workspace with the Analyze add-on. Webflow allows one Analyze request in flight per access token; concurrent requests are retried. The reporting window must start on or after 2025-04-09 and span at most 100 days.

    :param _builtins.str browser: Restrict the report to a single browser name (e.g., 'Chrome').
    :param _builtins.str bucket_time_zone: IANA time zone used to align daily bucket boundaries (e.g., 'UTC', 'America/New_York').
    :param _builtins.str country: Restrict the report to a single country, as an ISO 3166-1 alpha-2 code (e.g., 'US'). Normalized to uppercase.
    :param _builtins.str device_type: Restrict the report to a single device type: 'desktop', 'mobile' or 'tablet'.
    :param _builtins.str end_time: Exclusive end of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be after startTime and within 100 days of it.
    :param Mapping[str, Union['AnalyticsDimensionFilter', 'AnalyticsDimensionFilterDict']] filters: Advanced filters keyed by dimension (e.g., 'country', 'deviceType', 'pagePath', 'referrer', 'trafficSource', 'utmCampaign', 'os', 'language', 'locale', 'region', 'audienceIds', 'collectionId', 'itemSlug', 'pageId', 'dayOfWeek', 'timeOfDay', 'visitStatus', ...). Each entry supports 'eq', 'in', 'ne' and 'nin'. Filter a given dimension either here or with the matching single-value input, not both.
    :param _builtins.str metric_scope: Unit of each data point: 'session' (sessions), 'user' (unique users) or 'pageview'.
    :param _builtins.str page_path: Restrict the report to a single page path (e.g., '/pricing').
    :param _builtins.str referrer: Restrict the report to a single referrer domain (e.g., 'google.com').
    :param _builtins.str site_id: The Webflow site ID (24-character lowercase hexadecimal string).
    :param _builtins.str start_time: Inclusive start of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be on or after 2025-04-09T00:00:00Z.
    :param _builtins.str traffic_source: Restrict the report to a single traffic source code (e.g., 'SO' for Organic Search).
    :param _builtins.str utm_campaign: Restrict the report to a single utm_campaign value.
    :param _builtins.str utm_medium: Restrict the report to a single utm_medium value.
    :param _builtins.str utm_source: Restrict the report to a single utm_source value.
    """
    __args__ = dict()
    __args__['browser'] = browser
    __args__['bucketTimeZone'] = bucket_time_zone
    __args__['country'] = country
    __args__['deviceType'] = device_type
    __args__['endTime'] = end_time
    __args__['filters'] = filters
    __args__['metricScope'] = metric_scope
    __args__['pagePath'] = page_path
    __args__['referrer'] = referrer
    __args__['siteId'] = site_id
    __args__['startTime'] = start_time
    __args__['trafficSource'] = traffic_source
    __args__['utmCampaign'] = utm_campaign
    __args__['utmMedium'] = utm_medium
    __args__['utmSource'] = utm_source
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('webflow:index:getAnalyticsTraffic', __args__, opts=opts, typ=GetAnalyticsTrafficResult)
    return __ret__.apply(lambda __response__: GetAnalyticsTrafficResult(
        bucketing=pulumi.get(__response__, 'bucketing'),
        data=pulumi.get(__response__, 'data'),
        filters=pulumi.get(__response__, 'filters'),
        metric_scope=pulumi.get(__response__, 'metric_scope'),
        report=pulumi.get(__response__, 'report'),
        window=pulumi.get(__response__, 'window')))
