# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SiteArgs', 'Site']

@pulumi.input_type
class SiteArgs:
    def __init__(__self__, *,
                 display_name: pulumi.Input[_builtins.str],
                 workspace_id: pulumi.Input[_builtins.str],
                 parent_folder_id: pulumi.Input[Optional[_builtins.str]] = None,
                 publish: pulumi.Input[Optional[_builtins.bool]] = None,
                 publish_custom_domains: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 publish_page_id: pulumi.Input[Optional[_builtins.str]] = None,
                 publish_to_webflow_subdomain: pulumi.Input[Optional[_builtins.bool]] = None,
                 template_name: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Site resource.

        :param pulumi.Input[_builtins.str] display_name: The human-readable name of the site as shown in the Webflow dashboard. Required - must be a non-empty string. Examples: 'My Marketing Site', 'Company Blog', 'Product Landing Page'. This is the name users will see when managing the site.
        :param pulumi.Input[_builtins.str] workspace_id: The Webflow workspace ID where the site will be created (24-character lowercase hexadecimal string). Required for site creation (Enterprise workspace and the `workspace:write` scope are required by the Webflow API). Example: '5f0c8c9e1c9d440000e8d8c3'. You can find your workspace ID in the Webflow dashboard under Account Settings > Workspace. Changing this value replaces the site.
        :param pulumi.Input[_builtins.str] parent_folder_id: The folder ID where the site will be organized in the Webflow dashboard (24-character lowercase hexadecimal string). Optional - the site will be placed at the workspace root if not specified. Removing this property from your program moves the site back to the workspace root. This is useful for organizing multiple sites into logical groups within your workspace.
        :param pulumi.Input[_builtins.bool] publish: Automatically publish the site after creation or updates. When set to true, the provider calls the Webflow publish endpoint after successfully creating or updating the site, using `publishToWebflowSubdomain`, `publishCustomDomains` and `publishPageId` to build the publish request. If neither `publishToWebflowSubdomain` nor `publishCustomDomains` is set, the site is published to its webflow.io subdomain. Default: false (manual publishing required). If publishing fails, the operation fails with an error (the site may exist but Pulumi will report failure).
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] publish_custom_domains: When `publish` is true, the list of custom domain IDs (not host names) to publish to. Maps to the `customDomains` field of the Webflow publish endpoint. Custom domain IDs can be read from the Webflow site settings or the sites API.
        :param pulumi.Input[_builtins.str] publish_page_id: When `publish` is true, publish only the page with this ID (24-character lowercase hexadecimal string) instead of the whole site. Maps to the `pageId` field of the Webflow publish endpoint.
        :param pulumi.Input[_builtins.bool] publish_to_webflow_subdomain: When `publish` is true, publish to the site's default webflow.io subdomain. Maps to the `publishToWebflowSubdomain` field of the Webflow publish endpoint. Default: false.
        :param pulumi.Input[_builtins.str] template_name: The template to use for site creation. Optional - if not specified, Webflow will create a blank site. **This value only affects creation.** The Webflow API does not report which template a site was created from, so it cannot be read back: after `pulumi import` the state holds no templateName, and adding one to the program later does not change or replace the site. **WARNING:** changing from one non-empty template to a different non-empty template triggers a REPLACE operation, which will: (1) DELETE your existing site and ALL its content (pages, CMS items, assets, etc.), (2) CREATE a new site with the new template, (3) REPLACE all dependent resources (redirects, robots.txt, etc.). This is a DESTRUCTIVE operation that cannot be undone. Use any valid Webflow template identifier (e.g., 'mast-framework', 'blank'). Consider using resource protection (`protect: true`) to prevent accidental replacement.
        """
        pulumi.set(__self__, "display_name", display_name)
        pulumi.set(__self__, "workspace_id", workspace_id)
        if parent_folder_id is not None:
            pulumi.set(__self__, "parent_folder_id", parent_folder_id)
        if publish is not None:
            pulumi.set(__self__, "publish", publish)
        if publish_custom_domains is not None:
            pulumi.set(__self__, "publish_custom_domains", publish_custom_domains)
        if publish_page_id is not None:
            pulumi.set(__self__, "publish_page_id", publish_page_id)
        if publish_to_webflow_subdomain is not None:
            pulumi.set(__self__, "publish_to_webflow_subdomain", publish_to_webflow_subdomain)
        if template_name is not None:
            pulumi.set(__self__, "template_name", template_name)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[_builtins.str]:
        """
        The human-readable name of the site as shown in the Webflow dashboard. Required - must be a non-empty string. Examples: 'My Marketing Site', 'Company Blog', 'Product Landing Page'. This is the name users will see when managing the site.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> pulumi.Input[_builtins.str]:
        """
        The Webflow workspace ID where the site will be created (24-character lowercase hexadecimal string). Required for site creation (Enterprise workspace and the `workspace:write` scope are required by the Webflow API). Example: '5f0c8c9e1c9d440000e8d8c3'. You can find your workspace ID in the Webflow dashboard under Account Settings > Workspace. Changing this value replaces the site.
        """
        return pulumi.get(self, "workspace_id")

    @workspace_id.setter
    def workspace_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "workspace_id", value)

    @_builtins.property
    @pulumi.getter(name="parentFolderId")
    def parent_folder_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The folder ID where the site will be organized in the Webflow dashboard (24-character lowercase hexadecimal string). Optional - the site will be placed at the workspace root if not specified. Removing this property from your program moves the site back to the workspace root. This is useful for organizing multiple sites into logical groups within your workspace.
        """
        return pulumi.get(self, "parent_folder_id")

    @parent_folder_id.setter
    def parent_folder_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "parent_folder_id", value)

    @_builtins.property
    @pulumi.getter
    def publish(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Automatically publish the site after creation or updates. When set to true, the provider calls the Webflow publish endpoint after successfully creating or updating the site, using `publishToWebflowSubdomain`, `publishCustomDomains` and `publishPageId` to build the publish request. If neither `publishToWebflowSubdomain` nor `publishCustomDomains` is set, the site is published to its webflow.io subdomain. Default: false (manual publishing required). If publishing fails, the operation fails with an error (the site may exist but Pulumi will report failure).
        """
        return pulumi.get(self, "publish")

    @publish.setter
    def publish(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "publish", value)

    @_builtins.property
    @pulumi.getter(name="publishCustomDomains")
    def publish_custom_domains(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        When `publish` is true, the list of custom domain IDs (not host names) to publish to. Maps to the `customDomains` field of the Webflow publish endpoint. Custom domain IDs can be read from the Webflow site settings or the sites API.
        """
        return pulumi.get(self, "publish_custom_domains")

    @publish_custom_domains.setter
    def publish_custom_domains(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "publish_custom_domains", value)

    @_builtins.property
    @pulumi.getter(name="publishPageId")
    def publish_page_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        When `publish` is true, publish only the page with this ID (24-character lowercase hexadecimal string) instead of the whole site. Maps to the `pageId` field of the Webflow publish endpoint.
        """
        return pulumi.get(self, "publish_page_id")

    @publish_page_id.setter
    def publish_page_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "publish_page_id", value)

    @_builtins.property
    @pulumi.getter(name="publishToWebflowSubdomain")
    def publish_to_webflow_subdomain(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        When `publish` is true, publish to the site's default webflow.io subdomain. Maps to the `publishToWebflowSubdomain` field of the Webflow publish endpoint. Default: false.
        """
        return pulumi.get(self, "publish_to_webflow_subdomain")

    @publish_to_webflow_subdomain.setter
    def publish_to_webflow_subdomain(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "publish_to_webflow_subdomain", value)

    @_builtins.property
    @pulumi.getter(name="templateName")
    def template_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The template to use for site creation. Optional - if not specified, Webflow will create a blank site. **This value only affects creation.** The Webflow API does not report which template a site was created from, so it cannot be read back: after `pulumi import` the state holds no templateName, and adding one to the program later does not change or replace the site. **WARNING:** changing from one non-empty template to a different non-empty template triggers a REPLACE operation, which will: (1) DELETE your existing site and ALL its content (pages, CMS items, assets, etc.), (2) CREATE a new site with the new template, (3) REPLACE all dependent resources (redirects, robots.txt, etc.). This is a DESTRUCTIVE operation that cannot be undone. Use any valid Webflow template identifier (e.g., 'mast-framework', 'blank'). Consider using resource protection (`protect: true`) to prevent accidental replacement.
        """
        return pulumi.get(self, "template_name")

    @template_name.setter
    def template_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "template_name", value)


@pulumi.type_token("webflow:index:Site")
class Site(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 parent_folder_id: pulumi.Input[Optional[_builtins.str]] = None,
                 publish: pulumi.Input[Optional[_builtins.bool]] = None,
                 publish_custom_domains: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 publish_page_id: pulumi.Input[Optional[_builtins.str]] = None,
                 publish_to_webflow_subdomain: pulumi.Input[Optional[_builtins.bool]] = None,
                 template_name: pulumi.Input[Optional[_builtins.str]] = None,
                 workspace_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Manages Webflow sites programmatically. This resource allows you to create, configure, and manage Webflow sites through infrastructure code. Create, Read, Update, and Delete operations are fully supported for complete site lifecycle management.

        **Required scopes:** creating a site (POST /v2/workspaces/{workspace_id}/sites) requires the `workspace:write` scope and an Enterprise workspace; reading a site requires `sites:read`; updating, publishing and deleting a site require `sites:write`.

        **Import:** `pulumi import webflow:index:Site my-site <siteId>`. The Webflow API does not report the template a site was created from, so `templateName` is empty after import and only affects creation; it is compared only when both the program and the state hold a value.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] display_name: The human-readable name of the site as shown in the Webflow dashboard. Required - must be a non-empty string. Examples: 'My Marketing Site', 'Company Blog', 'Product Landing Page'. This is the name users will see when managing the site.
        :param pulumi.Input[_builtins.str] parent_folder_id: The folder ID where the site will be organized in the Webflow dashboard (24-character lowercase hexadecimal string). Optional - the site will be placed at the workspace root if not specified. Removing this property from your program moves the site back to the workspace root. This is useful for organizing multiple sites into logical groups within your workspace.
        :param pulumi.Input[_builtins.bool] publish: Automatically publish the site after creation or updates. When set to true, the provider calls the Webflow publish endpoint after successfully creating or updating the site, using `publishToWebflowSubdomain`, `publishCustomDomains` and `publishPageId` to build the publish request. If neither `publishToWebflowSubdomain` nor `publishCustomDomains` is set, the site is published to its webflow.io subdomain. Default: false (manual publishing required). If publishing fails, the operation fails with an error (the site may exist but Pulumi will report failure).
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] publish_custom_domains: When `publish` is true, the list of custom domain IDs (not host names) to publish to. Maps to the `customDomains` field of the Webflow publish endpoint. Custom domain IDs can be read from the Webflow site settings or the sites API.
        :param pulumi.Input[_builtins.str] publish_page_id: When `publish` is true, publish only the page with this ID (24-character lowercase hexadecimal string) instead of the whole site. Maps to the `pageId` field of the Webflow publish endpoint.
        :param pulumi.Input[_builtins.bool] publish_to_webflow_subdomain: When `publish` is true, publish to the site's default webflow.io subdomain. Maps to the `publishToWebflowSubdomain` field of the Webflow publish endpoint. Default: false.
        :param pulumi.Input[_builtins.str] template_name: The template to use for site creation. Optional - if not specified, Webflow will create a blank site. **This value only affects creation.** The Webflow API does not report which template a site was created from, so it cannot be read back: after `pulumi import` the state holds no templateName, and adding one to the program later does not change or replace the site. **WARNING:** changing from one non-empty template to a different non-empty template triggers a REPLACE operation, which will: (1) DELETE your existing site and ALL its content (pages, CMS items, assets, etc.), (2) CREATE a new site with the new template, (3) REPLACE all dependent resources (redirects, robots.txt, etc.). This is a DESTRUCTIVE operation that cannot be undone. Use any valid Webflow template identifier (e.g., 'mast-framework', 'blank'). Consider using resource protection (`protect: true`) to prevent accidental replacement.
        :param pulumi.Input[_builtins.str] workspace_id: The Webflow workspace ID where the site will be created (24-character lowercase hexadecimal string). Required for site creation (Enterprise workspace and the `workspace:write` scope are required by the Webflow API). Example: '5f0c8c9e1c9d440000e8d8c3'. You can find your workspace ID in the Webflow dashboard under Account Settings > Workspace. Changing this value replaces the site.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SiteArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages Webflow sites programmatically. This resource allows you to create, configure, and manage Webflow sites through infrastructure code. Create, Read, Update, and Delete operations are fully supported for complete site lifecycle management.

        **Required scopes:** creating a site (POST /v2/workspaces/{workspace_id}/sites) requires the `workspace:write` scope and an Enterprise workspace; reading a site requires `sites:read`; updating, publishing and deleting a site require `sites:write`.

        **Import:** `pulumi import webflow:index:Site my-site <siteId>`. The Webflow API does not report the template a site was created from, so `templateName` is empty after import and only affects creation; it is compared only when both the program and the state hold a value.

        :param str resource_name: The name of the resource.
        :param SiteArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SiteArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 parent_folder_id: pulumi.Input[Optional[_builtins.str]] = None,
                 publish: pulumi.Input[Optional[_builtins.bool]] = None,
                 publish_custom_domains: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 publish_page_id: pulumi.Input[Optional[_builtins.str]] = None,
                 publish_to_webflow_subdomain: pulumi.Input[Optional[_builtins.bool]] = None,
                 template_name: pulumi.Input[Optional[_builtins.str]] = None,
                 workspace_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SiteArgs.__new__(SiteArgs)

            if display_name is None and not opts.urn:
                raise TypeError("Missing required property 'display_name'")
            __props__.__dict__["display_name"] = display_name
            __props__.__dict__["parent_folder_id"] = parent_folder_id
            __props__.__dict__["publish"] = publish
            __props__.__dict__["publish_custom_domains"] = publish_custom_domains
            __props__.__dict__["publish_page_id"] = publish_page_id
            __props__.__dict__["publish_to_webflow_subdomain"] = publish_to_webflow_subdomain
            __props__.__dict__["template_name"] = template_name
            if workspace_id is None and not opts.urn:
                raise TypeError("Missing required property 'workspace_id'")
            __props__.__dict__["workspace_id"] = workspace_id
            __props__.__dict__["custom_domains"] = None
            __props__.__dict__["data_collection_enabled"] = None
            __props__.__dict__["data_collection_type"] = None
            __props__.__dict__["last_published"] = None
            __props__.__dict__["last_updated"] = None
            __props__.__dict__["preview_url"] = None
            __props__.__dict__["publish_scope"] = None
            __props__.__dict__["short_name"] = None
            __props__.__dict__["time_zone"] = None
        super(Site, __self__).__init__(
            'webflow:index:Site',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Site':
        """
        Get an existing Site resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = SiteArgs.__new__(SiteArgs)

        __props__.__dict__["custom_domains"] = None
        __props__.__dict__["data_collection_enabled"] = None
        __props__.__dict__["data_collection_type"] = None
        __props__.__dict__["display_name"] = None
        __props__.__dict__["last_published"] = None
        __props__.__dict__["last_updated"] = None
        __props__.__dict__["parent_folder_id"] = None
        __props__.__dict__["preview_url"] = None
        __props__.__dict__["publish"] = None
        __props__.__dict__["publish_custom_domains"] = None
        __props__.__dict__["publish_page_id"] = None
        __props__.__dict__["publish_scope"] = None
        __props__.__dict__["publish_to_webflow_subdomain"] = None
        __props__.__dict__["short_name"] = None
        __props__.__dict__["template_name"] = None
        __props__.__dict__["time_zone"] = None
        __props__.__dict__["workspace_id"] = None
        return Site(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="customDomains")
    def custom_domains(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of custom domains attached to the site (read-only in this release). Custom domain management will be available in a future release.
        """
        return pulumi.get(self, "custom_domains")

    @_builtins.property
    @pulumi.getter(name="dataCollectionEnabled")
    def data_collection_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Indicates whether data collection is enabled for this site (read-only). Controlled by your Webflow workspace settings, not per-site.
        """
        return pulumi.get(self, "data_collection_enabled")

    @_builtins.property
    @pulumi.getter(name="dataCollectionType")
    def data_collection_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The type of data collection enabled for the site (read-only). Possible values: 'always' (always collect), 'optOut' (collect by default), 'disabled' (no collection). Controlled by your Webflow workspace settings, not per-site.
        """
        return pulumi.get(self, "data_collection_type")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Output[_builtins.str]:
        """
        The human-readable name of the site as shown in the Webflow dashboard. Required - must be a non-empty string. Examples: 'My Marketing Site', 'Company Blog', 'Product Landing Page'. This is the name users will see when managing the site.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter(name="lastPublished")
    def last_published(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The RFC3339 timestamp of the last time the site was published (read-only). Automatically set by Webflow when changes are published to production.
        """
        return pulumi.get(self, "last_published")

    @_builtins.property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The RFC3339 timestamp of the last time the site configuration was updated (read-only). Automatically set by Webflow when any site changes occur.
        """
        return pulumi.get(self, "last_updated")

    @_builtins.property
    @pulumi.getter(name="parentFolderId")
    def parent_folder_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The folder ID where the site will be organized in the Webflow dashboard (24-character lowercase hexadecimal string). Optional - the site will be placed at the workspace root if not specified. Removing this property from your program moves the site back to the workspace root. This is useful for organizing multiple sites into logical groups within your workspace.
        """
        return pulumi.get(self, "parent_folder_id")

    @_builtins.property
    @pulumi.getter(name="previewUrl")
    def preview_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The URL to a preview image of the site (read-only). Automatically generated by Webflow for site thumbnails in the dashboard.
        """
        return pulumi.get(self, "preview_url")

    @_builtins.property
    @pulumi.getter
    def publish(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Automatically publish the site after creation or updates. When set to true, the provider calls the Webflow publish endpoint after successfully creating or updating the site, using `publishToWebflowSubdomain`, `publishCustomDomains` and `publishPageId` to build the publish request. If neither `publishToWebflowSubdomain` nor `publishCustomDomains` is set, the site is published to its webflow.io subdomain. Default: false (manual publishing required). If publishing fails, the operation fails with an error (the site may exist but Pulumi will report failure).
        """
        return pulumi.get(self, "publish")

    @_builtins.property
    @pulumi.getter(name="publishCustomDomains")
    def publish_custom_domains(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        When `publish` is true, the list of custom domain IDs (not host names) to publish to. Maps to the `customDomains` field of the Webflow publish endpoint. Custom domain IDs can be read from the Webflow site settings or the sites API.
        """
        return pulumi.get(self, "publish_custom_domains")

    @_builtins.property
    @pulumi.getter(name="publishPageId")
    def publish_page_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        When `publish` is true, publish only the page with this ID (24-character lowercase hexadecimal string) instead of the whole site. Maps to the `pageId` field of the Webflow publish endpoint.
        """
        return pulumi.get(self, "publish_page_id")

    @_builtins.property
    @pulumi.getter(name="publishScope")
    def publish_scope(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Scope of the last publish triggered by this provider (read-only): 'site' when the whole site was published, 'page' when only `publishPageId` was published. Empty when the provider has not published the site.
        """
        return pulumi.get(self, "publish_scope")

    @_builtins.property
    @pulumi.getter(name="publishToWebflowSubdomain")
    def publish_to_webflow_subdomain(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        When `publish` is true, publish to the site's default webflow.io subdomain. Maps to the `publishToWebflowSubdomain` field of the Webflow publish endpoint. Default: false.
        """
        return pulumi.get(self, "publish_to_webflow_subdomain")

    @_builtins.property
    @pulumi.getter(name="shortName")
    def short_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The slugified version of the site name used in URLs (read-only). Auto-generated by Webflow from the displayName. Cannot be set via API. Examples: 'my-site', 'company-blog-2024', 'product-landing'.
        """
        return pulumi.get(self, "short_name")

    @_builtins.property
    @pulumi.getter(name="templateName")
    def template_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The template to use for site creation. Optional - if not specified, Webflow will create a blank site. **This value only affects creation.** The Webflow API does not report which template a site was created from, so it cannot be read back: after `pulumi import` the state holds no templateName, and adding one to the program later does not change or replace the site. **WARNING:** changing from one non-empty template to a different non-empty template triggers a REPLACE operation, which will: (1) DELETE your existing site and ALL its content (pages, CMS items, assets, etc.), (2) CREATE a new site with the new template, (3) REPLACE all dependent resources (redirects, robots.txt, etc.). This is a DESTRUCTIVE operation that cannot be undone. Use any valid Webflow template identifier (e.g., 'mast-framework', 'blank'). Consider using resource protection (`protect: true`) to prevent accidental replacement.
        """
        return pulumi.get(self, "template_name")

    @_builtins.property
    @pulumi.getter(name="timeZone")
    def time_zone(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The IANA timezone identifier for the site (read-only). This value is configured in Webflow Site Settings and cannot be changed via API. Examples: 'America/New_York', 'Europe/London', 'Asia/Tokyo', 'UTC'.
        """
        return pulumi.get(self, "time_zone")

    @_builtins.property
    @pulumi.getter(name="workspaceId")
    def workspace_id(self) -> pulumi.Output[_builtins.str]:
        """
        The Webflow workspace ID where the site will be created (24-character lowercase hexadecimal string). Required for site creation (Enterprise workspace and the `workspace:write` scope are required by the Webflow API). Example: '5f0c8c9e1c9d440000e8d8c3'. You can find your workspace ID in the Webflow dashboard under Account Settings > Workspace. Changing this value replaces the site.
        """
        return pulumi.get(self, "workspace_id")

