// Copyright 2025, Justin Detmar.
// SPDX-License-Identifier: MIT

import * as pulumi from "@pulumi/pulumi";
import * as webflow from "@jdetmar/pulumi-webflow";

// Load configuration from current stack
const config = new pulumi.Config();

// Stack-specific configuration (defined in Pulumi.<stack>.yaml)
const environmentName = config.require("environmentName");  // "dev", "staging", "prod"
const workspaceId = config.require("workspaceId");          // Enterprise workspace that owns the sites

// Validate environment configuration
const validEnvironments = ["dev", "staging", "prod"];
if (!validEnvironments.includes(environmentName)) {
    throw new Error(
        `Invalid environment "${environmentName}". ` +
        `Must be one of: ${validEnvironments.join(", ")}`
    );
}

// Production safety check: require explicit confirmation
const isProd = environmentName === "prod";
if (isProd) {
    const confirmation = config.get("prodDeploymentConfirmed");
    if (confirmation !== "yes") {
        throw new Error(
            "⚠️  Production deployment requires explicit confirmation.\n" +
            "Run: pulumi config set prodDeploymentConfirmed yes\n" +
            "This prevents accidental production deployments."
        );
    }
}

// Site configuration interface - each site is a distinct entity.
// shortName and timeZone are generated by Webflow and exposed as outputs, not inputs.
interface SiteConfig {
    displayName: string;
    allowIndexing: boolean;  // Whether search engines can index this site
    redirects?: Array<{
        sourcePath: string;
        destinationPath: string;
        statusCode: number;
    }>;
}

// Load site configurations from stack config
// Each environment defines its own sites with environment-specific settings
const sitesConfig = config.requireObject<Record<string, SiteConfig>>("sites");

pulumi.log.info(
    `🚀 Deploying ${Object.keys(sitesConfig).length} sites to ${environmentName} environment`
);

// Create each configured site
const siteExports: Record<string, pulumi.Output<string>> = {};

for (const [siteKey, siteConfig] of Object.entries(sitesConfig)) {
    // Create the site with its specific configuration
    const site = new webflow.Site(siteKey, {
        workspaceId: workspaceId,
        displayName: siteConfig.displayName,
    });

    siteExports[`${siteKey}-id`] = site.id;
    siteExports[`${siteKey}-short-name`] = site.shortName.apply((s) => s ?? "");

    // Configure robots.txt based on site's indexing preference
    const robotsContent = siteConfig.allowIndexing
        ? "User-agent: *\nAllow: /\n"
        : `User-agent: *\nDisallow: /\n\n# ${environmentName.toUpperCase()} - Do not index`;

    new webflow.RobotsTxt(`${siteKey}-robots`, {
        siteId: site.id,
        content: robotsContent,
    });

    // Create any configured redirects for this site
    if (siteConfig.redirects) {
        for (const redirect of siteConfig.redirects) {
            const redirectName = `${siteKey}-redirect${redirect.sourcePath.replace(/\//g, "-")}`;
            new webflow.Redirect(redirectName, {
                siteId: site.id,
                sourcePath: redirect.sourcePath,
                destinationPath: redirect.destinationPath,
                statusCode: redirect.statusCode,
            });
        }
    }

    pulumi.log.info(`✅ Configured site: ${siteKey} (${siteConfig.displayName})`);
}

// Export site IDs and generated short names for reference, keyed by site
// (stack outputs in TypeScript are top-level `export`s; there is no pulumi.export())
export const sites = siteExports;

// Export summary information
export const environment = environmentName;
export const siteCount = Object.keys(sitesConfig).length;
export const siteNames = Object.keys(sitesConfig);
export const stackName = pulumi.getStack();
export const projectName = pulumi.getProject();

pulumi.log.info(
    `✅ Deployment complete: ${Object.keys(sitesConfig).length} sites configured for ${environmentName}`
);
