// Copyright 2025, Justin Detmar.
// SPDX-License-Identifier: MIT

package main

import (
	"fmt"

	"github.com/JDetmar/pulumi-webflow/sdk/go/webflow"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		// Log initialization with detailed debug information
		// (DEBUG messages are only visible with `pulumi up -v=9 --logtostderr`)
		ctx.Log.Info("🔍 Initializing Webflow site creation with logging analysis", nil)
		ctx.Log.Debug("Context initialized for deployment analysis", nil)

		// Site creation requires an Enterprise workspace ID (pulumi config set workspaceId ...)
		cfg := config.New(ctx, "")
		workspaceID := cfg.Require("workspaceId")

		// Demonstrate structured logging for troubleshooting
		ctx.Log.Info("🏗️  Creating Webflow site resource", nil)
		ctx.Log.Debug("Resource type: webflow:index:Site", nil)

		// Create a site with logging at each phase.
		// ShortName and TimeZone are generated by Webflow and available as outputs.
		site, err := webflow.NewSite(ctx, "go-logging-analysis", &webflow.SiteArgs{
			WorkspaceId: pulumi.String(workspaceID),
			DisplayName: pulumi.String("Go Logging Analysis Example"),
		})
		if err != nil {
			ctx.Log.Error(fmt.Sprintf("❌ Failed to create site: %v", err), nil)
			return err
		}

		ctx.Log.Info("✅ Site resource created successfully", nil)

		// Log resource IDs and diagnostic information
		site.ID().ApplyT(func(id string) error {
			ctx.Log.Debug(fmt.Sprintf("Site ID: %s", id), nil)
			ctx.Log.Info(fmt.Sprintf("✅ Site provisioned: %s", id), nil)
			return nil
		})

		// Create robots.txt with logging
		ctx.Log.Info("🤖 Configuring robots.txt resource", nil)

		_, err = webflow.NewRobotsTxt(ctx, "go-robots", &webflow.RobotsTxtArgs{
			SiteId:  site.ID(),
			Content: pulumi.String("User-agent: *\nAllow: /\n"),
		})
		if err != nil {
			ctx.Log.Error(fmt.Sprintf("❌ Failed to create robots.txt: %v", err), nil)
			return err
		}

		ctx.Log.Info("✅ Robots.txt configured successfully", nil)

		// Export stack outputs
		ctx.Export("siteID", site.ID())
		ctx.Export("siteShortName", site.ShortName)
		ctx.Log.Info("📤 Stack outputs exported", nil)

		// Final log summary
		ctx.Log.Info("🎉 Webflow infrastructure provisioned successfully", nil)
		ctx.Log.Debug("Deployment complete - all resources created and configured", nil)

		return nil
	})
}
