"""Reusable site templates for Webflow multi-site management.

This module provides factory functions for creating standardized site
configurations that can be reused across your site fleet, ensuring
consistency and reducing configuration boilerplate.

Site creation requires an Enterprise workspace ID, read from the ``workspaceId``
project config key. ``short_name`` and ``time_zone`` are generated by Webflow
and exposed as outputs on the returned ``Site`` resources.
"""

import pulumi
import pulumi_webflow as webflow

_WORKSPACE_ID = pulumi.Config().require("workspaceId")


def create_campaign_site(name: str, display_name: str) -> webflow.Site:
    """Create a standardized campaign site with default configurations.

    Args:
        name: Unique identifier for the site (e.g., "q1-promo")
        display_name: Human-readable site name (e.g., "Q1 Promotion")

    Returns:
        Created Site resource
    """
    # Create site with campaign defaults
    site = webflow.Site(
        name,
        workspace_id=_WORKSPACE_ID,
        display_name=display_name,
    )

    # Standard robots.txt for campaigns (allow all)
    webflow.RobotsTxt(
        f"{name}-robots",
        site_id=site.id,
        content="User-agent: *\nAllow: /",
    )

    # Standard campaign redirects
    webflow.Redirect(
        f"{name}-home-redirect",
        site_id=site.id,
        source_path="/home",
        destination_path="/",
    )

    webflow.Redirect(
        f"{name}-signup-redirect",
        site_id=site.id,
        source_path="/join",
        destination_path="/signup",
    )

    return site


def create_product_site(name: str, display_name: str) -> webflow.Site:
    """Create a standardized product landing page with default configurations.

    Args:
        name: Unique identifier for the site (e.g., "product-alpha")
        display_name: Human-readable product name (e.g., "Product Alpha")

    Returns:
        Created Site resource
    """
    # Create site with product defaults
    site = webflow.Site(
        name,
        workspace_id=_WORKSPACE_ID,
        display_name=display_name,
    )

    # Product-specific robots.txt (allow all for indexing)
    webflow.RobotsTxt(
        f"{name}-robots",
        site_id=site.id,
        content="User-agent: *\nAllow: /",
    )

    # Standard product page redirects
    webflow.Redirect(
        f"{name}-pricing-redirect",
        site_id=site.id,
        source_path="/price",
        destination_path="/pricing",
    )

    webflow.Redirect(
        f"{name}-demo-redirect",
        site_id=site.id,
        source_path="/try",
        destination_path="/request-demo",
    )

    webflow.Redirect(
        f"{name}-docs-redirect",
        site_id=site.id,
        source_path="/help",
        destination_path="/documentation",
    )

    return site


def create_event_site(name: str, display_name: str) -> webflow.Site:
    """Create a standardized event microsite with default configurations.

    Args:
        name: Unique identifier for the site (e.g., "conference-2025")
        display_name: Event name (e.g., "Annual Conference 2025")

    Returns:
        Created Site resource
    """
    # Create site with event defaults
    site = webflow.Site(
        name,
        workspace_id=_WORKSPACE_ID,
        display_name=display_name,
    )

    # Event-specific robots.txt
    webflow.RobotsTxt(
        f"{name}-robots",
        site_id=site.id,
        content="User-agent: *\nAllow: /\nDisallow: /admin/",
    )

    # Event registration redirects
    webflow.Redirect(
        f"{name}-register-redirect",
        site_id=site.id,
        source_path="/signup",
        destination_path="/register",
    )

    webflow.Redirect(
        f"{name}-agenda-redirect",
        site_id=site.id,
        source_path="/schedule",
        destination_path="/agenda",
    )

    webflow.Redirect(
        f"{name}-speakers-redirect",
        site_id=site.id,
        source_path="/presenters",
        destination_path="/speakers",
    )

    webflow.Redirect(
        f"{name}-tickets-redirect",
        site_id=site.id,
        source_path="/buy",
        destination_path="/tickets",
    )

    return site
