using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Pulumi;
using Community.Pulumi.Webflow;

// Site Example - Creating and Managing Webflow Sites
//
// Required inputs: WorkspaceId (Enterprise workspace) and DisplayName.
// ShortName and TimeZone are read-only outputs generated by Webflow.
class Program
{
    static Task<int> Main() => Deployment.RunAsync(() =>
    {
        // Create a Pulumi config object
        var config = new Config();

        // Get configuration values
        var workspaceId = config.Require("workspaceId");
        var displayName = config.Require("displayName");

        // Example 1: Basic Site Creation
        var basicSite = new Site("basic-site", new SiteArgs
        {
            WorkspaceId = workspaceId,
            DisplayName = displayName,
        });

        // Example 2: Multi-Environment Site Configuration
        var environments = new[] { "development", "staging", "production" };
        var environmentSites = new List<Site>();

        foreach (var env in environments)
        {
            var site = new Site($"site-{env}", new SiteArgs
            {
                WorkspaceId = workspaceId,
                DisplayName = $"{displayName}-{env}",
            });
            environmentSites.Add(site);
        }

        // Example 3: Site with Optional Configuration
        var configuredArgs = new SiteArgs
        {
            WorkspaceId = workspaceId,
            DisplayName = $"{displayName}-configured",
            // Publish after every create/update once you run `pulumi config set publish true`.
            // With PublishToWebflowSubdomain the site goes to its webflow.io subdomain;
            // add custom domain IDs with PublishCustomDomains, or publish a single page
            // with PublishPageId. Leave publish off until the site is ready to go live.
            Publish = config.GetBoolean("publish") ?? false,
            PublishToWebflowSubdomain = true,
            // PublishCustomDomains = { "your-custom-domain-id" }, // domain IDs, not host names
            // PublishPageId = "your-page-id", // publish only this page instead of the whole site
        };
        // Optional: organize the site in a workspace folder
        var parentFolderId = config.Get("parentFolderId");
        if (parentFolderId != null)
        {
            configuredArgs.ParentFolderId = parentFolderId;
        }
        // Optional and IMMUTABLE: changing it later replaces (deletes + recreates) the site
        var templateName = config.Get("templateName");
        if (templateName != null)
        {
            configuredArgs.TemplateName = templateName;
        }
        var configuredSite = new Site("configured-site", configuredArgs);

        // Export the site resources for reference
        return new Dictionary<string, object?>
        {
            ["basicSiteId"] = basicSite.Id,
            ["basicSiteName"] = basicSite.DisplayName,
            // ShortName and TimeZone are generated by Webflow and available as outputs
            ["basicSiteShortName"] = basicSite.ShortName,
            ["basicSiteTimeZone"] = basicSite.TimeZone,
            ["environmentSiteIds"] = Output.All(environmentSites.Select(s => s.Id).ToArray()),
            ["configuredSiteId"] = configuredSite.Id,
            // PublishScope reports what the last provider-initiated publish targeted
            // (the webflow.io subdomain, custom domains, or a single page)
            ["configuredSitePublishScope"] = configuredSite.PublishScope,
            ["configuredSiteLastPublished"] = configuredSite.LastPublished,
        };
    });
}
