# Copyright 2025, Justin Detmar.
# SPDX-License-Identifier: MIT

import pulumi
import pulumi_webflow as webflow

# Example: Create multiple Webflow sites in a single Pulumi program
# This demonstrates the basic pattern for managing multiple sites using list comprehension

# Site creation requires an Enterprise workspace ID (pulumi config set workspaceId ...)
config = pulumi.Config()
workspace_id = config.require("workspaceId")

# Define site configurations.
# short_name and time_zone are generated by Webflow and exposed as outputs, not inputs.
site_configs = [
    {
        "name": "marketing-site",
        "display_name": "Marketing Site",
    },
    {
        "name": "docs-site",
        "display_name": "Documentation Site",
    },
    {
        "name": "blog-site",
        "display_name": "Blog Site",
    },
    {
        "name": "support-site",
        "display_name": "Support Portal",
    },
    {
        "name": "careers-site",
        "display_name": "Careers Page",
    },
]

# Create all sites using list comprehension
sites = [
    webflow.Site(
        site_config["name"],
        workspace_id=workspace_id,
        display_name=site_config["display_name"],
    )
    for site_config in site_configs
]

# Create robots.txt for each site
for i, site_config in enumerate(site_configs):
    webflow.RobotsTxt(
        f"{site_config['name']}-robots",
        site_id=sites[i].id,
        content="User-agent: *\nAllow: /",
    )

# Export site IDs (and the Webflow-generated short names) individually
for i, site_config in enumerate(site_configs):
    pulumi.export(f"{site_config['name']}-id", sites[i].id)
    pulumi.export(f"{site_config['name']}-short-name", sites[i].short_name)

# Export all site IDs as a list
pulumi.export("all-site-ids", [site.id for site in sites])
pulumi.export("site-count", len(sites))
