package io.github.jdetmar.pulumi.webflow.examples;

import com.pulumi.Pulumi;
import com.pulumi.core.Output;
import io.github.jdetmar.pulumi.webflow.Site;
import io.github.jdetmar.pulumi.webflow.SiteArgs;

import java.util.List;
import java.util.ArrayList;
import java.util.stream.Collectors;

/**
 * Site Example - Creating and Managing Webflow Sites.
 *
 * Required inputs: workspaceId (Enterprise workspace) and displayName.
 * shortName and timeZone are read-only outputs generated by Webflow.
 */
public class App {
    public static void main(String[] args) {
        Pulumi.run(ctx -> {
            // Get configuration values
            var config = ctx.config();
            var workspaceId = config.require("workspaceId");
            var displayName = config.require("displayName");

            // Example 1: Basic Site Creation
            // Create a simple site with required properties
            var basicSite = new Site("basic-site",
                SiteArgs.builder()
                    .workspaceId(workspaceId)
                    .displayName(displayName)
                    .build());

            // Example 2: Multi-Environment Site Configuration
            // Create sites for different environments using a loop
            var environments = List.of("development", "staging", "production");
            var environmentSites = new ArrayList<Site>();

            for (String env : environments) {
                var site = new Site("site-" + env,
                    SiteArgs.builder()
                        .workspaceId(workspaceId)
                        .displayName(displayName + "-" + env)
                        .build());
                environmentSites.add(site);
            }

            // Example 3: Site with Optional Configuration
            var configuredArgs = SiteArgs.builder()
                .workspaceId(workspaceId)
                .displayName(displayName + "-configured")
                // Publish after every create/update once you run `pulumi config set publish true`.
                // With publishToWebflowSubdomain the site goes to its webflow.io subdomain;
                // add custom domain IDs with publishCustomDomains, or publish a single page
                // with publishPageId. Leave publish off until the site is ready to go live.
                .publish(config.getBoolean("publish").orElse(false))
                .publishToWebflowSubdomain(true);
                // .publishCustomDomains("your-custom-domain-id") // domain IDs, not host names
                // .publishPageId("your-page-id") // publish only this page instead of the whole site
            // Optional: organize the site in a workspace folder
            config.get("parentFolderId").ifPresent(configuredArgs::parentFolderId);
            // Optional and IMMUTABLE: changing it later replaces (deletes + recreates) the site
            config.get("templateName").ifPresent(configuredArgs::templateName);
            var configuredSite = new Site("configured-site", configuredArgs.build());

            // Export values for reference
            ctx.export("basicSiteId", basicSite.id());
            ctx.export("basicSiteName", basicSite.displayName());
            // shortName and timeZone are generated by Webflow and available as outputs
            ctx.export("basicSiteShortName", basicSite.shortName());
            ctx.export("basicSiteTimeZone", basicSite.timeZone());
            ctx.export("environmentSiteIds", Output.all(environmentSites.stream()
                .map(Site::id)
                .collect(Collectors.toList())));
            ctx.export("configuredSiteId", configuredSite.id());
            // publishScope reports what the last provider-initiated publish targeted
            // (the webflow.io subdomain, custom domains, or a single page)
            ctx.export("configuredSitePublishScope", configuredSite.publishScope());
            ctx.export("configuredSiteLastPublished", configuredSite.lastPublished());
        });
    }
}
