// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.jdetmar.pulumi.webflow.AssetArgs;
import io.github.jdetmar.pulumi.webflow.Utilities;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Uploads and manages an asset (image, file, document) in a Webflow site. Create registers the asset metadata with Webflow and then uploads the file bytes from fileSource to Webflow&#39;s storage. Assets are immutable: changing any input, or changing the content of a local fileSource, replaces the asset.
 * 
 */
@ResourceType(type="webflow:index:Asset")
public class Asset extends com.pulumi.resources.CustomResource {
    /**
     * The Webflow-assigned asset ID (read-only).
     * 
     */
    @Export(name="assetId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> assetId;

    /**
     * @return The Webflow-assigned asset ID (read-only).
     * 
     */
    public Output<Optional<String>> assetId() {
        return Codegen.optional(this.assetId);
    }
    /**
     * The direct S3 URL for the asset (read-only).
     * 
     */
    @Export(name="assetUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> assetUrl;

    /**
     * @return The direct S3 URL for the asset (read-only).
     * 
     */
    public Output<Optional<String>> assetUrl() {
        return Codegen.optional(this.assetUrl);
    }
    /**
     * The MIME type of the asset (read-only), e.g., &#39;image/png&#39;, &#39;application/pdf&#39;.
     * 
     */
    @Export(name="contentType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> contentType;

    /**
     * @return The MIME type of the asset (read-only), e.g., &#39;image/png&#39;, &#39;application/pdf&#39;.
     * 
     */
    public Output<Optional<String>> contentType() {
        return Codegen.optional(this.contentType);
    }
    /**
     * The timestamp when the asset metadata was created (RFC3339 format, read-only).
     * 
     */
    @Export(name="createdOn", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> createdOn;

    /**
     * @return The timestamp when the asset metadata was created (RFC3339 format, read-only).
     * 
     */
    public Output<Optional<String>> createdOn() {
        return Codegen.optional(this.createdOn);
    }
    /**
     * MD5 hash of the file content. Computed automatically from fileSource; if you set it explicitly it must match the actual content. For local files, a content change (different hash) replaces the asset.
     * 
     */
    @Export(name="fileHash", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> fileHash;

    /**
     * @return MD5 hash of the file content. Computed automatically from fileSource; if you set it explicitly it must match the actual content. For local files, a content change (different hash) replaces the asset.
     * 
     */
    public Output<Optional<String>> fileHash() {
        return Codegen.optional(this.fileHash);
    }
    /**
     * The name of the file as it will appear in Webflow, including the extension. Examples: &#39;logo.png&#39;, &#39;hero-image.jpg&#39;, &#39;document.pdf&#39;. Must not exceed 255 characters or contain &lt;, &gt;, :, &#34;, |, ?, *.
     * 
     */
    @Export(name="fileName", refs={String.class}, tree="[0]")
    private Output<String> fileName;

    /**
     * @return The name of the file as it will appear in Webflow, including the extension. Examples: &#39;logo.png&#39;, &#39;hero-image.jpg&#39;, &#39;document.pdf&#39;. Must not exceed 255 characters or contain &lt;, &gt;, :, &#34;, |, ?, *.
     * 
     */
    public Output<String> fileName() {
        return this.fileName;
    }
    /**
     * Where the file bytes come from: a local file path (resolved relative to the Pulumi program&#39;s working directory, e.g., &#39;./assets/logo.png&#39;) or an http(s) URL (e.g., &#39;https://example.com/logo.png&#39;). The content is read at apply time, MD5-hashed and uploaded to Webflow.
     * 
     */
    @Export(name="fileSource", refs={String.class}, tree="[0]")
    private Output<String> fileSource;

    /**
     * @return Where the file bytes come from: a local file path (resolved relative to the Pulumi program&#39;s working directory, e.g., &#39;./assets/logo.png&#39;) or an http(s) URL (e.g., &#39;https://example.com/logo.png&#39;). The content is read at apply time, MD5-hashed and uploaded to Webflow.
     * 
     */
    public Output<String> fileSource() {
        return this.fileSource;
    }
    /**
     * The ID of the asset folder the asset belongs to, or empty when it is at the site root (read-only).
     * 
     */
    @Export(name="folderId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> folderId;

    /**
     * @return The ID of the asset folder the asset belongs to, or empty when it is at the site root (read-only).
     * 
     */
    public Output<Optional<String>> folderId() {
        return Codegen.optional(this.folderId);
    }
    /**
     * The Webflow CDN URL where the asset is hosted (read-only). Example: &#39;https://cdn.prod.website-files.com/.../logo.png&#39;.
     * 
     */
    @Export(name="hostedUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> hostedUrl;

    /**
     * @return The Webflow CDN URL where the asset is hosted (read-only). Example: &#39;https://cdn.prod.website-files.com/.../logo.png&#39;.
     * 
     */
    public Output<Optional<String>> hostedUrl() {
        return Codegen.optional(this.hostedUrl);
    }
    /**
     * The timestamp when the asset was last modified (RFC3339 format, read-only).
     * 
     */
    @Export(name="lastUpdated", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> lastUpdated;

    /**
     * @return The timestamp when the asset was last modified (RFC3339 format, read-only).
     * 
     */
    public Output<Optional<String>> lastUpdated() {
        return Codegen.optional(this.lastUpdated);
    }
    /**
     * Optional asset folder ID where the asset will be organized in the Webflow Assets panel. If not specified, the asset is placed at the root level. Example: &#39;5f0c8c9e1c9d440000e8d8c4&#39;.
     * 
     */
    @Export(name="parentFolder", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> parentFolder;

    /**
     * @return Optional asset folder ID where the asset will be organized in the Webflow Assets panel. If not specified, the asset is placed at the root level. Example: &#39;5f0c8c9e1c9d440000e8d8c4&#39;.
     * 
     */
    public Output<Optional<String>> parentFolder() {
        return Codegen.optional(this.parentFolder);
    }
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings.
     * 
     */
    @Export(name="siteId", refs={String.class}, tree="[0]")
    private Output<String> siteId;

    /**
     * @return The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings.
     * 
     */
    public Output<String> siteId() {
        return this.siteId;
    }
    /**
     * The size of the uploaded file in bytes (read-only).
     * 
     */
    @Export(name="size", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> size;

    /**
     * @return The size of the uploaded file in bytes (read-only).
     * 
     */
    public Output<Optional<Integer>> size() {
        return Codegen.optional(this.size);
    }
    /**
     * The signed AWS S3 POST form fields used for the upload (read-only, secret).
     * 
     */
    @Export(name="uploadDetails", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> uploadDetails;

    /**
     * @return The signed AWS S3 POST form fields used for the upload (read-only, secret).
     * 
     */
    public Output<Optional<Map<String,String>>> uploadDetails() {
        return Codegen.optional(this.uploadDetails);
    }
    /**
     * The presigned S3 URL the file was uploaded to (read-only, secret). The provider performs the upload; this is recorded for reference only.
     * 
     */
    @Export(name="uploadUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> uploadUrl;

    /**
     * @return The presigned S3 URL the file was uploaded to (read-only, secret). The provider performs the upload; this is recorded for reference only.
     * 
     */
    public Output<Optional<String>> uploadUrl() {
        return Codegen.optional(this.uploadUrl);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Asset(java.lang.String name) {
        this(name, AssetArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Asset(java.lang.String name, AssetArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Asset(java.lang.String name, AssetArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:Asset", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Asset(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:Asset", name, null, makeResourceOptions(options, id), false);
    }

    private static AssetArgs makeArgs(AssetArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? AssetArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/JDetmar/pulumi-webflow")
            .additionalSecretOutputs(List.of(
                "uploadDetails",
                "uploadUrl"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Asset get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Asset(name, id, options);
    }
}
