// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CollectionFieldArgs extends com.pulumi.resources.ResourceArgs {

    public static final CollectionFieldArgs Empty = new CollectionFieldArgs();

    /**
     * The Webflow collection ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
     * 
     */
    @Import(name="collectionId", required=true)
    private Output<String> collectionId;

    /**
     * @return The Webflow collection ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
     * 
     */
    public Output<String> collectionId() {
        return this.collectionId;
    }

    /**
     * The human-readable name of the field (e.g., &#39;Title&#39;, &#39;Description&#39;, &#39;Author&#39;). This name appears in the Webflow CMS interface. Maximum length: 255 characters.
     * 
     */
    @Import(name="displayName", required=true)
    private Output<String> displayName;

    /**
     * @return The human-readable name of the field (e.g., &#39;Title&#39;, &#39;Description&#39;, &#39;Author&#39;). This name appears in the Webflow CMS interface. Maximum length: 255 characters.
     * 
     */
    public Output<String> displayName() {
        return this.displayName;
    }

    /**
     * Optional help text shown in the CMS interface (e.g., &#39;Enter the article title&#39;). Helps content editors understand what to enter in this field.
     * 
     */
    @Import(name="helpText")
    private @Nullable Output<String> helpText;

    /**
     * @return Optional help text shown in the CMS interface (e.g., &#39;Enter the article title&#39;). Helps content editors understand what to enter in this field.
     * 
     */
    public Optional<Output<String>> helpText() {
        return Optional.ofNullable(this.helpText);
    }

    /**
     * Whether the field is required (optional, defaults to false). When true, content items must provide a value for this field.
     * 
     */
    @Import(name="isRequired")
    private @Nullable Output<Boolean> isRequired;

    /**
     * @return Whether the field is required (optional, defaults to false). When true, content items must provide a value for this field.
     * 
     */
    public Optional<Output<Boolean>> isRequired() {
        return Optional.ofNullable(this.isRequired);
    }

    /**
     * Type-specific configuration (create-only). Required for Option fields: {&#34;options&#34;: [{&#34;name&#34;: &#34;Draft&#34;}, {&#34;name&#34;: &#34;Published&#34;}]}. Required for Reference and MultiReference fields: {&#34;collectionId&#34;: &#34;&lt;referenced collection ID&gt;&#34;}. Not accepted for other field types. Changing metadata requires replacement.
     * 
     */
    @Import(name="metadata")
    private @Nullable Output<Map<String,Object>> metadata;

    /**
     * @return Type-specific configuration (create-only). Required for Option fields: {&#34;options&#34;: [{&#34;name&#34;: &#34;Draft&#34;}, {&#34;name&#34;: &#34;Published&#34;}]}. Required for Reference and MultiReference fields: {&#34;collectionId&#34;: &#34;&lt;referenced collection ID&gt;&#34;}. Not accepted for other field types. Changing metadata requires replacement.
     * 
     */
    public Optional<Output<Map<String,Object>>> metadata() {
        return Optional.ofNullable(this.metadata);
    }

    /**
     * Deprecated: the Webflow Create Field endpoint does not accept a slug; Webflow generates the slug from displayName. This input is ignored - it is never sent to the API and never causes a diff. The generated slug (used in API requests and exports) is reported in the outputs.
     * 
     * @deprecated
     * The Webflow API does not accept a slug when creating a field; Webflow generates it from displayName. This input is ignored; read the generated slug from the outputs.
     * 
     */
    @Deprecated /* The Webflow API does not accept a slug when creating a field; Webflow generates it from displayName. This input is ignored; read the generated slug from the outputs. */
    @Import(name="slug")
    private @Nullable Output<String> slug;

    /**
     * @return Deprecated: the Webflow Create Field endpoint does not accept a slug; Webflow generates the slug from displayName. This input is ignored - it is never sent to the API and never causes a diff. The generated slug (used in API requests and exports) is reported in the outputs.
     * 
     * @deprecated
     * The Webflow API does not accept a slug when creating a field; Webflow generates it from displayName. This input is ignored; read the generated slug from the outputs.
     * 
     */
    @Deprecated /* The Webflow API does not accept a slug when creating a field; Webflow generates it from displayName. This input is ignored; read the generated slug from the outputs. */
    public Optional<Output<String>> slug() {
        return Optional.ofNullable(this.slug);
    }

    /**
     * The field type (e.g., &#39;PlainText&#39;, &#39;RichText&#39;, &#39;Image&#39;, &#39;Number&#39;). Supported types: Color, DateTime, Email, File, Image, Link, MultiImage, Number, Phone, PlainText, RichText, Switch, VideoLink, Option, MultiReference, Reference. IMPORTANT: Cannot be changed after creation - changing this requires replacement.
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return The field type (e.g., &#39;PlainText&#39;, &#39;RichText&#39;, &#39;Image&#39;, &#39;Number&#39;). Supported types: Color, DateTime, Email, File, Image, Link, MultiImage, Number, Phone, PlainText, RichText, Switch, VideoLink, Option, MultiReference, Reference. IMPORTANT: Cannot be changed after creation - changing this requires replacement.
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    /**
     * Deprecated: the Webflow API does not accept validations when creating a field (&#34;field validation is currently not available through the API&#34;). This input is ignored - it is never sent to the API and never causes a diff. The validations Webflow reports for the field are available in the outputs.
     * 
     * @deprecated
     * The Webflow API does not accept field validations; this input is ignored. The validations Webflow reports are available in the outputs.
     * 
     */
    @Deprecated /* The Webflow API does not accept field validations; this input is ignored. The validations Webflow reports are available in the outputs. */
    @Import(name="validations")
    private @Nullable Output<Map<String,Object>> validations;

    /**
     * @return Deprecated: the Webflow API does not accept validations when creating a field (&#34;field validation is currently not available through the API&#34;). This input is ignored - it is never sent to the API and never causes a diff. The validations Webflow reports for the field are available in the outputs.
     * 
     * @deprecated
     * The Webflow API does not accept field validations; this input is ignored. The validations Webflow reports are available in the outputs.
     * 
     */
    @Deprecated /* The Webflow API does not accept field validations; this input is ignored. The validations Webflow reports are available in the outputs. */
    public Optional<Output<Map<String,Object>>> validations() {
        return Optional.ofNullable(this.validations);
    }

    private CollectionFieldArgs() {}

    private CollectionFieldArgs(CollectionFieldArgs $) {
        this.collectionId = $.collectionId;
        this.displayName = $.displayName;
        this.helpText = $.helpText;
        this.isRequired = $.isRequired;
        this.metadata = $.metadata;
        this.slug = $.slug;
        this.type = $.type;
        this.validations = $.validations;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CollectionFieldArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CollectionFieldArgs $;

        public Builder() {
            $ = new CollectionFieldArgs();
        }

        public Builder(CollectionFieldArgs defaults) {
            $ = new CollectionFieldArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param collectionId The Webflow collection ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder collectionId(Output<String> collectionId) {
            $.collectionId = collectionId;
            return this;
        }

        /**
         * @param collectionId The Webflow collection ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder collectionId(String collectionId) {
            return collectionId(Output.of(collectionId));
        }

        /**
         * @param displayName The human-readable name of the field (e.g., &#39;Title&#39;, &#39;Description&#39;, &#39;Author&#39;). This name appears in the Webflow CMS interface. Maximum length: 255 characters.
         * 
         * @return builder
         * 
         */
        public Builder displayName(Output<String> displayName) {
            $.displayName = displayName;
            return this;
        }

        /**
         * @param displayName The human-readable name of the field (e.g., &#39;Title&#39;, &#39;Description&#39;, &#39;Author&#39;). This name appears in the Webflow CMS interface. Maximum length: 255 characters.
         * 
         * @return builder
         * 
         */
        public Builder displayName(String displayName) {
            return displayName(Output.of(displayName));
        }

        /**
         * @param helpText Optional help text shown in the CMS interface (e.g., &#39;Enter the article title&#39;). Helps content editors understand what to enter in this field.
         * 
         * @return builder
         * 
         */
        public Builder helpText(@Nullable Output<String> helpText) {
            $.helpText = helpText;
            return this;
        }

        /**
         * @param helpText Optional help text shown in the CMS interface (e.g., &#39;Enter the article title&#39;). Helps content editors understand what to enter in this field.
         * 
         * @return builder
         * 
         */
        public Builder helpText(String helpText) {
            return helpText(Output.of(helpText));
        }

        /**
         * @param isRequired Whether the field is required (optional, defaults to false). When true, content items must provide a value for this field.
         * 
         * @return builder
         * 
         */
        public Builder isRequired(@Nullable Output<Boolean> isRequired) {
            $.isRequired = isRequired;
            return this;
        }

        /**
         * @param isRequired Whether the field is required (optional, defaults to false). When true, content items must provide a value for this field.
         * 
         * @return builder
         * 
         */
        public Builder isRequired(Boolean isRequired) {
            return isRequired(Output.of(isRequired));
        }

        /**
         * @param metadata Type-specific configuration (create-only). Required for Option fields: {&#34;options&#34;: [{&#34;name&#34;: &#34;Draft&#34;}, {&#34;name&#34;: &#34;Published&#34;}]}. Required for Reference and MultiReference fields: {&#34;collectionId&#34;: &#34;&lt;referenced collection ID&gt;&#34;}. Not accepted for other field types. Changing metadata requires replacement.
         * 
         * @return builder
         * 
         */
        public Builder metadata(@Nullable Output<Map<String,Object>> metadata) {
            $.metadata = metadata;
            return this;
        }

        /**
         * @param metadata Type-specific configuration (create-only). Required for Option fields: {&#34;options&#34;: [{&#34;name&#34;: &#34;Draft&#34;}, {&#34;name&#34;: &#34;Published&#34;}]}. Required for Reference and MultiReference fields: {&#34;collectionId&#34;: &#34;&lt;referenced collection ID&gt;&#34;}. Not accepted for other field types. Changing metadata requires replacement.
         * 
         * @return builder
         * 
         */
        public Builder metadata(Map<String,Object> metadata) {
            return metadata(Output.of(metadata));
        }

        /**
         * @param slug Deprecated: the Webflow Create Field endpoint does not accept a slug; Webflow generates the slug from displayName. This input is ignored - it is never sent to the API and never causes a diff. The generated slug (used in API requests and exports) is reported in the outputs.
         * 
         * @return builder
         * 
         * @deprecated
         * The Webflow API does not accept a slug when creating a field; Webflow generates it from displayName. This input is ignored; read the generated slug from the outputs.
         * 
         */
        @Deprecated /* The Webflow API does not accept a slug when creating a field; Webflow generates it from displayName. This input is ignored; read the generated slug from the outputs. */
        public Builder slug(@Nullable Output<String> slug) {
            $.slug = slug;
            return this;
        }

        /**
         * @param slug Deprecated: the Webflow Create Field endpoint does not accept a slug; Webflow generates the slug from displayName. This input is ignored - it is never sent to the API and never causes a diff. The generated slug (used in API requests and exports) is reported in the outputs.
         * 
         * @return builder
         * 
         * @deprecated
         * The Webflow API does not accept a slug when creating a field; Webflow generates it from displayName. This input is ignored; read the generated slug from the outputs.
         * 
         */
        @Deprecated /* The Webflow API does not accept a slug when creating a field; Webflow generates it from displayName. This input is ignored; read the generated slug from the outputs. */
        public Builder slug(String slug) {
            return slug(Output.of(slug));
        }

        /**
         * @param type The field type (e.g., &#39;PlainText&#39;, &#39;RichText&#39;, &#39;Image&#39;, &#39;Number&#39;). Supported types: Color, DateTime, Email, File, Image, Link, MultiImage, Number, Phone, PlainText, RichText, Switch, VideoLink, Option, MultiReference, Reference. IMPORTANT: Cannot be changed after creation - changing this requires replacement.
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type The field type (e.g., &#39;PlainText&#39;, &#39;RichText&#39;, &#39;Image&#39;, &#39;Number&#39;). Supported types: Color, DateTime, Email, File, Image, Link, MultiImage, Number, Phone, PlainText, RichText, Switch, VideoLink, Option, MultiReference, Reference. IMPORTANT: Cannot be changed after creation - changing this requires replacement.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        /**
         * @param validations Deprecated: the Webflow API does not accept validations when creating a field (&#34;field validation is currently not available through the API&#34;). This input is ignored - it is never sent to the API and never causes a diff. The validations Webflow reports for the field are available in the outputs.
         * 
         * @return builder
         * 
         * @deprecated
         * The Webflow API does not accept field validations; this input is ignored. The validations Webflow reports are available in the outputs.
         * 
         */
        @Deprecated /* The Webflow API does not accept field validations; this input is ignored. The validations Webflow reports are available in the outputs. */
        public Builder validations(@Nullable Output<Map<String,Object>> validations) {
            $.validations = validations;
            return this;
        }

        /**
         * @param validations Deprecated: the Webflow API does not accept validations when creating a field (&#34;field validation is currently not available through the API&#34;). This input is ignored - it is never sent to the API and never causes a diff. The validations Webflow reports for the field are available in the outputs.
         * 
         * @return builder
         * 
         * @deprecated
         * The Webflow API does not accept field validations; this input is ignored. The validations Webflow reports are available in the outputs.
         * 
         */
        @Deprecated /* The Webflow API does not accept field validations; this input is ignored. The validations Webflow reports are available in the outputs. */
        public Builder validations(Map<String,Object> validations) {
            return validations(Output.of(validations));
        }

        public CollectionFieldArgs build() {
            if ($.collectionId == null) {
                throw new MissingRequiredPropertyException("CollectionFieldArgs", "collectionId");
            }
            if ($.displayName == null) {
                throw new MissingRequiredPropertyException("CollectionFieldArgs", "displayName");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("CollectionFieldArgs", "type");
            }
            return $;
        }
    }

}
