// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CollectionArgs extends com.pulumi.resources.ResourceArgs {

    public static final CollectionArgs Empty = new CollectionArgs();

    /**
     * The human-readable name of the collection (e.g., &#39;Blog Posts&#39;, &#39;Products&#39;, &#39;Team Members&#39;). This name appears in the Webflow CMS interface. Maximum length: 255 characters.
     * 
     */
    @Import(name="displayName", required=true)
    private Output<String> displayName;

    /**
     * @return The human-readable name of the collection (e.g., &#39;Blog Posts&#39;, &#39;Products&#39;, &#39;Team Members&#39;). This name appears in the Webflow CMS interface. Maximum length: 255 characters.
     * 
     */
    public Output<String> displayName() {
        return this.displayName;
    }

    /**
     * The singular form of the collection name (e.g., &#39;Blog Post&#39; for &#39;Blog Posts&#39;, &#39;Product&#39; for &#39;Products&#39;). Used in the CMS UI when referring to individual items. Maximum length: 255 characters.
     * 
     */
    @Import(name="singularName", required=true)
    private Output<String> singularName;

    /**
     * @return The singular form of the collection name (e.g., &#39;Blog Post&#39; for &#39;Blog Posts&#39;, &#39;Product&#39; for &#39;Products&#39;). Used in the CMS UI when referring to individual items. Maximum length: 255 characters.
     * 
     */
    public Output<String> singularName() {
        return this.singularName;
    }

    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    @Import(name="siteId", required=true)
    private Output<String> siteId;

    /**
     * @return The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     * 
     */
    public Output<String> siteId() {
        return this.siteId;
    }

    /**
     * The URL-friendly slug for the collection (optional, e.g., &#39;blog-posts&#39;, &#39;products&#39;). If not provided, Webflow will auto-generate a slug from the displayName and the generated value is recorded in the resource outputs without causing a diff. The slug determines the URL path for collection items and cannot be changed after creation.
     * 
     */
    @Import(name="slug")
    private @Nullable Output<String> slug;

    /**
     * @return The URL-friendly slug for the collection (optional, e.g., &#39;blog-posts&#39;, &#39;products&#39;). If not provided, Webflow will auto-generate a slug from the displayName and the generated value is recorded in the resource outputs without causing a diff. The slug determines the URL path for collection items and cannot be changed after creation.
     * 
     */
    public Optional<Output<String>> slug() {
        return Optional.ofNullable(this.slug);
    }

    private CollectionArgs() {}

    private CollectionArgs(CollectionArgs $) {
        this.displayName = $.displayName;
        this.singularName = $.singularName;
        this.siteId = $.siteId;
        this.slug = $.slug;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CollectionArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CollectionArgs $;

        public Builder() {
            $ = new CollectionArgs();
        }

        public Builder(CollectionArgs defaults) {
            $ = new CollectionArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param displayName The human-readable name of the collection (e.g., &#39;Blog Posts&#39;, &#39;Products&#39;, &#39;Team Members&#39;). This name appears in the Webflow CMS interface. Maximum length: 255 characters.
         * 
         * @return builder
         * 
         */
        public Builder displayName(Output<String> displayName) {
            $.displayName = displayName;
            return this;
        }

        /**
         * @param displayName The human-readable name of the collection (e.g., &#39;Blog Posts&#39;, &#39;Products&#39;, &#39;Team Members&#39;). This name appears in the Webflow CMS interface. Maximum length: 255 characters.
         * 
         * @return builder
         * 
         */
        public Builder displayName(String displayName) {
            return displayName(Output.of(displayName));
        }

        /**
         * @param singularName The singular form of the collection name (e.g., &#39;Blog Post&#39; for &#39;Blog Posts&#39;, &#39;Product&#39; for &#39;Products&#39;). Used in the CMS UI when referring to individual items. Maximum length: 255 characters.
         * 
         * @return builder
         * 
         */
        public Builder singularName(Output<String> singularName) {
            $.singularName = singularName;
            return this;
        }

        /**
         * @param singularName The singular form of the collection name (e.g., &#39;Blog Post&#39; for &#39;Blog Posts&#39;, &#39;Product&#39; for &#39;Products&#39;). Used in the CMS UI when referring to individual items. Maximum length: 255 characters.
         * 
         * @return builder
         * 
         */
        public Builder singularName(String singularName) {
            return singularName(Output.of(singularName));
        }

        /**
         * @param siteId The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder siteId(Output<String> siteId) {
            $.siteId = siteId;
            return this;
        }

        /**
         * @param siteId The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
         * 
         * @return builder
         * 
         */
        public Builder siteId(String siteId) {
            return siteId(Output.of(siteId));
        }

        /**
         * @param slug The URL-friendly slug for the collection (optional, e.g., &#39;blog-posts&#39;, &#39;products&#39;). If not provided, Webflow will auto-generate a slug from the displayName and the generated value is recorded in the resource outputs without causing a diff. The slug determines the URL path for collection items and cannot be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder slug(@Nullable Output<String> slug) {
            $.slug = slug;
            return this;
        }

        /**
         * @param slug The URL-friendly slug for the collection (optional, e.g., &#39;blog-posts&#39;, &#39;products&#39;). If not provided, Webflow will auto-generate a slug from the displayName and the generated value is recorded in the resource outputs without causing a diff. The slug determines the URL path for collection items and cannot be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder slug(String slug) {
            return slug(Output.of(slug));
        }

        public CollectionArgs build() {
            if ($.displayName == null) {
                throw new MissingRequiredPropertyException("CollectionArgs", "displayName");
            }
            if ($.singularName == null) {
                throw new MissingRequiredPropertyException("CollectionArgs", "singularName");
            }
            if ($.siteId == null) {
                throw new MissingRequiredPropertyException("CollectionArgs", "siteId");
            }
            return $;
        }
    }

}
