// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import io.github.jdetmar.pulumi.webflow.GoogleTagArgs;
import io.github.jdetmar.pulumi.webflow.Utilities;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages a single Google Tag ID (Google Analytics 4, Google Tag, Google Ads or Campaign Manager) configured on a Webflow site via the Google Tag Manager integration API. Each resource manages one entry in the site&#39;s tag list, so multiple GoogleTag resources may target the same site. Tags on the site that are not managed by Pulumi are left untouched. Requires the &#39;sites:read&#39; and &#39;sites:write&#39; scopes. Webflow allows up to 25 tags per site and rejects legacy Universal Analytics &#39;UA-&#39; IDs.
 * 
 */
@ResourceType(type="webflow:index:GoogleTag")
public class GoogleTag extends com.pulumi.resources.CustomResource {
    /**
     * A human-readable label for the tag shown in the Webflow dashboard (e.g., &#39;Primary Google Analytics&#39;).
     * 
     */
    @Export(name="displayName", refs={String.class}, tree="[0]")
    private Output<String> displayName;

    /**
     * @return A human-readable label for the tag shown in the Webflow dashboard (e.g., &#39;Primary Google Analytics&#39;).
     * 
     */
    public Output<String> displayName() {
        return this.displayName;
    }
    /**
     * The display position Webflow reports for this tag. This reflects any automatic assignment or renormalization performed by Webflow and may differ from &#39;order&#39;. Read-only.
     * 
     */
    @Export(name="effectiveOrder", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> effectiveOrder;

    /**
     * @return The display position Webflow reports for this tag. This reflects any automatic assignment or renormalization performed by Webflow and may differ from &#39;order&#39;. Read-only.
     * 
     */
    public Output<Optional<Integer>> effectiveOrder() {
        return Codegen.optional(this.effectiveOrder);
    }
    /**
     * Optional display position of the tag within the site&#39;s tag list. When omitted, Webflow assigns the position automatically (see &#39;effectiveOrder&#39;). Webflow renormalizes positions after a tag is deleted, so only set this when you need to control ordering explicitly.
     * 
     */
    @Export(name="order", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> order;

    /**
     * @return Optional display position of the tag within the site&#39;s tag list. When omitted, Webflow assigns the position automatically (see &#39;effectiveOrder&#39;). Webflow renormalizes positions after a tag is deleted, so only set this when you need to control ordering explicitly.
     * 
     */
    public Output<Optional<Integer>> order() {
        return Codegen.optional(this.order);
    }
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). Changing this value replaces the resource.
     * 
     */
    @Export(name="siteId", refs={String.class}, tree="[0]")
    private Output<String> siteId;

    /**
     * @return The Webflow site ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c3&#39;). Changing this value replaces the resource.
     * 
     */
    public Output<String> siteId() {
        return this.siteId;
    }
    /**
     * The Google Tag ID to configure, e.g., &#39;G-1A2B3C4D5E&#39; (GA4 measurement ID), &#39;GT-ABC123&#39; (Google Tag), &#39;AW-123456789&#39; (Google Ads) or &#39;DC-1234567&#39; (Campaign Manager). Webflow rejects Universal Analytics &#39;UA-&#39; IDs. Changing this value replaces the resource.
     * 
     */
    @Export(name="tagId", refs={String.class}, tree="[0]")
    private Output<String> tagId;

    /**
     * @return The Google Tag ID to configure, e.g., &#39;G-1A2B3C4D5E&#39; (GA4 measurement ID), &#39;GT-ABC123&#39; (Google Tag), &#39;AW-123456789&#39; (Google Ads) or &#39;DC-1234567&#39; (Campaign Manager). Webflow rejects Universal Analytics &#39;UA-&#39; IDs. Changing this value replaces the resource.
     * 
     */
    public Output<String> tagId() {
        return this.tagId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public GoogleTag(java.lang.String name) {
        this(name, GoogleTagArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public GoogleTag(java.lang.String name, GoogleTagArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public GoogleTag(java.lang.String name, GoogleTagArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:GoogleTag", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private GoogleTag(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("webflow:index:GoogleTag", name, null, makeResourceOptions(options, id), false);
    }

    private static GoogleTagArgs makeArgs(GoogleTagArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? GoogleTagArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/JDetmar/pulumi-webflow")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static GoogleTag get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new GoogleTag(name, id, options);
    }
}
