// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.jdetmar.pulumi.webflow.inputs.NodeContentUpdateArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PageContentArgs extends com.pulumi.resources.ResourceArgs {

    public static final PageContentArgs Empty = new PageContentArgs();

    /**
     * Optional locale ID to update a secondary locale. When omitted the localeId query parameter is not sent and Webflow updates the primary locale.
     * 
     */
    @Import(name="localeId")
    private @Nullable Output<String> localeId;

    /**
     * @return Optional locale ID to update a secondary locale. When omitted the localeId query parameter is not sent and Webflow updates the primary locale.
     * 
     */
    public Optional<Output<String>> localeId() {
        return Optional.ofNullable(this.localeId);
    }

    /**
     * List of node content updates to apply. Each entry names a nodeId from the page&#39;s DOM and the new text (HTML allowed). Node IDs must be unique within the list.
     * 
     */
    @Import(name="nodes", required=true)
    private Output<List<NodeContentUpdateArgs>> nodes;

    /**
     * @return List of node content updates to apply. Each entry names a nodeId from the page&#39;s DOM and the new text (HTML allowed). Node IDs must be unique within the list.
     * 
     */
    public Output<List<NodeContentUpdateArgs>> nodes() {
        return this.nodes;
    }

    /**
     * The Webflow page ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). Use the getPages function to find page IDs.
     * 
     */
    @Import(name="pageId", required=true)
    private Output<String> pageId;

    /**
     * @return The Webflow page ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). Use the getPages function to find page IDs.
     * 
     */
    public Output<String> pageId() {
        return this.pageId;
    }

    private PageContentArgs() {}

    private PageContentArgs(PageContentArgs $) {
        this.localeId = $.localeId;
        this.nodes = $.nodes;
        this.pageId = $.pageId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PageContentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PageContentArgs $;

        public Builder() {
            $ = new PageContentArgs();
        }

        public Builder(PageContentArgs defaults) {
            $ = new PageContentArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param localeId Optional locale ID to update a secondary locale. When omitted the localeId query parameter is not sent and Webflow updates the primary locale.
         * 
         * @return builder
         * 
         */
        public Builder localeId(@Nullable Output<String> localeId) {
            $.localeId = localeId;
            return this;
        }

        /**
         * @param localeId Optional locale ID to update a secondary locale. When omitted the localeId query parameter is not sent and Webflow updates the primary locale.
         * 
         * @return builder
         * 
         */
        public Builder localeId(String localeId) {
            return localeId(Output.of(localeId));
        }

        /**
         * @param nodes List of node content updates to apply. Each entry names a nodeId from the page&#39;s DOM and the new text (HTML allowed). Node IDs must be unique within the list.
         * 
         * @return builder
         * 
         */
        public Builder nodes(Output<List<NodeContentUpdateArgs>> nodes) {
            $.nodes = nodes;
            return this;
        }

        /**
         * @param nodes List of node content updates to apply. Each entry names a nodeId from the page&#39;s DOM and the new text (HTML allowed). Node IDs must be unique within the list.
         * 
         * @return builder
         * 
         */
        public Builder nodes(List<NodeContentUpdateArgs> nodes) {
            return nodes(Output.of(nodes));
        }

        /**
         * @param nodes List of node content updates to apply. Each entry names a nodeId from the page&#39;s DOM and the new text (HTML allowed). Node IDs must be unique within the list.
         * 
         * @return builder
         * 
         */
        public Builder nodes(NodeContentUpdateArgs... nodes) {
            return nodes(List.of(nodes));
        }

        /**
         * @param pageId The Webflow page ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). Use the getPages function to find page IDs.
         * 
         * @return builder
         * 
         */
        public Builder pageId(Output<String> pageId) {
            $.pageId = pageId;
            return this;
        }

        /**
         * @param pageId The Webflow page ID (24-character lowercase hexadecimal string, e.g., &#39;5f0c8c9e1c9d440000e8d8c4&#39;). Use the getPages function to find page IDs.
         * 
         * @return builder
         * 
         */
        public Builder pageId(String pageId) {
            return pageId(Output.of(pageId));
        }

        public PageContentArgs build() {
            if ($.nodes == null) {
                throw new MissingRequiredPropertyException("PageContentArgs", "nodes");
            }
            if ($.pageId == null) {
                throw new MissingRequiredPropertyException("PageContentArgs", "pageId");
            }
            return $;
        }
    }

}
