// Copyright 2025, Justin Detmar.
// SPDX-License-Identifier: MIT

import * as pulumi from "@pulumi/pulumi";
import * as webflow from "@jdetmar/pulumi-webflow";

// Log configuration loading (INFO level - always shown)
pulumi.log.info("🔍 Loading configuration for troubleshooting example");

// Log detailed config (DEBUG level - only visible with `pulumi up -v=9 --logtostderr`)
pulumi.log.debug("Pulumi context initialized for troubleshooting");

// Site creation requires an Enterprise workspace ID (pulumi config set workspaceId ...)
const config = new pulumi.Config();
const workspaceId = config.require("workspaceId");

// Example: Troubleshooting authentication
pulumi.log.info("🔐 Verifying Webflow API authentication");
pulumi.log.debug("Token source: Pulumi config (credentials redacted in logs)");

// Create a site with logging at each step.
// shortName and timeZone are generated by Webflow and available as outputs.
pulumi.log.info("🏗️  Creating Webflow site");

const site = new webflow.Site("troubleshooting-site", {
    workspaceId: workspaceId,
    displayName: "Troubleshooting Example Site",
});

// Log resource creation (ID only shown after deployment)
site.id.apply((id: string) => {
    pulumi.log.info(`✅ Site created successfully: ${id}`);
    pulumi.log.debug(`Site details: displayName=Troubleshooting Example Site`);
    return id;
});

// Example: Error handling with logging
site.id.apply((id: string) => {
    pulumi.log.info("🤖 Configuring robots.txt");

    const robots = new webflow.RobotsTxt("troubleshoot-robots", {
        siteId: id,
        content: "User-agent: *\nAllow: /\n",
    });

    pulumi.log.info("✅ Robots.txt configured successfully");
    return robots;
});

// Export with logging (stack outputs in TypeScript are top-level `export`s)
export const siteId = site.id;
export const siteShortName = site.shortName;
pulumi.log.info("📤 Exported site ID for reference");
