#!/usr/bin/env python3
# Copyright 2025, Justin Detmar.
# SPDX-License-Identifier: MIT

import os
import pulumi
import pulumi_webflow as webflow

# Detect CI/CD environment
is_ci = os.getenv("CI") == "true"
environment = os.getenv("PULUMI_STACK", "unknown")

# Configure logging based on environment
if is_ci:
    pulumi.log.info(f"🤖 Running in CI/CD environment: {environment}")
    pulumi.log.debug("Verbose logging enabled for CI/CD troubleshooting")
else:
    pulumi.log.info(f"💻 Running in local environment: {environment}")

# Always log credential source (without exposing values).
# Note: when both are set, webflow:apiToken wins; WEBFLOW_API_TOKEN is only the fallback.
token_source = "environment" if os.getenv("WEBFLOW_API_TOKEN") else "pulumi_config"
pulumi.log.info(f"🔐 Using API token from: {token_source}")
pulumi.log.debug("API credentials are redacted from all log output")

# Production: minimal logging
# Development: verbose logging (debug messages need `pulumi up -v=9 --logtostderr`)
log_level = "info" if environment == "prod" else "debug"
pulumi.log.info(f"📊 Log level: {log_level}")

# Site creation requires an Enterprise workspace ID (pulumi config set workspaceId ...)
config = pulumi.Config()
workspace_id = config.require("workspaceId")

# Create a Webflow site for CI/CD environment.
# short_name and time_zone are generated by Webflow and available as outputs.
pulumi.log.info("🚀 Creating Webflow site for CI/CD pipeline")

site = webflow.Site(
    "cicd-logging-site",
    workspace_id=workspace_id,
    display_name="CI/CD Logging Example Site",
)

pulumi.log.debug(f"Site creation request submitted (details redacted)")

# Configure robots.txt with environment-specific settings
site_id = site.id.apply(lambda id: id)

def configure_robots(site_id):
    pulumi.log.info(f"🤖 Configuring robots.txt for site: {site_id}")

    # Environment-specific robots.txt content
    if environment == "prod":
        robots_content = "User-agent: *\nAllow: /\n"
        pulumi.log.debug("Using production robots.txt (allow all)")
    else:
        robots_content = f"User-agent: *\nDisallow: /\n\n# {environment.upper()} ENVIRONMENT - NOT FOR INDEXING"
        pulumi.log.debug(f"Using {environment} robots.txt (disallow all)")

    robots = webflow.RobotsTxt(
        f"{environment}-robots",
        site_id=site_id,
        content=robots_content,
    )

    pulumi.log.info(f"✅ Robots.txt configured for {environment} environment")
    return robots

robots = site_id.apply(configure_robots)

# Export results
pulumi.export("site_id", site.id)
pulumi.export("site_short_name", site.short_name)
pulumi.export("environment", environment)
pulumi.export("is_ci", is_ci)
pulumi.log.info("📤 Exported stack outputs for CI/CD pipeline")
