// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class AnalyticsCountPoint {
    /**
     * @return Number of sessions, users, pageviews or events in the bucket, per the report&#39;s metric scope.
     * 
     */
    private Integer count;
    /**
     * @return Start of the time bucket as a UTC instant in ISO 8601 / RFC 3339 format.
     * 
     */
    private String timestamp;

    private AnalyticsCountPoint() {}
    /**
     * @return Number of sessions, users, pageviews or events in the bucket, per the report&#39;s metric scope.
     * 
     */
    public Integer count() {
        return this.count;
    }
    /**
     * @return Start of the time bucket as a UTC instant in ISO 8601 / RFC 3339 format.
     * 
     */
    public String timestamp() {
        return this.timestamp;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AnalyticsCountPoint defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer count;
        private String timestamp;
        public Builder() {}
        public Builder(AnalyticsCountPoint defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.count = defaults.count;
    	      this.timestamp = defaults.timestamp;
        }

        @CustomType.Setter
        public Builder count(Integer count) {
            if (count == null) {
              throw new MissingRequiredPropertyException("AnalyticsCountPoint", "count");
            }
            this.count = count;
            return this;
        }
        @CustomType.Setter
        public Builder timestamp(String timestamp) {
            if (timestamp == null) {
              throw new MissingRequiredPropertyException("AnalyticsCountPoint", "timestamp");
            }
            this.timestamp = timestamp;
            return this;
        }
        public AnalyticsCountPoint build() {
            final var _resultValue = new AnalyticsCountPoint();
            _resultValue.count = count;
            _resultValue.timestamp = timestamp;
            return _resultValue;
        }
    }
}
