// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class AnalyticsDimensionRow {
    /**
     * @return The raw value of the dimension (e.g., &#39;US-CA&#39; for a region, &#39;SO&#39; for a traffic source).
     * 
     */
    private String attributeKey;
    /**
     * @return Number of sessions or users with this value, per the requested metric scope.
     * 
     */
    private Integer count;
    /**
     * @return A human-readable label for the value (e.g., &#39;California, United States&#39;).
     * 
     */
    private String name;

    private AnalyticsDimensionRow() {}
    /**
     * @return The raw value of the dimension (e.g., &#39;US-CA&#39; for a region, &#39;SO&#39; for a traffic source).
     * 
     */
    public String attributeKey() {
        return this.attributeKey;
    }
    /**
     * @return Number of sessions or users with this value, per the requested metric scope.
     * 
     */
    public Integer count() {
        return this.count;
    }
    /**
     * @return A human-readable label for the value (e.g., &#39;California, United States&#39;).
     * 
     */
    public String name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AnalyticsDimensionRow defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String attributeKey;
        private Integer count;
        private String name;
        public Builder() {}
        public Builder(AnalyticsDimensionRow defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.attributeKey = defaults.attributeKey;
    	      this.count = defaults.count;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder attributeKey(String attributeKey) {
            if (attributeKey == null) {
              throw new MissingRequiredPropertyException("AnalyticsDimensionRow", "attributeKey");
            }
            this.attributeKey = attributeKey;
            return this;
        }
        @CustomType.Setter
        public Builder count(Integer count) {
            if (count == null) {
              throw new MissingRequiredPropertyException("AnalyticsDimensionRow", "count");
            }
            this.count = count;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("AnalyticsDimensionRow", "name");
            }
            this.name = name;
            return this;
        }
        public AnalyticsDimensionRow build() {
            final var _resultValue = new AnalyticsDimensionRow();
            _resultValue.attributeKey = attributeKey;
            _resultValue.count = count;
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
