// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.jdetmar.pulumi.webflow.outputs.AnalyticsBucketing;
import io.github.jdetmar.pulumi.webflow.outputs.AnalyticsDimensionFilter;
import io.github.jdetmar.pulumi.webflow.outputs.AnalyticsTopPageRow;
import io.github.jdetmar.pulumi.webflow.outputs.AnalyticsWindow;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetAnalyticsTopPagesResult {
    /**
     * @return The bucketing applied to per-page time series; present only when &#39;timeseries&#39; was requested.
     * 
     */
    private @Nullable AnalyticsBucketing bucketing;
    /**
     * @return The ranked pages, most visited first.
     * 
     */
    private List<AnalyticsTopPageRow> data;
    /**
     * @return The filters that were applied, keyed by dimension.
     * 
     */
    private @Nullable Map<String,AnalyticsDimensionFilter> filters;
    /**
     * @return The row cap that was applied (echoes the request value, including the default).
     * 
     */
    private Integer limit;
    /**
     * @return The report name, always &#39;top_pages&#39;.
     * 
     */
    private String report;
    /**
     * @return The metric rows were ranked by: &#39;session&#39;, &#39;user&#39; or &#39;pageview&#39;.
     * 
     */
    private String sortBy;
    /**
     * @return The reporting window that was applied.
     * 
     */
    private AnalyticsWindow window;

    private GetAnalyticsTopPagesResult() {}
    /**
     * @return The bucketing applied to per-page time series; present only when &#39;timeseries&#39; was requested.
     * 
     */
    public Optional<AnalyticsBucketing> bucketing() {
        return Optional.ofNullable(this.bucketing);
    }
    /**
     * @return The ranked pages, most visited first.
     * 
     */
    public List<AnalyticsTopPageRow> data() {
        return this.data;
    }
    /**
     * @return The filters that were applied, keyed by dimension.
     * 
     */
    public Map<String,AnalyticsDimensionFilter> filters() {
        return this.filters == null ? Map.of() : this.filters;
    }
    /**
     * @return The row cap that was applied (echoes the request value, including the default).
     * 
     */
    public Integer limit() {
        return this.limit;
    }
    /**
     * @return The report name, always &#39;top_pages&#39;.
     * 
     */
    public String report() {
        return this.report;
    }
    /**
     * @return The metric rows were ranked by: &#39;session&#39;, &#39;user&#39; or &#39;pageview&#39;.
     * 
     */
    public String sortBy() {
        return this.sortBy;
    }
    /**
     * @return The reporting window that was applied.
     * 
     */
    public AnalyticsWindow window() {
        return this.window;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAnalyticsTopPagesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable AnalyticsBucketing bucketing;
        private List<AnalyticsTopPageRow> data;
        private @Nullable Map<String,AnalyticsDimensionFilter> filters;
        private Integer limit;
        private String report;
        private String sortBy;
        private AnalyticsWindow window;
        public Builder() {}
        public Builder(GetAnalyticsTopPagesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.bucketing = defaults.bucketing;
    	      this.data = defaults.data;
    	      this.filters = defaults.filters;
    	      this.limit = defaults.limit;
    	      this.report = defaults.report;
    	      this.sortBy = defaults.sortBy;
    	      this.window = defaults.window;
        }

        @CustomType.Setter
        public Builder bucketing(@Nullable AnalyticsBucketing bucketing) {

            this.bucketing = bucketing;
            return this;
        }
        @CustomType.Setter
        public Builder data(List<AnalyticsTopPageRow> data) {
            if (data == null) {
              throw new MissingRequiredPropertyException("GetAnalyticsTopPagesResult", "data");
            }
            this.data = data;
            return this;
        }
        public Builder data(AnalyticsTopPageRow... data) {
            return data(List.of(data));
        }
        @CustomType.Setter
        public Builder filters(@Nullable Map<String,AnalyticsDimensionFilter> filters) {

            this.filters = filters;
            return this;
        }
        @CustomType.Setter
        public Builder limit(Integer limit) {
            if (limit == null) {
              throw new MissingRequiredPropertyException("GetAnalyticsTopPagesResult", "limit");
            }
            this.limit = limit;
            return this;
        }
        @CustomType.Setter
        public Builder report(String report) {
            if (report == null) {
              throw new MissingRequiredPropertyException("GetAnalyticsTopPagesResult", "report");
            }
            this.report = report;
            return this;
        }
        @CustomType.Setter
        public Builder sortBy(String sortBy) {
            if (sortBy == null) {
              throw new MissingRequiredPropertyException("GetAnalyticsTopPagesResult", "sortBy");
            }
            this.sortBy = sortBy;
            return this;
        }
        @CustomType.Setter
        public Builder window(AnalyticsWindow window) {
            if (window == null) {
              throw new MissingRequiredPropertyException("GetAnalyticsTopPagesResult", "window");
            }
            this.window = window;
            return this;
        }
        public GetAnalyticsTopPagesResult build() {
            final var _resultValue = new GetAnalyticsTopPagesResult();
            _resultValue.bucketing = bucketing;
            _resultValue.data = data;
            _resultValue.filters = filters;
            _resultValue.limit = limit;
            _resultValue.report = report;
            _resultValue.sortBy = sortBy;
            _resultValue.window = window;
            return _resultValue;
        }
    }
}
