// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.jdetmar.pulumi.webflow.outputs.AnalyticsBucketing;
import io.github.jdetmar.pulumi.webflow.outputs.AnalyticsCountPoint;
import io.github.jdetmar.pulumi.webflow.outputs.AnalyticsDimensionFilter;
import io.github.jdetmar.pulumi.webflow.outputs.AnalyticsWindow;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetAnalyticsTrafficResult {
    /**
     * @return The bucketing applied to the time series (daily, in the requested time zone).
     * 
     */
    private @Nullable AnalyticsBucketing bucketing;
    /**
     * @return One data point per day, ordered by timestamp.
     * 
     */
    private List<AnalyticsCountPoint> data;
    /**
     * @return The filters that were applied, keyed by dimension.
     * 
     */
    private @Nullable Map<String,AnalyticsDimensionFilter> filters;
    /**
     * @return The unit each count is measured in: &#39;session&#39;, &#39;user&#39; or &#39;pageview&#39;.
     * 
     */
    private String metricScope;
    /**
     * @return The report name, always &#39;traffic&#39;.
     * 
     */
    private String report;
    /**
     * @return The reporting window that was applied.
     * 
     */
    private AnalyticsWindow window;

    private GetAnalyticsTrafficResult() {}
    /**
     * @return The bucketing applied to the time series (daily, in the requested time zone).
     * 
     */
    public Optional<AnalyticsBucketing> bucketing() {
        return Optional.ofNullable(this.bucketing);
    }
    /**
     * @return One data point per day, ordered by timestamp.
     * 
     */
    public List<AnalyticsCountPoint> data() {
        return this.data;
    }
    /**
     * @return The filters that were applied, keyed by dimension.
     * 
     */
    public Map<String,AnalyticsDimensionFilter> filters() {
        return this.filters == null ? Map.of() : this.filters;
    }
    /**
     * @return The unit each count is measured in: &#39;session&#39;, &#39;user&#39; or &#39;pageview&#39;.
     * 
     */
    public String metricScope() {
        return this.metricScope;
    }
    /**
     * @return The report name, always &#39;traffic&#39;.
     * 
     */
    public String report() {
        return this.report;
    }
    /**
     * @return The reporting window that was applied.
     * 
     */
    public AnalyticsWindow window() {
        return this.window;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAnalyticsTrafficResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable AnalyticsBucketing bucketing;
        private List<AnalyticsCountPoint> data;
        private @Nullable Map<String,AnalyticsDimensionFilter> filters;
        private String metricScope;
        private String report;
        private AnalyticsWindow window;
        public Builder() {}
        public Builder(GetAnalyticsTrafficResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.bucketing = defaults.bucketing;
    	      this.data = defaults.data;
    	      this.filters = defaults.filters;
    	      this.metricScope = defaults.metricScope;
    	      this.report = defaults.report;
    	      this.window = defaults.window;
        }

        @CustomType.Setter
        public Builder bucketing(@Nullable AnalyticsBucketing bucketing) {

            this.bucketing = bucketing;
            return this;
        }
        @CustomType.Setter
        public Builder data(List<AnalyticsCountPoint> data) {
            if (data == null) {
              throw new MissingRequiredPropertyException("GetAnalyticsTrafficResult", "data");
            }
            this.data = data;
            return this;
        }
        public Builder data(AnalyticsCountPoint... data) {
            return data(List.of(data));
        }
        @CustomType.Setter
        public Builder filters(@Nullable Map<String,AnalyticsDimensionFilter> filters) {

            this.filters = filters;
            return this;
        }
        @CustomType.Setter
        public Builder metricScope(String metricScope) {
            if (metricScope == null) {
              throw new MissingRequiredPropertyException("GetAnalyticsTrafficResult", "metricScope");
            }
            this.metricScope = metricScope;
            return this;
        }
        @CustomType.Setter
        public Builder report(String report) {
            if (report == null) {
              throw new MissingRequiredPropertyException("GetAnalyticsTrafficResult", "report");
            }
            this.report = report;
            return this;
        }
        @CustomType.Setter
        public Builder window(AnalyticsWindow window) {
            if (window == null) {
              throw new MissingRequiredPropertyException("GetAnalyticsTrafficResult", "window");
            }
            this.window = window;
            return this;
        }
        public GetAnalyticsTrafficResult build() {
            final var _resultValue = new GetAnalyticsTrafficResult();
            _resultValue.bucketing = bucketing;
            _resultValue.data = data;
            _resultValue.filters = filters;
            _resultValue.metricScope = metricScope;
            _resultValue.report = report;
            _resultValue.window = window;
            return _resultValue;
        }
    }
}
