// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.jdetmar.pulumi.webflow.outputs.PageRecord;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetPagesResult {
    /**
     * @return All pages of the site.
     * 
     */
    private List<PageRecord> pages;
    /**
     * @return The site ID that was listed.
     * 
     */
    private String siteId;

    private GetPagesResult() {}
    /**
     * @return All pages of the site.
     * 
     */
    public List<PageRecord> pages() {
        return this.pages;
    }
    /**
     * @return The site ID that was listed.
     * 
     */
    public String siteId() {
        return this.siteId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPagesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<PageRecord> pages;
        private String siteId;
        public Builder() {}
        public Builder(GetPagesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.pages = defaults.pages;
    	      this.siteId = defaults.siteId;
        }

        @CustomType.Setter
        public Builder pages(List<PageRecord> pages) {
            if (pages == null) {
              throw new MissingRequiredPropertyException("GetPagesResult", "pages");
            }
            this.pages = pages;
            return this;
        }
        public Builder pages(PageRecord... pages) {
            return pages(List.of(pages));
        }
        @CustomType.Setter
        public Builder siteId(String siteId) {
            if (siteId == null) {
              throw new MissingRequiredPropertyException("GetPagesResult", "siteId");
            }
            this.siteId = siteId;
            return this;
        }
        public GetPagesResult build() {
            final var _resultValue = new GetPagesResult();
            _resultValue.pages = pages;
            _resultValue.siteId = siteId;
            return _resultValue;
        }
    }
}
