// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package io.github.jdetmar.pulumi.webflow.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import io.github.jdetmar.pulumi.webflow.outputs.PageOpenGraphRecord;
import io.github.jdetmar.pulumi.webflow.outputs.PageSEORecord;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetPageResult {
    /**
     * @return Whether the page is archived.
     * 
     */
    private Boolean archived;
    /**
     * @return The ID of the parent branch, or empty.
     * 
     */
    private String branchId;
    /**
     * @return Whether the page can be branched.
     * 
     */
    private Boolean canBranch;
    /**
     * @return The CMS collection ID for collection template pages, or empty.
     * 
     */
    private String collectionId;
    /**
     * @return The timestamp when the page was created (RFC3339 format).
     * 
     */
    private String createdOn;
    /**
     * @return Whether the page is a draft.
     * 
     */
    private Boolean draft;
    /**
     * @return Whether the page is a branch of another page.
     * 
     */
    private Boolean isBranch;
    /**
     * @return The timestamp when the page was last updated (RFC3339 format).
     * 
     */
    private String lastUpdated;
    /**
     * @return The locale ID of the returned page data, or empty for the primary locale.
     * 
     */
    private String localeId;
    /**
     * @return The Open Graph settings of the page.
     * 
     */
    private PageOpenGraphRecord openGraph;
    /**
     * @return The Webflow page ID.
     * 
     */
    private String pageId;
    /**
     * @return The ID of the parent folder, or empty when the page is at the root.
     * 
     */
    private String parentId;
    /**
     * @return The relative URL path of the published page.
     * 
     */
    private String publishedPath;
    /**
     * @return The SEO title and description of the page.
     * 
     */
    private PageSEORecord seo;
    /**
     * @return The Webflow site ID this page belongs to.
     * 
     */
    private String siteId;
    /**
     * @return The URL slug of the page (e.g., &#39;about&#39; for &#39;/about&#39;).
     * 
     */
    private String slug;
    /**
     * @return The page title shown in browser tabs and search results.
     * 
     */
    private String title;

    private GetPageResult() {}
    /**
     * @return Whether the page is archived.
     * 
     */
    public Boolean archived() {
        return this.archived;
    }
    /**
     * @return The ID of the parent branch, or empty.
     * 
     */
    public String branchId() {
        return this.branchId;
    }
    /**
     * @return Whether the page can be branched.
     * 
     */
    public Boolean canBranch() {
        return this.canBranch;
    }
    /**
     * @return The CMS collection ID for collection template pages, or empty.
     * 
     */
    public String collectionId() {
        return this.collectionId;
    }
    /**
     * @return The timestamp when the page was created (RFC3339 format).
     * 
     */
    public String createdOn() {
        return this.createdOn;
    }
    /**
     * @return Whether the page is a draft.
     * 
     */
    public Boolean draft() {
        return this.draft;
    }
    /**
     * @return Whether the page is a branch of another page.
     * 
     */
    public Boolean isBranch() {
        return this.isBranch;
    }
    /**
     * @return The timestamp when the page was last updated (RFC3339 format).
     * 
     */
    public String lastUpdated() {
        return this.lastUpdated;
    }
    /**
     * @return The locale ID of the returned page data, or empty for the primary locale.
     * 
     */
    public String localeId() {
        return this.localeId;
    }
    /**
     * @return The Open Graph settings of the page.
     * 
     */
    public PageOpenGraphRecord openGraph() {
        return this.openGraph;
    }
    /**
     * @return The Webflow page ID.
     * 
     */
    public String pageId() {
        return this.pageId;
    }
    /**
     * @return The ID of the parent folder, or empty when the page is at the root.
     * 
     */
    public String parentId() {
        return this.parentId;
    }
    /**
     * @return The relative URL path of the published page.
     * 
     */
    public String publishedPath() {
        return this.publishedPath;
    }
    /**
     * @return The SEO title and description of the page.
     * 
     */
    public PageSEORecord seo() {
        return this.seo;
    }
    /**
     * @return The Webflow site ID this page belongs to.
     * 
     */
    public String siteId() {
        return this.siteId;
    }
    /**
     * @return The URL slug of the page (e.g., &#39;about&#39; for &#39;/about&#39;).
     * 
     */
    public String slug() {
        return this.slug;
    }
    /**
     * @return The page title shown in browser tabs and search results.
     * 
     */
    public String title() {
        return this.title;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetPageResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Boolean archived;
        private String branchId;
        private Boolean canBranch;
        private String collectionId;
        private String createdOn;
        private Boolean draft;
        private Boolean isBranch;
        private String lastUpdated;
        private String localeId;
        private PageOpenGraphRecord openGraph;
        private String pageId;
        private String parentId;
        private String publishedPath;
        private PageSEORecord seo;
        private String siteId;
        private String slug;
        private String title;
        public Builder() {}
        public Builder(GetPageResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.archived = defaults.archived;
    	      this.branchId = defaults.branchId;
    	      this.canBranch = defaults.canBranch;
    	      this.collectionId = defaults.collectionId;
    	      this.createdOn = defaults.createdOn;
    	      this.draft = defaults.draft;
    	      this.isBranch = defaults.isBranch;
    	      this.lastUpdated = defaults.lastUpdated;
    	      this.localeId = defaults.localeId;
    	      this.openGraph = defaults.openGraph;
    	      this.pageId = defaults.pageId;
    	      this.parentId = defaults.parentId;
    	      this.publishedPath = defaults.publishedPath;
    	      this.seo = defaults.seo;
    	      this.siteId = defaults.siteId;
    	      this.slug = defaults.slug;
    	      this.title = defaults.title;
        }

        @CustomType.Setter
        public Builder archived(Boolean archived) {
            if (archived == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "archived");
            }
            this.archived = archived;
            return this;
        }
        @CustomType.Setter
        public Builder branchId(String branchId) {
            if (branchId == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "branchId");
            }
            this.branchId = branchId;
            return this;
        }
        @CustomType.Setter
        public Builder canBranch(Boolean canBranch) {
            if (canBranch == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "canBranch");
            }
            this.canBranch = canBranch;
            return this;
        }
        @CustomType.Setter
        public Builder collectionId(String collectionId) {
            if (collectionId == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "collectionId");
            }
            this.collectionId = collectionId;
            return this;
        }
        @CustomType.Setter
        public Builder createdOn(String createdOn) {
            if (createdOn == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "createdOn");
            }
            this.createdOn = createdOn;
            return this;
        }
        @CustomType.Setter
        public Builder draft(Boolean draft) {
            if (draft == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "draft");
            }
            this.draft = draft;
            return this;
        }
        @CustomType.Setter
        public Builder isBranch(Boolean isBranch) {
            if (isBranch == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "isBranch");
            }
            this.isBranch = isBranch;
            return this;
        }
        @CustomType.Setter
        public Builder lastUpdated(String lastUpdated) {
            if (lastUpdated == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "lastUpdated");
            }
            this.lastUpdated = lastUpdated;
            return this;
        }
        @CustomType.Setter
        public Builder localeId(String localeId) {
            if (localeId == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "localeId");
            }
            this.localeId = localeId;
            return this;
        }
        @CustomType.Setter
        public Builder openGraph(PageOpenGraphRecord openGraph) {
            if (openGraph == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "openGraph");
            }
            this.openGraph = openGraph;
            return this;
        }
        @CustomType.Setter
        public Builder pageId(String pageId) {
            if (pageId == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "pageId");
            }
            this.pageId = pageId;
            return this;
        }
        @CustomType.Setter
        public Builder parentId(String parentId) {
            if (parentId == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "parentId");
            }
            this.parentId = parentId;
            return this;
        }
        @CustomType.Setter
        public Builder publishedPath(String publishedPath) {
            if (publishedPath == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "publishedPath");
            }
            this.publishedPath = publishedPath;
            return this;
        }
        @CustomType.Setter
        public Builder seo(PageSEORecord seo) {
            if (seo == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "seo");
            }
            this.seo = seo;
            return this;
        }
        @CustomType.Setter
        public Builder siteId(String siteId) {
            if (siteId == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "siteId");
            }
            this.siteId = siteId;
            return this;
        }
        @CustomType.Setter
        public Builder slug(String slug) {
            if (slug == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "slug");
            }
            this.slug = slug;
            return this;
        }
        @CustomType.Setter
        public Builder title(String title) {
            if (title == null) {
              throw new MissingRequiredPropertyException("GetPageResult", "title");
            }
            this.title = title;
            return this;
        }
        public GetPageResult build() {
            final var _resultValue = new GetPageResult();
            _resultValue.archived = archived;
            _resultValue.branchId = branchId;
            _resultValue.canBranch = canBranch;
            _resultValue.collectionId = collectionId;
            _resultValue.createdOn = createdOn;
            _resultValue.draft = draft;
            _resultValue.isBranch = isBranch;
            _resultValue.lastUpdated = lastUpdated;
            _resultValue.localeId = localeId;
            _resultValue.openGraph = openGraph;
            _resultValue.pageId = pageId;
            _resultValue.parentId = parentId;
            _resultValue.publishedPath = publishedPath;
            _resultValue.seo = seo;
            _resultValue.siteId = siteId;
            _resultValue.slug = slug;
            _resultValue.title = title;
            return _resultValue;
        }
    }
}
