# Copyright 2025, Justin Detmar.
# SPDX-License-Identifier: MIT

import pulumi
import pulumi_webflow as webflow

# Create a Pulumi config object
config = pulumi.Config()

# Get configuration values
workspace_id = config.require("workspaceId")
display_name = config.require("displayName")

"""
Site Example - Creating and Managing Webflow Sites

This example demonstrates how to create and manage Webflow sites using Pulumi.

Required inputs: workspace_id (Enterprise workspace) and display_name.
`short_name` and `time_zone` are read-only outputs generated by Webflow.
"""

# Example 1: Basic Site Creation
basic_site = webflow.Site("basic-site",
    workspace_id=workspace_id,
    display_name=display_name)

# Example 2: Multi-Environment Site Configuration
environments = ["development", "staging", "production"]
environment_sites = []
for env in environments:
    site = webflow.Site(f"site-{env}",
        workspace_id=workspace_id,
        display_name=f"{display_name}-{env}")
    environment_sites.append(site)

# Example 3: Site with Optional Configuration
configured_site = webflow.Site("configured-site",
    workspace_id=workspace_id,
    display_name=f"{display_name}-configured",
    # Optional: organize the site in a workspace folder
    parent_folder_id=config.get("parentFolderId"),
    # Optional and IMMUTABLE: changing it later replaces (deletes + recreates) the site
    template_name=config.get("templateName"),
    # Publish after every create/update once you run `pulumi config set publish true`.
    # With publish_to_webflow_subdomain the site goes to its webflow.io subdomain;
    # add custom domain IDs with publish_custom_domains, or publish a single page
    # with publish_page_id. Leave publish off until the site is ready to go live.
    publish=config.get_bool("publish") or False,
    publish_to_webflow_subdomain=True)
    # publish_custom_domains=["your-custom-domain-id"],  # domain IDs, not host names
    # publish_page_id="your-page-id",  # publish only this page instead of the whole site

# Export values
pulumi.export("basic_site_id", basic_site.id)
pulumi.export("basic_site_name", basic_site.display_name)
# short_name and time_zone are generated by Webflow and available as outputs
pulumi.export("basic_site_short_name", basic_site.short_name)
pulumi.export("basic_site_time_zone", basic_site.time_zone)
pulumi.export("environment_site_ids", [s.id for s in environment_sites])
pulumi.export("configured_site_id", configured_site.id)
# publish_scope reports what the last provider-initiated publish targeted
# (the webflow.io subdomain, custom domains, or a single page)
pulumi.export("configured_site_publish_scope", configured_site.publish_scope)
pulumi.export("configured_site_last_published", configured_site.last_published)

# Print success message
site_count = len(environment_sites) + 2
print(f"✅ Successfully created {site_count} sites")
