import pulumi
import pulumi_webflow as webflow

# Create a Pulumi config object
config = pulumi.Config()

# Get configuration values
workspace_id = config.require("workspaceId")
display_name = config.require("displayName")

"""
Site Example - Creating and Managing Webflow Sites

This example demonstrates how to create and manage Webflow sites using Pulumi.

Required inputs: workspace_id (Enterprise workspace) and display_name.
`short_name` and `time_zone` are read-only outputs generated by Webflow.
"""

# Example 1: Basic Site Creation
basic_site = webflow.Site("basic-site",
    workspace_id=workspace_id,
    display_name=display_name)

# Example 2: Multi-Environment Site Configuration
environments = ["development", "staging", "production"]
environment_sites = []
for env in environments:
    site = webflow.Site(f"site-{env}",
        workspace_id=workspace_id,
        display_name=f"{display_name}-{env}")
    environment_sites.append(site)

# Example 3: Site with Optional Configuration
configured_site = webflow.Site("configured-site",
    workspace_id=workspace_id,
    display_name=f"{display_name}-configured",
    # Optional: organize the site in a workspace folder
    parent_folder_id=config.get("parentFolderId"),
    # Optional and IMMUTABLE: changing it later replaces (deletes + recreates) the site
    template_name=config.get("templateName"),
    # Do not auto-publish; enable after the first manual publish in the Designer
    publish=False)

# Export values
pulumi.export("basic_site_id", basic_site.id)
pulumi.export("basic_site_name", basic_site.display_name)
# short_name and time_zone are generated by Webflow and available as outputs
pulumi.export("basic_site_short_name", basic_site.short_name)
pulumi.export("basic_site_time_zone", basic_site.time_zone)
pulumi.export("environment_site_ids", [s.id for s in environment_sites])
pulumi.export("configured_site_id", configured_site.id)

# Print success message
site_count = len(environment_sites) + 2
print(f"✅ Successfully created {site_count} sites")
