// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow
{
    /// <summary>
    /// Manages CMS collection items for a Webflow collection. Collection items represent individual content entries (blog posts, products, etc.) within a CMS collection. Each item has dynamic field data based on the collection schema. Items are created and updated in staging; set live=true to publish them to the live site as part of every create and update.
    /// </summary>
    [WebflowResourceType("webflow:index:CollectionItem")]
    public partial class CollectionItem : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The CMS locale ID for localized sites (optional). Only required if your site uses Webflow's localization features; it is sent with every request for this item, including reads. Leave empty for non-localized sites.
        /// </summary>
        [Output("cmsLocaleId")]
        public Output<string?> CmsLocaleId { get; private set; } = null!;

        /// <summary>
        /// The Webflow collection ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
        /// </summary>
        [Output("collectionId")]
        public Output<string> CollectionId { get; private set; } = null!;

        /// <summary>
        /// The timestamp when the item was created (RFC3339 format, read-only). This is automatically set by Webflow and is immutable.
        /// </summary>
        [Output("createdOn")]
        public Output<string?> CreatedOn { get; private set; } = null!;

        /// <summary>
        /// A map of field slugs to values for the collection item. The field slugs must match the fields defined in the collection schema. Common fields include 'name' (required), 'slug' (required, URL-friendly), and any custom fields you've added to the collection. Only the fields listed here are managed; other fields of the item are left untouched. Example: {"name": "My Blog Post", "slug": "my-blog-post", "content": "Post content..."}
        /// </summary>
        [Output("fieldData")]
        public Output<ImmutableDictionary<string, object>> FieldData { get; private set; } = null!;

        /// <summary>
        /// Whether the item is archived (optional). Archived items are not visible on the published site but remain in the CMS. When omitted, the archived state is not managed and never causes a diff.
        /// </summary>
        [Output("isArchived")]
        public Output<bool?> IsArchived { get; private set; } = null!;

        /// <summary>
        /// Whether the item is a draft (optional; Webflow defaults new items to true). Setting isDraft to false stages the item to go out with the next site publish - it does not publish the item by itself. Use live=true to publish the item immediately. When omitted, the draft state is not managed and never causes a diff.
        /// </summary>
        [Output("isDraft")]
        public Output<bool?> IsDraft { get; private set; } = null!;

        /// <summary>
        /// The Webflow-assigned item ID (read-only). This is automatically set by Webflow when the item is created.
        /// </summary>
        [Output("itemId")]
        public Output<string?> ItemId { get; private set; } = null!;

        /// <summary>
        /// The timestamp when the item was last published (RFC3339 format, read-only). This is automatically updated by Webflow when the item is published.
        /// </summary>
        [Output("lastPublished")]
        public Output<string?> LastPublished { get; private set; } = null!;

        /// <summary>
        /// The timestamp when the item was last updated (RFC3339 format, read-only). This is automatically updated by Webflow whenever the item is modified.
        /// </summary>
        [Output("lastUpdated")]
        public Output<string?> LastUpdated { get; private set; } = null!;

        /// <summary>
        /// Publish the item to the live site after every create and update (optional, defaults to false). When true the provider calls the Webflow publish-items endpoint after writing the item and reads the item back from the live endpoint, so lastPublished reflects the live copy. Setting this back to false stops publishing future changes but does not unpublish the item.
        /// </summary>
        [Output("live")]
        public Output<bool?> Live { get; private set; } = null!;


        /// <summary>
        /// Create a CollectionItem resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CollectionItem(string name, CollectionItemArgs args, CustomResourceOptions? options = null)
            : base("webflow:index:CollectionItem", name, args ?? new CollectionItemArgs(), MakeResourceOptions(options, ""))
        {
        }

        private CollectionItem(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("webflow:index:CollectionItem", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/JDetmar/pulumi-webflow",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing CollectionItem resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static CollectionItem Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new CollectionItem(name, id, options);
        }
    }

    public sealed class CollectionItemArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The CMS locale ID for localized sites (optional). Only required if your site uses Webflow's localization features; it is sent with every request for this item, including reads. Leave empty for non-localized sites.
        /// </summary>
        [Input("cmsLocaleId")]
        public Input<string>? CmsLocaleId { get; set; }

        /// <summary>
        /// The Webflow collection ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find collection IDs via the Webflow API or dashboard. This field will be validated before making any API calls.
        /// </summary>
        [Input("collectionId", required: true)]
        public Input<string> CollectionId { get; set; } = null!;

        [Input("fieldData", required: true)]
        private InputMap<object>? _fieldData;

        /// <summary>
        /// A map of field slugs to values for the collection item. The field slugs must match the fields defined in the collection schema. Common fields include 'name' (required), 'slug' (required, URL-friendly), and any custom fields you've added to the collection. Only the fields listed here are managed; other fields of the item are left untouched. Example: {"name": "My Blog Post", "slug": "my-blog-post", "content": "Post content..."}
        /// </summary>
        public InputMap<object> FieldData
        {
            get => _fieldData ?? (_fieldData = new InputMap<object>());
            set => _fieldData = value;
        }

        /// <summary>
        /// Whether the item is archived (optional). Archived items are not visible on the published site but remain in the CMS. When omitted, the archived state is not managed and never causes a diff.
        /// </summary>
        [Input("isArchived")]
        public Input<bool>? IsArchived { get; set; }

        /// <summary>
        /// Whether the item is a draft (optional; Webflow defaults new items to true). Setting isDraft to false stages the item to go out with the next site publish - it does not publish the item by itself. Use live=true to publish the item immediately. When omitted, the draft state is not managed and never causes a diff.
        /// </summary>
        [Input("isDraft")]
        public Input<bool>? IsDraft { get; set; }

        /// <summary>
        /// Publish the item to the live site after every create and update (optional, defaults to false). When true the provider calls the Webflow publish-items endpoint after writing the item and reads the item back from the live endpoint, so lastPublished reflects the live copy. Setting this back to false stops publishing future changes but does not unpublish the item.
        /// </summary>
        [Input("live")]
        public Input<bool>? Live { get; set; }

        public CollectionItemArgs()
        {
        }
        public static new CollectionItemArgs Empty => new CollectionItemArgs();
    }
}
