// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow
{
    public static class GetAnalyticsTimeOnPage
    {
        /// <summary>
        /// Returns the average time visitors spend on a page of a Webflow site, as a single value or bucketed by day or week (Analyze API, beta). Use the 'pagePath' filter to target one page. Requires the 'sites:read' scope and a Webflow workspace with the Analyze add-on. Webflow allows one Analyze request in flight per access token; concurrent requests are retried. The reporting window must start on or after 2025-04-09 and span at most 100 days.
        /// </summary>
        public static Task<GetAnalyticsTimeOnPageResult> InvokeAsync(GetAnalyticsTimeOnPageArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAnalyticsTimeOnPageResult>("webflow:index:getAnalyticsTimeOnPage", args ?? new GetAnalyticsTimeOnPageArgs(), options.WithDefaults());

        /// <summary>
        /// Returns the average time visitors spend on a page of a Webflow site, as a single value or bucketed by day or week (Analyze API, beta). Use the 'pagePath' filter to target one page. Requires the 'sites:read' scope and a Webflow workspace with the Analyze add-on. Webflow allows one Analyze request in flight per access token; concurrent requests are retried. The reporting window must start on or after 2025-04-09 and span at most 100 days.
        /// </summary>
        public static Output<GetAnalyticsTimeOnPageResult> Invoke(GetAnalyticsTimeOnPageInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAnalyticsTimeOnPageResult>("webflow:index:getAnalyticsTimeOnPage", args ?? new GetAnalyticsTimeOnPageInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Returns the average time visitors spend on a page of a Webflow site, as a single value or bucketed by day or week (Analyze API, beta). Use the 'pagePath' filter to target one page. Requires the 'sites:read' scope and a Webflow workspace with the Analyze add-on. Webflow allows one Analyze request in flight per access token; concurrent requests are retried. The reporting window must start on or after 2025-04-09 and span at most 100 days.
        /// </summary>
        public static Output<GetAnalyticsTimeOnPageResult> Invoke(GetAnalyticsTimeOnPageInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAnalyticsTimeOnPageResult>("webflow:index:getAnalyticsTimeOnPage", args ?? new GetAnalyticsTimeOnPageInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAnalyticsTimeOnPageArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Restrict the report to a single browser name (e.g., 'Chrome').
        /// </summary>
        [Input("browser")]
        public string? Browser { get; set; }

        /// <summary>
        /// Restrict the report to a single country, as an ISO 3166-1 alpha-2 code (e.g., 'US'). Normalized to uppercase.
        /// </summary>
        [Input("country")]
        public string? Country { get; set; }

        /// <summary>
        /// Restrict the report to a single device type: 'desktop', 'mobile' or 'tablet'.
        /// </summary>
        [Input("deviceType")]
        public string? DeviceType { get; set; }

        /// <summary>
        /// Exclusive end of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be after startTime and within 100 days of it.
        /// </summary>
        [Input("endTime", required: true)]
        public string EndTime { get; set; } = null!;

        [Input("filters")]
        private Dictionary<string, Inputs.AnalyticsDimensionFilter>? _filters;

        /// <summary>
        /// Advanced filters keyed by dimension (e.g., 'country', 'deviceType', 'pagePath', 'referrer', 'trafficSource', 'utmCampaign', 'os', 'language', 'locale', 'region', 'audienceIds', 'collectionId', 'itemSlug', 'pageId', 'dayOfWeek', 'timeOfDay', 'visitStatus', ...). Each entry supports 'eq', 'in', 'ne' and 'nin'. Filter a given dimension either here or with the matching single-value input, not both.
        /// </summary>
        public Dictionary<string, Inputs.AnalyticsDimensionFilter> Filters
        {
            get => _filters ?? (_filters = new Dictionary<string, Inputs.AnalyticsDimensionFilter>());
            set => _filters = value;
        }

        /// <summary>
        /// How the average is computed: per 'session', per 'user' or per 'pageview'.
        /// </summary>
        [Input("metricScope", required: true)]
        public string MetricScope { get; set; } = null!;

        /// <summary>
        /// Restrict the report to a single page path (e.g., '/pricing').
        /// </summary>
        [Input("pagePath")]
        public string? PagePath { get; set; }

        /// <summary>
        /// Restrict the report to a single referrer domain (e.g., 'google.com').
        /// </summary>
        [Input("referrer")]
        public string? Referrer { get; set; }

        /// <summary>
        /// The Webflow site ID (24-character lowercase hexadecimal string).
        /// </summary>
        [Input("siteId", required: true)]
        public string SiteId { get; set; } = null!;

        /// <summary>
        /// Inclusive start of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be on or after 2025-04-09T00:00:00Z.
        /// </summary>
        [Input("startTime", required: true)]
        public string StartTime { get; set; } = null!;

        /// <summary>
        /// Include bucketed averages using the given granularity ('day' or 'week') and IANA time zone. Omit to return a single aggregate value for the window.
        /// </summary>
        [Input("timeseries")]
        public Inputs.AnalyticsTimeOnPageTimeseriesArgs? Timeseries { get; set; }

        /// <summary>
        /// Restrict the report to a single traffic source code (e.g., 'SO' for Organic Search).
        /// </summary>
        [Input("trafficSource")]
        public string? TrafficSource { get; set; }

        /// <summary>
        /// Restrict the report to a single utm_campaign value.
        /// </summary>
        [Input("utmCampaign")]
        public string? UtmCampaign { get; set; }

        /// <summary>
        /// Restrict the report to a single utm_medium value.
        /// </summary>
        [Input("utmMedium")]
        public string? UtmMedium { get; set; }

        /// <summary>
        /// Restrict the report to a single utm_source value.
        /// </summary>
        [Input("utmSource")]
        public string? UtmSource { get; set; }

        public GetAnalyticsTimeOnPageArgs()
        {
        }
        public static new GetAnalyticsTimeOnPageArgs Empty => new GetAnalyticsTimeOnPageArgs();
    }

    public sealed class GetAnalyticsTimeOnPageInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Restrict the report to a single browser name (e.g., 'Chrome').
        /// </summary>
        [Input("browser")]
        public Input<string>? Browser { get; set; }

        /// <summary>
        /// Restrict the report to a single country, as an ISO 3166-1 alpha-2 code (e.g., 'US'). Normalized to uppercase.
        /// </summary>
        [Input("country")]
        public Input<string>? Country { get; set; }

        /// <summary>
        /// Restrict the report to a single device type: 'desktop', 'mobile' or 'tablet'.
        /// </summary>
        [Input("deviceType")]
        public Input<string>? DeviceType { get; set; }

        /// <summary>
        /// Exclusive end of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be after startTime and within 100 days of it.
        /// </summary>
        [Input("endTime", required: true)]
        public Input<string> EndTime { get; set; } = null!;

        [Input("filters")]
        private InputMap<Inputs.AnalyticsDimensionFilterArgs>? _filters;

        /// <summary>
        /// Advanced filters keyed by dimension (e.g., 'country', 'deviceType', 'pagePath', 'referrer', 'trafficSource', 'utmCampaign', 'os', 'language', 'locale', 'region', 'audienceIds', 'collectionId', 'itemSlug', 'pageId', 'dayOfWeek', 'timeOfDay', 'visitStatus', ...). Each entry supports 'eq', 'in', 'ne' and 'nin'. Filter a given dimension either here or with the matching single-value input, not both.
        /// </summary>
        public InputMap<Inputs.AnalyticsDimensionFilterArgs> Filters
        {
            get => _filters ?? (_filters = new InputMap<Inputs.AnalyticsDimensionFilterArgs>());
            set => _filters = value;
        }

        /// <summary>
        /// How the average is computed: per 'session', per 'user' or per 'pageview'.
        /// </summary>
        [Input("metricScope", required: true)]
        public Input<string> MetricScope { get; set; } = null!;

        /// <summary>
        /// Restrict the report to a single page path (e.g., '/pricing').
        /// </summary>
        [Input("pagePath")]
        public Input<string>? PagePath { get; set; }

        /// <summary>
        /// Restrict the report to a single referrer domain (e.g., 'google.com').
        /// </summary>
        [Input("referrer")]
        public Input<string>? Referrer { get; set; }

        /// <summary>
        /// The Webflow site ID (24-character lowercase hexadecimal string).
        /// </summary>
        [Input("siteId", required: true)]
        public Input<string> SiteId { get; set; } = null!;

        /// <summary>
        /// Inclusive start of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be on or after 2025-04-09T00:00:00Z.
        /// </summary>
        [Input("startTime", required: true)]
        public Input<string> StartTime { get; set; } = null!;

        /// <summary>
        /// Include bucketed averages using the given granularity ('day' or 'week') and IANA time zone. Omit to return a single aggregate value for the window.
        /// </summary>
        [Input("timeseries")]
        public Input<Inputs.AnalyticsTimeOnPageTimeseriesArgsArgs>? Timeseries { get; set; }

        /// <summary>
        /// Restrict the report to a single traffic source code (e.g., 'SO' for Organic Search).
        /// </summary>
        [Input("trafficSource")]
        public Input<string>? TrafficSource { get; set; }

        /// <summary>
        /// Restrict the report to a single utm_campaign value.
        /// </summary>
        [Input("utmCampaign")]
        public Input<string>? UtmCampaign { get; set; }

        /// <summary>
        /// Restrict the report to a single utm_medium value.
        /// </summary>
        [Input("utmMedium")]
        public Input<string>? UtmMedium { get; set; }

        /// <summary>
        /// Restrict the report to a single utm_source value.
        /// </summary>
        [Input("utmSource")]
        public Input<string>? UtmSource { get; set; }

        public GetAnalyticsTimeOnPageInvokeArgs()
        {
        }
        public static new GetAnalyticsTimeOnPageInvokeArgs Empty => new GetAnalyticsTimeOnPageInvokeArgs();
    }


    [OutputType]
    public sealed class GetAnalyticsTimeOnPageResult
    {
        /// <summary>
        /// The bucketing applied; present only when 'timeseries' was requested.
        /// </summary>
        public readonly Outputs.AnalyticsBucketing? Bucketing;
        /// <summary>
        /// A single aggregate data point, or one point per bucket when 'timeseries' was requested.
        /// </summary>
        public readonly ImmutableArray<Outputs.AnalyticsAverageSecondsPoint> Data;
        /// <summary>
        /// The filters that were applied, keyed by dimension.
        /// </summary>
        public readonly ImmutableDictionary<string, Outputs.AnalyticsDimensionFilter>? Filters;
        /// <summary>
        /// How the average was computed: 'session', 'user' or 'pageview'.
        /// </summary>
        public readonly string MetricScope;
        /// <summary>
        /// The report name, always 'time_on_page'.
        /// </summary>
        public readonly string Report;
        /// <summary>
        /// The reporting window that was applied.
        /// </summary>
        public readonly Outputs.AnalyticsWindow Window;

        [OutputConstructor]
        private GetAnalyticsTimeOnPageResult(
            Outputs.AnalyticsBucketing? bucketing,

            ImmutableArray<Outputs.AnalyticsAverageSecondsPoint> data,

            ImmutableDictionary<string, Outputs.AnalyticsDimensionFilter>? filters,

            string metricScope,

            string report,

            Outputs.AnalyticsWindow window)
        {
            Bucketing = bucketing;
            Data = data;
            Filters = filters;
            MetricScope = metricScope;
            Report = report;
            Window = window;
        }
    }
}
