// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow
{
    /// <summary>
    /// Manages the static text content of a Webflow page in a secondary locale (POST /v2/pages/{page_id}/dom?localeId=...). Webflow's Update Page Content endpoint only edits secondary locales: localeId is required and must be a valid secondary locale of the site, and the primary locale's content cannot be changed via the API. This resource updates the HTML of existing text nodes; it does NOT manage page structure or layout. Find node IDs by fetching the page DOM (GET /v2/pages/{page_id}/dom?localeId=...). Each node's text is required, and its HTML tags must match the node's current content; an empty text does not clear a node and is rejected. At most 1000 nodes may be updated per resource. Webflow reports per-node failures in the response; the update fails if any node was rejected. Refresh reads the current text of the managed nodes from the page DOM, so content changed outside of Pulumi shows up as drift. Import with the ID {pageId}/content/{localeId} to adopt every text node of the page. Destroying the resource leaves the content in place.
    /// </summary>
    [WebflowResourceType("webflow:index:PageContent")]
    public partial class PageContent : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The ID of the secondary locale to update (24-character lowercase hexadecimal string). Required: the Update Page Content endpoint only edits secondary locales, and Webflow rejects the request when the locale is the primary locale or not a locale of the site. Locale IDs are listed under Site Settings &gt; Localization or via the Get Site endpoint. Changing it replaces the resource.
        /// </summary>
        [Output("localeId")]
        public Output<string> LocaleId { get; private set; } = null!;

        /// <summary>
        /// List of node content updates to apply (1 to 1000 entries). Each entry names a nodeId from the page's DOM and the node's new HTML text. Node IDs must be unique within the list.
        /// </summary>
        [Output("nodes")]
        public Output<ImmutableArray<Outputs.NodeContentUpdate>> Nodes { get; private set; } = null!;

        /// <summary>
        /// The Webflow page ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). Use the getPages function to find page IDs. Changing it replaces the resource.
        /// </summary>
        [Output("pageId")]
        public Output<string> PageId { get; private set; } = null!;


        /// <summary>
        /// Create a PageContent resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PageContent(string name, PageContentArgs args, CustomResourceOptions? options = null)
            : base("webflow:index:PageContent", name, args ?? new PageContentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PageContent(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("webflow:index:PageContent", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/JDetmar/pulumi-webflow",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PageContent resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PageContent Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new PageContent(name, id, options);
        }
    }

    public sealed class PageContentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the secondary locale to update (24-character lowercase hexadecimal string). Required: the Update Page Content endpoint only edits secondary locales, and Webflow rejects the request when the locale is the primary locale or not a locale of the site. Locale IDs are listed under Site Settings &gt; Localization or via the Get Site endpoint. Changing it replaces the resource.
        /// </summary>
        [Input("localeId", required: true)]
        public Input<string> LocaleId { get; set; } = null!;

        [Input("nodes", required: true)]
        private InputList<Inputs.NodeContentUpdateArgs>? _nodes;

        /// <summary>
        /// List of node content updates to apply (1 to 1000 entries). Each entry names a nodeId from the page's DOM and the node's new HTML text. Node IDs must be unique within the list.
        /// </summary>
        public InputList<Inputs.NodeContentUpdateArgs> Nodes
        {
            get => _nodes ?? (_nodes = new InputList<Inputs.NodeContentUpdateArgs>());
            set => _nodes = value;
        }

        /// <summary>
        /// The Webflow page ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). Use the getPages function to find page IDs. Changing it replaces the resource.
        /// </summary>
        [Input("pageId", required: true)]
        public Input<string> PageId { get; set; } = null!;

        public PageContentArgs()
        {
        }
        public static new PageContentArgs Empty => new PageContentArgs();
    }
}
