// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow
{
    /// <summary>
    /// Manages the JSON-LD schema markup (structured data) of a Webflow page, optionally for a specific secondary locale, using the Pages schema markup API (beta). Creating or updating the resource PUTs the markup; deleting it clears the markup by writing null, since Webflow has no delete endpoint for schema markup. The markup is supplied as a JSON string and compared semantically, so key order and whitespace differences never cause a diff. Requires the 'pages:read' and 'pages:write' scopes. Webflow limits each entry to 60KB, 32 levels of nesting and 5,000 nodes, and silently strips the keys '__proto__', 'constructor' and 'prototype'.
    /// </summary>
    [WebflowResourceType("webflow:index:PageSchemaMarkup")]
    public partial class PageSchemaMarkup : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The locale whose markup Webflow reports for this page. Differs from 'localeId' when a secondary locale falls back to the primary locale. Read-only.
        /// </summary>
        [Output("effectiveLocaleId")]
        public Output<string?> EffectiveLocaleId { get; private set; } = null!;

        /// <summary>
        /// True when the targeted secondary locale has no schema markup of its own and Webflow serves the primary locale's markup instead. Always false for the primary locale. Read-only.
        /// </summary>
        [Output("isInherited")]
        public Output<bool> IsInherited { get; private set; } = null!;

        /// <summary>
        /// The timestamp of the most recent update to the markup (RFC3339). Read-only.
        /// </summary>
        [Output("lastUpdated")]
        public Output<string?> LastUpdated { get; private set; } = null!;

        /// <summary>
        /// Optional secondary locale ID (24-character lowercase hexadecimal string) to manage the markup of a localized version of the page. Omit to manage the primary locale. Changing this value replaces the resource.
        /// </summary>
        [Output("localeId")]
        public Output<string?> LocaleId { get; private set; } = null!;

        /// <summary>
        /// The Webflow page ID (24-character lowercase hexadecimal string, e.g., '6596da6045e56dee495bcbba'). Changing this value replaces the resource.
        /// </summary>
        [Output("pageId")]
        public Output<string> PageId { get; private set; } = null!;

        /// <summary>
        /// The relative published URL path of the page (e.g., '/about'). Read-only.
        /// </summary>
        [Output("publishedPath")]
        public Output<string?> PublishedPath { get; private set; } = null!;

        /// <summary>
        /// The JSON-LD document as a JSON string, e.g. '{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[...]}'. Must be a single JSON object (use '@graph' to publish several entities). Use JSON.stringify / json.dumps / JsonSerializer to serialize an object from your program. Compared semantically, so formatting and key order do not cause diffs.
        /// </summary>
        [Output("schemaMarkup")]
        public Output<string> SchemaMarkup { get; private set; } = null!;

        /// <summary>
        /// The ID of the Webflow site containing the page. Read-only.
        /// </summary>
        [Output("siteId")]
        public Output<string?> SiteId { get; private set; } = null!;


        /// <summary>
        /// Create a PageSchemaMarkup resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PageSchemaMarkup(string name, PageSchemaMarkupArgs args, CustomResourceOptions? options = null)
            : base("webflow:index:PageSchemaMarkup", name, args ?? new PageSchemaMarkupArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PageSchemaMarkup(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("webflow:index:PageSchemaMarkup", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/JDetmar/pulumi-webflow",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PageSchemaMarkup resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PageSchemaMarkup Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new PageSchemaMarkup(name, id, options);
        }
    }

    public sealed class PageSchemaMarkupArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Optional secondary locale ID (24-character lowercase hexadecimal string) to manage the markup of a localized version of the page. Omit to manage the primary locale. Changing this value replaces the resource.
        /// </summary>
        [Input("localeId")]
        public Input<string>? LocaleId { get; set; }

        /// <summary>
        /// The Webflow page ID (24-character lowercase hexadecimal string, e.g., '6596da6045e56dee495bcbba'). Changing this value replaces the resource.
        /// </summary>
        [Input("pageId", required: true)]
        public Input<string> PageId { get; set; } = null!;

        /// <summary>
        /// The JSON-LD document as a JSON string, e.g. '{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[...]}'. Must be a single JSON object (use '@graph' to publish several entities). Use JSON.stringify / json.dumps / JsonSerializer to serialize an object from your program. Compared semantically, so formatting and key order do not cause diffs.
        /// </summary>
        [Input("schemaMarkup", required: true)]
        public Input<string> SchemaMarkup { get; set; } = null!;

        public PageSchemaMarkupArgs()
        {
        }
        public static new PageSchemaMarkupArgs Empty => new PageSchemaMarkupArgs();
    }
}
