// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow
{
    /// <summary>
    /// Manages HTTP redirects for a Webflow site (POST/PATCH/DELETE /v2/sites/{site_id}/redirects, scope sites:write; GET requires sites:read). Webflow redirects are always permanent (301) redirects from one site path to another; the API does not support other status codes. Changing `sourcePath` replaces the redirect; changing `destinationPath` updates it in place.
    /// </summary>
    [WebflowResourceType("webflow:index:Redirect")]
    public partial class Redirect : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The timestamp when the redirect was created (RFC3339 format), if the Webflow API reports it. The redirects API does not document this field, so it is normally empty. Read-only.
        /// </summary>
        [Output("createdOn")]
        public Output<string?> CreatedOn { get; private set; } = null!;

        /// <summary>
        /// The URL path to redirect to (e.g., '/new-page', '/home'). Must start with '/' and contain only valid URL characters. This is the location where users will be redirected when they visit the source path. Changing this value updates the redirect in place.
        /// </summary>
        [Output("destinationPath")]
        public Output<string> DestinationPath { get; private set; } = null!;

        /// <summary>
        /// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
        /// </summary>
        [Output("siteId")]
        public Output<string> SiteId { get; private set; } = null!;

        /// <summary>
        /// The URL path to redirect from (e.g., '/old-page', '/blog/2023'). Must start with '/' and contain only valid URL characters (letters, numbers, hyphens, underscores, slashes, dots). Query strings and fragments are not allowed in the source path. Changing this value replaces the redirect.
        /// </summary>
        [Output("sourcePath")]
        public Output<string> SourcePath { get; private set; } = null!;

        /// <summary>
        /// Deprecated and ignored. Webflow redirects are always 301 (permanent) redirects: the redirect API object is {id, fromUrl, toUrl} and has no status code, so this value is never sent to Webflow, never validated and never produces a diff. Remove it from your program; it only remains for backwards compatibility.
        /// </summary>
        [Output("statusCode")]
        public Output<int?> StatusCode { get; private set; } = null!;


        /// <summary>
        /// Create a Redirect resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Redirect(string name, RedirectArgs args, CustomResourceOptions? options = null)
            : base("webflow:index:Redirect", name, args ?? new RedirectArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Redirect(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("webflow:index:Redirect", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/JDetmar/pulumi-webflow",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Redirect resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Redirect Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Redirect(name, id, options);
        }
    }

    public sealed class RedirectArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The URL path to redirect to (e.g., '/new-page', '/home'). Must start with '/' and contain only valid URL characters. This is the location where users will be redirected when they visit the source path. Changing this value updates the redirect in place.
        /// </summary>
        [Input("destinationPath", required: true)]
        public Input<string> DestinationPath { get; set; } = null!;

        /// <summary>
        /// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
        /// </summary>
        [Input("siteId", required: true)]
        public Input<string> SiteId { get; set; } = null!;

        /// <summary>
        /// The URL path to redirect from (e.g., '/old-page', '/blog/2023'). Must start with '/' and contain only valid URL characters (letters, numbers, hyphens, underscores, slashes, dots). Query strings and fragments are not allowed in the source path. Changing this value replaces the redirect.
        /// </summary>
        [Input("sourcePath", required: true)]
        public Input<string> SourcePath { get; set; } = null!;

        /// <summary>
        /// Deprecated and ignored. Webflow redirects are always 301 (permanent) redirects: the redirect API object is {id, fromUrl, toUrl} and has no status code, so this value is never sent to Webflow, never validated and never produces a diff. Remove it from your program; it only remains for backwards compatibility.
        /// </summary>
        [Input("statusCode")]
        public Input<int>? StatusCode { get; set; }

        public RedirectArgs()
        {
        }
        public static new RedirectArgs Empty => new RedirectArgs();
    }
}
