// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow
{
    /// <summary>
    /// Registers an externally hosted script in a Webflow site's script registry (POST /v2/sites/{site_id}/registered_scripts/hosted). Registered scripts are applied to a site or page with the SiteCustomCode and PageCustomCode resources. scriptVersion is required: the register endpoint rejects requests without one.
    /// 
    /// **Authentication:** this resource calls Webflow custom code endpoints, which require an OAuth Data Client app token with the `custom_code:read` and `custom_code:write` scopes. Webflow documents that these scopes are available only to Data Client apps: site API tokens cannot access custom code endpoints.
    /// 
    /// **IMPORTANT LIMITATION:** Webflow has no endpoint to update or unregister a registered script. Registrations are versioned and permanent (a site can hold up to 800). Changing displayName, hostedLocation, integrityHash, scriptVersion or canCopy therefore registers a new script (a new version when only scriptVersion changes) and the previous registration remains in the registry. Destroying the resource is a logged no-op: the script stays registered and Pulumi simply stops managing it. Applied code is removed by SiteCustomCode and PageCustomCode.
    /// </summary>
    [WebflowResourceType("webflow:index:RegisteredScript")]
    public partial class RegisteredScript : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Indicates whether the script can be copied when the site is duplicated. Default: false. When true, the script will be included when creating a copy of the site.
        /// </summary>
        [Output("canCopy")]
        public Output<bool?> CanCopy { get; private set; } = null!;

        /// <summary>
        /// The timestamp when the script was created (RFC3339 format). This is automatically set by Webflow when the script is created and is read-only.
        /// </summary>
        [Output("createdOn")]
        public Output<string?> CreatedOn { get; private set; } = null!;

        /// <summary>
        /// The user-facing name for the script (1-50 characters: letters, digits and spaces). This name is used to identify the script in the Webflow interface and derives the scriptId. Changing it registers a new script; the previous registration remains. Example valid names: 'CMS Slider', 'AnalyticsScript', 'MyCustomScript123'.
        /// </summary>
        [Output("displayName")]
        public Output<string> DisplayName { get; private set; } = null!;

        /// <summary>
        /// The URI for the externally hosted script (e.g., 'https://cdn.example.com/my-script.js'). Must be a valid HTTP or HTTPS URL. The script should be publicly accessible and properly configured for cross-origin requests.
        /// </summary>
        [Output("hostedLocation")]
        public Output<string> HostedLocation { get; private set; } = null!;

        /// <summary>
        /// The Sub-Resource Integrity (SRI) hash for the script. Format: 'sha384-&lt;hash&gt;', 'sha256-&lt;hash&gt;', or 'sha512-&lt;hash&gt;'. SRI hashes help ensure that the script hasn't been modified in transit. You can generate an SRI hash using https://www.srihash.org/
        /// </summary>
        [Output("integrityHash")]
        public Output<string> IntegrityHash { get; private set; } = null!;

        /// <summary>
        /// The timestamp when the script was last updated (RFC3339 format). This is automatically updated by Webflow when the script is modified and is read-only.
        /// </summary>
        [Output("lastUpdated")]
        public Output<string?> LastUpdated { get; private set; } = null!;

        /// <summary>
        /// The Webflow-assigned script ID (read-only). This is typically the lowercase version of displayName. Use this value when referencing the script in SiteCustomCode or PageCustomCode resources.
        /// </summary>
        [Output("scriptId")]
        public Output<string> ScriptId { get; private set; } = null!;

        /// <summary>
        /// The Semantic Version (SemVer) string for the script (e.g., '1.0.0', '2.3.1'). Required by the Webflow register endpoint. Registered scripts are versioned: changing this value registers a new version of the script and the previous version remains registered. See https://semver.org/ for more information on semantic versioning.
        /// </summary>
        [Output("scriptVersion")]
        public Output<string> ScriptVersion { get; private set; } = null!;

        /// <summary>
        /// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
        /// </summary>
        [Output("siteId")]
        public Output<string> SiteId { get; private set; } = null!;


        /// <summary>
        /// Create a RegisteredScript resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RegisteredScript(string name, RegisteredScriptArgs args, CustomResourceOptions? options = null)
            : base("webflow:index:RegisteredScript", name, args ?? new RegisteredScriptArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RegisteredScript(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("webflow:index:RegisteredScript", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/JDetmar/pulumi-webflow",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RegisteredScript resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RegisteredScript Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new RegisteredScript(name, id, options);
        }
    }

    public sealed class RegisteredScriptArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Indicates whether the script can be copied when the site is duplicated. Default: false. When true, the script will be included when creating a copy of the site.
        /// </summary>
        [Input("canCopy")]
        public Input<bool>? CanCopy { get; set; }

        /// <summary>
        /// The user-facing name for the script (1-50 characters: letters, digits and spaces). This name is used to identify the script in the Webflow interface and derives the scriptId. Changing it registers a new script; the previous registration remains. Example valid names: 'CMS Slider', 'AnalyticsScript', 'MyCustomScript123'.
        /// </summary>
        [Input("displayName", required: true)]
        public Input<string> DisplayName { get; set; } = null!;

        /// <summary>
        /// The URI for the externally hosted script (e.g., 'https://cdn.example.com/my-script.js'). Must be a valid HTTP or HTTPS URL. The script should be publicly accessible and properly configured for cross-origin requests.
        /// </summary>
        [Input("hostedLocation", required: true)]
        public Input<string> HostedLocation { get; set; } = null!;

        /// <summary>
        /// The Sub-Resource Integrity (SRI) hash for the script. Format: 'sha384-&lt;hash&gt;', 'sha256-&lt;hash&gt;', or 'sha512-&lt;hash&gt;'. SRI hashes help ensure that the script hasn't been modified in transit. You can generate an SRI hash using https://www.srihash.org/
        /// </summary>
        [Input("integrityHash", required: true)]
        public Input<string> IntegrityHash { get; set; } = null!;

        /// <summary>
        /// The Semantic Version (SemVer) string for the script (e.g., '1.0.0', '2.3.1'). Required by the Webflow register endpoint. Registered scripts are versioned: changing this value registers a new version of the script and the previous version remains registered. See https://semver.org/ for more information on semantic versioning.
        /// </summary>
        [Input("scriptVersion", required: true)]
        public Input<string> ScriptVersion { get; set; } = null!;

        /// <summary>
        /// The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
        /// </summary>
        [Input("siteId", required: true)]
        public Input<string> SiteId { get; set; } = null!;

        public RegisteredScriptArgs()
        {
        }
        public static new RegisteredScriptArgs Empty => new RegisteredScriptArgs();
    }
}
