// Copyright 2025, Justin Detmar.
// SPDX-License-Identifier: MIT
//
// This is an unofficial, community-maintained Pulumi provider for Webflow.
// Not affiliated with, endorsed by, or supported by Pulumi Corporation or Webflow, Inc.

package provider

import (
	"context"
	"errors"
	"fmt"

	p "github.com/pulumi/pulumi-go-provider"
	"github.com/pulumi/pulumi-go-provider/infer"
)

// SiteResource is the resource controller for managing Webflow sites.
// It implements the infer.CustomResource interface for full CRUD operations.
type SiteResource struct{}

// SiteArgs defines the input properties for the Site resource.
type SiteArgs struct {
	// WorkspaceID is the Webflow workspace ID where the site will be created.
	// Required for site creation operations - Enterprise workspace is required by Webflow API.
	// Example: "5f0c8c9e1c9d440000e8d8c3"
	WorkspaceID string `pulumi:"workspaceId"`
	// DisplayName is the human-readable name of the site shown in the Webflow dashboard.
	// Required - must be a non-empty string.
	// Examples: "My Marketing Site", "Company Blog", "Product Landing Page"
	DisplayName string `pulumi:"displayName"`
	// ParentFolderID is the folder ID where the site will be organized in the Webflow dashboard.
	// Optional - site will be placed at workspace root if not specified. Removing it from the
	// program moves the site back to the workspace root.
	ParentFolderID string `pulumi:"parentFolderId,optional"`
	// Publish triggers automatic site publishing after create/update.
	// When set to true, the provider will publish the site after successfully creating or updating it.
	// Default: false (manual publishing required).
	Publish bool `pulumi:"publish,optional"`
	// PublishToWebflowSubdomain publishes to the site's default webflow.io subdomain when Publish is true.
	PublishToWebflowSubdomain bool `pulumi:"publishToWebflowSubdomain,optional"`
	// PublishCustomDomains lists the custom domain IDs to publish to when Publish is true.
	PublishCustomDomains []string `pulumi:"publishCustomDomains,optional"`
	// PublishPageID limits the publish to a single page ID when Publish is true.
	PublishPageID string `pulumi:"publishPageId,optional"`
	// TemplateName is the template to use for site creation.
	// Optional - used only during site creation; the API never reports it back, so an imported
	// site has no templateName in state.
	// WARNING: Changing this value between two non-empty values will DELETE the existing site
	// and CREATE a new one (DESTRUCTIVE).
	// Examples: "mast-framework", "blank", or any other Webflow template identifier.
	TemplateName string `pulumi:"templateName,optional"`
}

// SiteState defines the output properties for the Site resource.
// It embeds SiteArgs to include input properties in the output.
type SiteState struct {
	SiteArgs
	// ShortName is the slugified version of the site name used in URLs (read-only).
	// Auto-generated by Webflow from the displayName. Cannot be set via API.
	// Examples: "my-site", "company-blog-2024", "product-landing"
	ShortName string `pulumi:"shortName,optional"`
	// TimeZone is the IANA timezone identifier for the site (read-only).
	// This value is set in Webflow Site Settings and cannot be changed via API.
	// Examples: "America/New_York", "Europe/London", "Asia/Tokyo", "UTC"
	TimeZone string `pulumi:"timeZone,optional"`
	// LastPublished is the timestamp of the last site publish (read-only).
	// Set automatically by Webflow when the site is published.
	LastPublished string `pulumi:"lastPublished,optional"`
	// LastUpdated is the timestamp of the last site update (read-only).
	// Set automatically by Webflow when the site configuration changes.
	LastUpdated string `pulumi:"lastUpdated,optional"`
	// PreviewURL is the URL to a preview image of the site (read-only).
	// Automatically generated by Webflow for site thumbnails.
	PreviewURL string `pulumi:"previewUrl,optional"`
	// CustomDomains is the list of custom domains attached to the site (read-only for now).
	// Custom domain management is out of scope for the MVP.
	CustomDomains []string `pulumi:"customDomains,optional"`
	// DataCollectionEnabled indicates if data collection is enabled for the site (read-only).
	// Controlled by Webflow workspace settings.
	DataCollectionEnabled bool `pulumi:"dataCollectionEnabled,optional"`
	// DataCollectionType is the type of data collection enabled (read-only).
	// Values: always, optOut, disabled. Controlled by Webflow workspace settings.
	DataCollectionType string `pulumi:"dataCollectionType,optional"`
	// PublishScope reports whether the last provider-triggered publish covered the whole site
	// ("site") or a single page ("page"), as returned by the publish endpoint (read-only).
	PublishScope string `pulumi:"publishScope,optional"`
}

// Annotate adds descriptions and constraints to the Site resource.
func (r *SiteResource) Annotate(a infer.Annotator) {
	a.SetToken("index", "Site")
	a.Describe(r, "Manages Webflow sites programmatically. "+
		"This resource allows you to create, configure, and manage Webflow sites through infrastructure code. "+
		"Create, Read, Update, and Delete operations are fully supported for complete site lifecycle management. "+
		"\n\n**Required scopes:** creating a site (POST /v2/workspaces/{workspace_id}/sites) requires the "+
		"`workspace:write` scope and an Enterprise workspace; reading a site requires `sites:read`; "+
		"updating, publishing and deleting a site require `sites:write`. "+
		"\n\n**Import:** `pulumi import webflow:index:Site my-site <siteId>`. The Webflow API does not report "+
		"the template a site was created from, so `templateName` is empty after import and only affects "+
		"creation; it is compared only when both the program and the state hold a value.")
}

// Annotate adds descriptions to the SiteArgs fields.
func (args *SiteArgs) Annotate(a infer.Annotator) {
	a.Describe(&args.WorkspaceID,
		"The Webflow workspace ID where the site will be created "+
			"(24-character lowercase hexadecimal string). "+
			"Required for site creation (Enterprise workspace and the `workspace:write` scope are required "+
			"by the Webflow API). Example: '5f0c8c9e1c9d440000e8d8c3'. "+
			"You can find your workspace ID in the Webflow dashboard under Account Settings > Workspace. "+
			"Changing this value replaces the site.")

	a.Describe(&args.DisplayName,
		"The human-readable name of the site as shown in the Webflow dashboard. "+
			"Required - must be a non-empty string. "+
			"Examples: 'My Marketing Site', 'Company Blog', 'Product Landing Page'. "+
			"This is the name users will see when managing the site.")

	a.Describe(&args.ParentFolderID,
		"The folder ID where the site will be organized in the Webflow dashboard "+
			"(24-character lowercase hexadecimal string). "+
			"Optional - the site will be placed at the workspace root if not specified. "+
			"Removing this property from your program moves the site back to the workspace root. "+
			"This is useful for organizing multiple sites into logical groups within your workspace.")

	a.Describe(&args.Publish,
		"Automatically publish the site after creation or updates. "+
			"When set to true, the provider calls the Webflow publish endpoint after "+
			"successfully creating or updating the site, using `publishToWebflowSubdomain`, "+
			"`publishCustomDomains` and `publishPageId` to build the publish request. "+
			"If neither `publishToWebflowSubdomain` nor `publishCustomDomains` is set, the site is "+
			"published to its webflow.io subdomain. "+
			"Default: false (manual publishing required). "+
			"If publishing fails, the operation fails with an error "+
			"(the site may exist but Pulumi will report failure).")

	a.Describe(&args.PublishToWebflowSubdomain,
		"When `publish` is true, publish to the site's default webflow.io subdomain. "+
			"Maps to the `publishToWebflowSubdomain` field of the Webflow publish endpoint. Default: false.")

	a.Describe(&args.PublishCustomDomains,
		"When `publish` is true, the list of custom domain IDs (not host names) to publish to. "+
			"Maps to the `customDomains` field of the Webflow publish endpoint. "+
			"Custom domain IDs can be read from the Webflow site settings or the sites API.")

	a.Describe(&args.PublishPageID,
		"When `publish` is true, publish only the page with this ID "+
			"(24-character lowercase hexadecimal string) instead of the whole site. "+
			"Maps to the `pageId` field of the Webflow publish endpoint.")

	a.Describe(&args.TemplateName,
		"The template to use for site creation. "+
			"Optional - if not specified, Webflow will create a blank site. "+
			"**This value only affects creation.** The Webflow API does not report which template a site "+
			"was created from, so it cannot be read back: after `pulumi import` the state holds no "+
			"templateName, and adding one to the program later does not change or replace the site. "+
			"**WARNING:** changing from one non-empty template to a different non-empty template triggers a "+
			"REPLACE operation, which will: "+
			"(1) DELETE your existing site and ALL its content (pages, CMS items, assets, etc.), "+
			"(2) CREATE a new site with the new template, "+
			"(3) REPLACE all dependent resources (redirects, robots.txt, etc.). "+
			"This is a DESTRUCTIVE operation that cannot be undone. "+
			"Use any valid Webflow template identifier (e.g., 'mast-framework', 'blank'). "+
			"Consider using resource protection (`protect: true`) to prevent accidental replacement.")
}

// Annotate adds descriptions to the SiteState fields.
func (state *SiteState) Annotate(a infer.Annotator) {
	a.Describe(&state.ShortName,
		"The slugified version of the site name used in URLs (read-only). "+
			"Auto-generated by Webflow from the displayName. Cannot be set via API. "+
			"Examples: 'my-site', 'company-blog-2024', 'product-landing'.")

	a.Describe(&state.TimeZone,
		"The IANA timezone identifier for the site (read-only). "+
			"This value is configured in Webflow Site Settings and cannot be changed via API. "+
			"Examples: 'America/New_York', 'Europe/London', 'Asia/Tokyo', 'UTC'.")

	a.Describe(&state.LastPublished,
		"The RFC3339 timestamp of the last time the site was published (read-only). "+
			"Automatically set by Webflow when changes are published to production.")

	a.Describe(&state.LastUpdated,
		"The RFC3339 timestamp of the last time the site configuration was updated (read-only). "+
			"Automatically set by Webflow when any site changes occur.")

	a.Describe(&state.PreviewURL,
		"The URL to a preview image of the site (read-only). "+
			"Automatically generated by Webflow for site thumbnails in the dashboard.")

	a.Describe(&state.CustomDomains,
		"List of custom domains attached to the site (read-only in this release). "+
			"Custom domain management will be available in a future release.")

	a.Describe(&state.DataCollectionEnabled,
		"Indicates whether data collection is enabled for this site (read-only). "+
			"Controlled by your Webflow workspace settings, not per-site.")

	a.Describe(&state.DataCollectionType,
		"The type of data collection enabled for the site (read-only). "+
			"Possible values: 'always' (always collect), 'optOut' (collect by default), 'disabled' (no collection). "+
			"Controlled by your Webflow workspace settings, not per-site.")

	a.Describe(&state.PublishScope,
		"Scope of the last publish triggered by this provider (read-only): "+
			"'site' when the whole site was published, 'page' when only `publishPageId` was published. "+
			"Empty when the provider has not published the site.")
}

// siteCheckValidators lists the known-value validators applied by Check.
var siteCheckValidators = []stringValidator{
	{property: "workspaceId", validate: ValidateWorkspaceID},
	{property: "displayName", validate: ValidateDisplayName},
	{property: "parentFolderId", validate: ValidateParentFolderID},
	{property: "publishPageId", validate: ValidatePublishPageID},
	{property: "templateName", validate: ValidateTemplateName},
}

// Check validates the inputs that are already known at preview time. Values that still depend
// on other resources' outputs are skipped here and validated again in Create or Update.
func (r *SiteResource) Check(
	ctx context.Context, req infer.CheckRequest,
) (infer.CheckResponse[SiteArgs], error) {
	inputs, failures, err := checkStrings[SiteArgs](ctx, req.NewInputs, siteCheckValidators...)
	return infer.CheckResponse[SiteArgs]{Inputs: inputs, Failures: failures}, err
}

// validateSiteArgs validates the fully-resolved inputs shared by Create and Update.
// workspaceId is validated by Create only: it is not needed to update an existing site.
func validateSiteArgs(args SiteArgs) error {
	if err := ValidateDisplayName(args.DisplayName); err != nil {
		return fmt.Errorf("validation failed for Site resource: %w", err)
	}
	if err := ValidateParentFolderID(args.ParentFolderID); err != nil {
		return fmt.Errorf("validation failed for Site resource: %w", err)
	}
	if err := ValidatePublishPageID(args.PublishPageID); err != nil {
		return fmt.Errorf("validation failed for Site resource: %w", err)
	}
	if err := ValidateTemplateName(args.TemplateName); err != nil {
		return fmt.Errorf("validation failed for Site resource: %w", err)
	}
	return nil
}

// Diff determines what changes need to be made to the site resource.
// For sites, workspace ID and site ID are immutable (primary key).
// Other fields (displayName, timeZone, etc.) can be updated.
func (r *SiteResource) Diff(
	ctx context.Context, req infer.DiffRequest[SiteArgs, SiteState],
) (infer.DiffResponse, error) {
	diff := infer.DiffResponse{
		DeleteBeforeReplace: false,
		HasChanges:          false,
		DetailedDiff:        make(map[string]p.PropertyDiff),
	}

	// Check immutable fields (workspaceId, templateName) - require replace if changed
	if req.Inputs.WorkspaceID != req.State.WorkspaceID {
		diff.HasChanges = true
		diff.DeleteBeforeReplace = false
		diff.DetailedDiff["workspaceId"] = p.PropertyDiff{
			Kind: p.UpdateReplace,
		}
		// If workspace changes, entire resource must be replaced
		return diff, nil
	}

	// templateName only affects creation and cannot be read back from the API, so an imported
	// site carries no template in state. Compare it only when both sides hold a value; otherwise
	// `pulumi import` followed by `pulumi up` would replace (permanently delete) the site.
	if req.Inputs.TemplateName != "" && req.State.TemplateName != "" &&
		req.Inputs.TemplateName != req.State.TemplateName {
		diff.HasChanges = true
		diff.DeleteBeforeReplace = false
		diff.DetailedDiff["templateName"] = p.PropertyDiff{
			Kind: p.UpdateReplace,
		}
		// If template changes, entire resource must be replaced
		return diff, nil
	}

	// Check mutable fields - can be updated in place
	// CRITICAL: Accumulate all changes in SINGLE map (don't overwrite!)
	update := func(name string, changed bool) {
		if changed {
			diff.HasChanges = true
			diff.DetailedDiff[name] = p.PropertyDiff{Kind: p.Update}
		}
	}

	update("displayName", req.Inputs.DisplayName != req.State.DisplayName)
	// Note: shortName is read-only (auto-generated by Webflow) - not diffed
	// Note: TimeZone is read-only (output only) - cannot be changed via API
	update("parentFolderId", req.Inputs.ParentFolderID != req.State.ParentFolderID)
	update("publish", req.Inputs.Publish != req.State.Publish)
	update("publishToWebflowSubdomain", req.Inputs.PublishToWebflowSubdomain != req.State.PublishToWebflowSubdomain)
	update("publishCustomDomains", !stringSlicesEqual(req.Inputs.PublishCustomDomains, req.State.PublishCustomDomains))
	update("publishPageId", req.Inputs.PublishPageID != req.State.PublishPageID)

	return diff, nil
}

// buildPublishRequest maps the publish-related inputs onto the publish endpoint body.
// When neither a custom domain nor the subdomain is selected the request would publish
// nothing, so the provider falls back to the webflow.io subdomain and says so.
func buildPublishRequest(log *LogContext, args SiteArgs) SitePublishRequest {
	request := SitePublishRequest{
		CustomDomains:             args.PublishCustomDomains,
		PublishToWebflowSubdomain: args.PublishToWebflowSubdomain,
		PageID:                    args.PublishPageID,
	}
	if len(request.CustomDomains) == 0 && !request.PublishToWebflowSubdomain {
		log.Warn("publish is true but neither publishToWebflowSubdomain nor publishCustomDomains is set; " +
			"publishing to the webflow.io subdomain. Set publishToWebflowSubdomain or publishCustomDomains " +
			"explicitly to silence this warning")
		request.PublishToWebflowSubdomain = true
	}
	return request
}

// applySiteResponse copies the read-only fields of an API site object into state.
func applySiteResponse(state *SiteState, site *Site) {
	state.ShortName = site.ShortName
	state.TimeZone = site.TimeZone
	state.LastPublished = site.LastPublished
	state.LastUpdated = site.LastUpdated
	state.PreviewURL = site.PreviewURL
	if site.CustomDomains != nil {
		state.CustomDomains = []string(site.CustomDomains)
	}
	state.DataCollectionEnabled = site.DataCollectionEnabled
	state.DataCollectionType = site.DataCollectionType
}

// Create creates a new site in Webflow.
func (r *SiteResource) Create(
	ctx context.Context, req infer.CreateRequest[SiteArgs],
) (infer.CreateResponse[SiteState], error) {
	log := NewLogContext(ctx).
		WithField("workspaceId", req.Inputs.WorkspaceID).
		WithField("displayName", req.Inputs.DisplayName)
	log.Info("Creating Webflow site")

	state := SiteState{
		SiteArgs: req.Inputs,
		// Read-only fields will be populated from API response
	}

	// Preview: return the inputs without an ID and without calling the API. An empty ID tells
	// the framework to present the ID and every output as unknown to dependent resources.
	// Inputs may still be unknown at this point (they arrive zeroed), so validation of the
	// resolved values happens at apply time (Check already validated the known ones).
	if req.DryRun {
		log.Debug("Dry run mode - skipping API call")
		return infer.CreateResponse[SiteState]{Output: state}, nil
	}

	// Validate inputs BEFORE any API call
	if err := ValidateWorkspaceID(req.Inputs.WorkspaceID); err != nil {
		log.Errorf("Validation failed: %v", err)
		return infer.CreateResponse[SiteState]{}, fmt.Errorf("validation failed for Site resource: %w", err)
	}
	if err := validateSiteArgs(req.Inputs); err != nil {
		log.Errorf("Validation failed: %v", err)
		return infer.CreateResponse[SiteState]{}, err
	}
	// Note: shortName is read-only (auto-generated by Webflow) and is not validated

	client, err := GetHTTPClient(ctx, currentProviderVersion())
	if err != nil {
		log.Errorf("Failed to create HTTP client: %v", err)
		return infer.CreateResponse[SiteState]{}, fmt.Errorf("failed to create HTTP client: %w", err)
	}

	log.Debug("Calling Webflow API to create site")
	response, err := PostSite(
		ctx, client,
		req.Inputs.WorkspaceID, req.Inputs.DisplayName,
		req.Inputs.ParentFolderID, req.Inputs.TemplateName,
	)
	if err != nil {
		log.Errorf("Failed to create site via API: %v", err)
		return infer.CreateResponse[SiteState]{}, fmt.Errorf("failed to create site: %w", err)
	}

	if response.ID == "" {
		log.Error("API returned empty site ID")
		return infer.CreateResponse[SiteState]{}, errors.New(
			"webflow API returned empty site ID - " +
				"this is unexpected and may indicate an API issue")
	}

	log.WithField("siteId", response.ID).Info("Site created successfully")
	applySiteResponse(&state, response)

	if req.Inputs.Publish {
		log.WithField("siteId", response.ID).Debug("Publishing site after creation")
		publishResp, err := PublishSite(ctx, client, response.ID, buildPublishRequest(log, req.Inputs))
		if err != nil {
			log.WithField("siteId", response.ID).Errorf("Publishing failed: %v", err)
			return infer.CreateResponse[SiteState]{}, fmt.Errorf("site created successfully but publishing failed: %w", err)
		}
		state.PublishScope = publishResp.PublishScope
		log.WithField("siteId", response.ID).WithField("publishScope", publishResp.PublishScope).
			Info("Site publish accepted")
	}

	return infer.CreateResponse[SiteState]{
		ID:     response.ID,
		Output: state,
	}, nil
}

// Read retrieves the current state of a site from Webflow.
// This is called by Pulumi during preview, refresh, update, and IMPORT operations to detect drift.
// If the site was deleted externally (404), Read returns an empty ID to signal deletion; any
// other error is returned so transient failures never look like a deleted site.
//
// Import Support: Accepts siteId directly
// Example: pulumi import webflow:index:Site my-site "69307a0ff82ccd49b929ed6d"
// The workspaceId is automatically fetched from the Webflow API. templateName cannot be
// recovered (the API never reports it) and stays empty after import; Diff tolerates that.
func (r *SiteResource) Read(
	ctx context.Context, req infer.ReadRequest[SiteArgs, SiteState],
) (infer.ReadResponse[SiteArgs, SiteState], error) {
	// Resource ID is just the siteId; validate it before it is used in a URL
	siteID := req.ID
	if err := ValidateSiteID(siteID); err != nil {
		return infer.ReadResponse[SiteArgs, SiteState]{}, fmt.Errorf("invalid resource ID: %w", err)
	}

	client, err := GetHTTPClient(ctx, currentProviderVersion())
	if err != nil {
		return infer.ReadResponse[SiteArgs, SiteState]{}, fmt.Errorf("failed to get HTTP client: %w", err)
	}

	// GetSite returns nil, nil only for a 404 (IsNotFound); every other failure is an error.
	siteData, err := GetSite(ctx, client, siteID)
	if err != nil {
		return infer.ReadResponse[SiteArgs, SiteState]{}, fmt.Errorf("failed to read site (site ID: %s): %w", siteID, err)
	}
	if siteData == nil {
		// Site was deleted externally: an empty ID tells Pulumi the resource is gone.
		return infer.ReadResponse[SiteArgs, SiteState]{ID: ""}, nil
	}

	// Publish-related properties are not returned by GET - preserve them from the existing state
	currentInputs := SiteArgs{
		WorkspaceID:               siteData.WorkspaceID,
		DisplayName:               siteData.DisplayName,
		ParentFolderID:            siteData.ParentFolderID,
		Publish:                   req.State.Publish,
		PublishToWebflowSubdomain: req.State.PublishToWebflowSubdomain,
		PublishCustomDomains:      req.State.PublishCustomDomains,
		PublishPageID:             req.State.PublishPageID,
		TemplateName:              req.State.TemplateName,
	}

	currentState := SiteState{
		SiteArgs:     currentInputs,
		PublishScope: req.State.PublishScope,
	}
	applySiteResponse(&currentState, siteData)

	return infer.ReadResponse[SiteArgs, SiteState]{
		ID:     siteID,
		Inputs: currentInputs,
		State:  currentState,
	}, nil
}

// Update modifies an existing site configuration.
func (r *SiteResource) Update(
	ctx context.Context, req infer.UpdateRequest[SiteArgs, SiteState],
) (infer.UpdateResponse[SiteState], error) {
	siteID := req.ID

	log := NewLogContext(ctx).
		WithField("siteId", siteID).
		WithField("displayName", req.Inputs.DisplayName)
	log.Info("Updating Webflow site")

	state := SiteState{
		SiteArgs: req.Inputs,
		// Preserve read-only fields from previous state
		ShortName:             req.State.ShortName,
		TimeZone:              req.State.TimeZone,
		LastPublished:         req.State.LastPublished,
		LastUpdated:           req.State.LastUpdated,
		PreviewURL:            req.State.PreviewURL,
		CustomDomains:         req.State.CustomDomains,
		DataCollectionEnabled: req.State.DataCollectionEnabled,
		DataCollectionType:    req.State.DataCollectionType,
		PublishScope:          req.State.PublishScope,
	}

	// Preview: return the expected state without validating (inputs may be unknown) or calling the API.
	if req.DryRun {
		log.Debug("Dry run mode - skipping API call")
		return infer.UpdateResponse[SiteState]{
			Output: state,
		}, nil
	}

	if err := ValidateSiteID(siteID); err != nil {
		log.Errorf("Validation failed: %v", err)
		return infer.UpdateResponse[SiteState]{}, fmt.Errorf("invalid resource ID: %w", err)
	}
	if err := validateSiteArgs(req.Inputs); err != nil {
		log.Errorf("Validation failed: %v", err)
		return infer.UpdateResponse[SiteState]{}, err
	}

	client, err := GetHTTPClient(ctx, currentProviderVersion())
	if err != nil {
		log.Errorf("Failed to create HTTP client: %v", err)
		return infer.UpdateResponse[SiteState]{}, fmt.Errorf("failed to create HTTP client: %w", err)
	}

	// parentFolderId is nullable on PATCH: send the new folder, send null when the user removed
	// the folder (state had one, inputs do not), and omit it when it was never set.
	var parentFolderID *string
	switch {
	case req.Inputs.ParentFolderID != "":
		folder := req.Inputs.ParentFolderID
		parentFolderID = &folder
	case req.State.ParentFolderID != "":
		cleared := ""
		parentFolderID = &cleared
		log.Debug("parentFolderId removed - moving site to the workspace root")
	}

	log.Debug("Calling Webflow API to update site")
	response, err := PatchSite(ctx, client, siteID, req.Inputs.DisplayName, parentFolderID)
	if err != nil {
		log.Errorf("Failed to update site via API: %v", err)
		return infer.UpdateResponse[SiteState]{}, fmt.Errorf("failed to update site: %w", err)
	}

	log.Info("Site updated successfully")

	// The API returns the full site object
	state.DisplayName = response.DisplayName
	state.ParentFolderID = response.ParentFolderID
	applySiteResponse(&state, response)

	if req.Inputs.Publish {
		log.Debug("Publishing site after update")
		publishResp, err := PublishSite(ctx, client, siteID, buildPublishRequest(log, req.Inputs))
		if err != nil {
			log.Errorf("Publishing failed: %v", err)
			return infer.UpdateResponse[SiteState]{}, fmt.Errorf("site updated successfully but publishing failed: %w", err)
		}
		state.PublishScope = publishResp.PublishScope
		log.WithField("publishScope", publishResp.PublishScope).Info("Site publish accepted")
	}

	return infer.UpdateResponse[SiteState]{
		Output: state,
	}, nil
}

// Delete removes a site from Webflow.
// This is a destructive operation that permanently deletes the site and all its content.
// The operation cannot be undone.
func (r *SiteResource) Delete(ctx context.Context, req infer.DeleteRequest[SiteState]) (infer.DeleteResponse, error) {
	siteID := req.ID

	log := NewLogContext(ctx).
		WithField("siteId", siteID).
		WithField("displayName", req.State.DisplayName)
	log.Warn("Deleting Webflow site - this is a destructive operation")

	if err := ValidateSiteID(siteID); err != nil {
		return infer.DeleteResponse{}, fmt.Errorf("invalid resource ID: %w", err)
	}

	client, err := GetHTTPClient(ctx, currentProviderVersion())
	if err != nil {
		log.Errorf("Failed to create HTTP client: %v", err)
		return infer.DeleteResponse{}, fmt.Errorf("failed to create HTTP client: %w", err)
	}

	log.Debug("Calling Webflow API to delete site")
	if err := DeleteSite(ctx, client, siteID); err != nil {
		log.Errorf("Failed to delete site via API: %v", err)
		return infer.DeleteResponse{}, fmt.Errorf("failed to delete site (site ID: %s): %w", siteID, err)
	}

	log.Info("Site deleted successfully")
	return infer.DeleteResponse{}, nil
}
