// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow.Outputs
{

    [OutputType]
    public sealed class AnalyticsBucketing
    {
        /// <summary>
        /// The IANA time zone used to align bucket boundaries (e.g., 'UTC', 'America/New_York').
        /// </summary>
        public readonly string BucketTimeZone;
        /// <summary>
        /// The size of each time bucket: 'day' or 'week'.
        /// </summary>
        public readonly string GranularityPeriod;

        [OutputConstructor]
        private AnalyticsBucketing(
            string bucketTimeZone,

            string granularityPeriod)
        {
            BucketTimeZone = bucketTimeZone;
            GranularityPeriod = granularityPeriod;
        }
    }
}
