// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Community.Pulumi.Webflow.Outputs
{

    [OutputType]
    public sealed class PageOpenGraphArgs
    {
        /// <summary>
        /// The Open Graph description of the page.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// Whether the Open Graph description is copied from the SEO description.
        /// </summary>
        public readonly bool? DescriptionCopied;
        /// <summary>
        /// The Open Graph title of the page.
        /// </summary>
        public readonly string? Title;
        /// <summary>
        /// Whether the Open Graph title is copied from the SEO title.
        /// </summary>
        public readonly bool? TitleCopied;

        [OutputConstructor]
        private PageOpenGraphArgs(
            string? description,

            bool? descriptionCopied,

            string? title,

            bool? titleCopied)
        {
            Description = description;
            DescriptionCopied = descriptionCopied;
            Title = title;
            TitleCopied = titleCopied;
        }
    }
}
