// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Returns the top values of a chosen dimension (country, region, device type, OS, browser, language, locale, referrer, traffic source, UTM parameters or audience) for a Webflow site, ranked by sessions or users (Analyze API, beta). Requires the 'sites:read' scope and a Webflow workspace with the Analyze add-on. Webflow allows one Analyze request in flight per access token; concurrent requests are retried. The reporting window must start on or after 2025-04-09 and span at most 100 days.
 */
export function getAnalyticsTopDimensions(args: GetAnalyticsTopDimensionsArgs, opts?: pulumi.InvokeOptions): Promise<GetAnalyticsTopDimensionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("webflow:index:getAnalyticsTopDimensions", {
        "browser": args.browser,
        "country": args.country,
        "deviceType": args.deviceType,
        "dimension": args.dimension,
        "endTime": args.endTime,
        "filters": args.filters,
        "limit": args.limit,
        "metricScope": args.metricScope,
        "pagePath": args.pagePath,
        "referrer": args.referrer,
        "siteId": args.siteId,
        "startTime": args.startTime,
        "trafficSource": args.trafficSource,
        "utmCampaign": args.utmCampaign,
        "utmMedium": args.utmMedium,
        "utmSource": args.utmSource,
    }, opts);
}

export interface GetAnalyticsTopDimensionsArgs {
    /**
     * Restrict the report to a single browser name (e.g., 'Chrome').
     */
    browser?: string;
    /**
     * Restrict the report to a single country, as an ISO 3166-1 alpha-2 code (e.g., 'US'). Normalized to uppercase.
     */
    country?: string;
    /**
     * Restrict the report to a single device type: 'desktop', 'mobile' or 'tablet'.
     */
    deviceType?: string;
    /**
     * The dimension to rank. One of: 'country', 'region', 'deviceType', 'os', 'browser', 'language', 'locale', 'referrer', 'trafficSource', 'utmCampaign', 'utmContent', 'utmMedium', 'utmSource', 'utmTerm', 'audienceIds'.
     */
    dimension: string;
    /**
     * Exclusive end of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be after startTime and within 100 days of it.
     */
    endTime: string;
    /**
     * Advanced filters keyed by dimension (e.g., 'country', 'deviceType', 'pagePath', 'referrer', 'trafficSource', 'utmCampaign', 'os', 'language', 'locale', 'region', 'audienceIds', 'collectionId', 'itemSlug', 'pageId', 'dayOfWeek', 'timeOfDay', 'visitStatus', ...). Each entry supports 'eq', 'in', 'ne' and 'nin'. Filter a given dimension either here or with the matching single-value input, not both.
     */
    filters?: {[key: string]: inputs.AnalyticsDimensionFilter};
    /**
     * Maximum number of rows to return. Defaults to 25, up to a maximum of 100.
     */
    limit?: number;
    /**
     * Unit of each row's count: 'session' or 'user'.
     */
    metricScope: string;
    /**
     * Restrict the report to a single page path (e.g., '/pricing').
     */
    pagePath?: string;
    /**
     * Restrict the report to a single referrer domain (e.g., 'google.com').
     */
    referrer?: string;
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string).
     */
    siteId: string;
    /**
     * Inclusive start of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be on or after 2025-04-09T00:00:00Z.
     */
    startTime: string;
    /**
     * Restrict the report to a single traffic source code (e.g., 'SO' for Organic Search).
     */
    trafficSource?: string;
    /**
     * Restrict the report to a single utm_campaign value.
     */
    utmCampaign?: string;
    /**
     * Restrict the report to a single utm_medium value.
     */
    utmMedium?: string;
    /**
     * Restrict the report to a single utm_source value.
     */
    utmSource?: string;
}

export interface GetAnalyticsTopDimensionsResult {
    /**
     * The ranked dimension values, highest count first.
     */
    readonly data: outputs.AnalyticsDimensionRow[];
    /**
     * The dimension whose values were ranked.
     */
    readonly dimension: string;
    /**
     * The filters that were applied, keyed by dimension.
     */
    readonly filters?: {[key: string]: outputs.AnalyticsDimensionFilter};
    /**
     * The row cap that was applied (echoes the request value, including the default).
     */
    readonly limit: number;
    /**
     * The unit each count is measured in: 'session' or 'user'.
     */
    readonly metricScope: string;
    /**
     * The report name, always 'top_dimensions'.
     */
    readonly report: string;
    /**
     * The reporting window that was applied.
     */
    readonly window: outputs.AnalyticsWindow;
}
/**
 * Returns the top values of a chosen dimension (country, region, device type, OS, browser, language, locale, referrer, traffic source, UTM parameters or audience) for a Webflow site, ranked by sessions or users (Analyze API, beta). Requires the 'sites:read' scope and a Webflow workspace with the Analyze add-on. Webflow allows one Analyze request in flight per access token; concurrent requests are retried. The reporting window must start on or after 2025-04-09 and span at most 100 days.
 */
export function getAnalyticsTopDimensionsOutput(args: GetAnalyticsTopDimensionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAnalyticsTopDimensionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("webflow:index:getAnalyticsTopDimensions", {
        "browser": args.browser,
        "country": args.country,
        "deviceType": args.deviceType,
        "dimension": args.dimension,
        "endTime": args.endTime,
        "filters": args.filters,
        "limit": args.limit,
        "metricScope": args.metricScope,
        "pagePath": args.pagePath,
        "referrer": args.referrer,
        "siteId": args.siteId,
        "startTime": args.startTime,
        "trafficSource": args.trafficSource,
        "utmCampaign": args.utmCampaign,
        "utmMedium": args.utmMedium,
        "utmSource": args.utmSource,
    }, opts);
}

export interface GetAnalyticsTopDimensionsOutputArgs {
    /**
     * Restrict the report to a single browser name (e.g., 'Chrome').
     */
    browser?: pulumi.Input<string | undefined>;
    /**
     * Restrict the report to a single country, as an ISO 3166-1 alpha-2 code (e.g., 'US'). Normalized to uppercase.
     */
    country?: pulumi.Input<string | undefined>;
    /**
     * Restrict the report to a single device type: 'desktop', 'mobile' or 'tablet'.
     */
    deviceType?: pulumi.Input<string | undefined>;
    /**
     * The dimension to rank. One of: 'country', 'region', 'deviceType', 'os', 'browser', 'language', 'locale', 'referrer', 'trafficSource', 'utmCampaign', 'utmContent', 'utmMedium', 'utmSource', 'utmTerm', 'audienceIds'.
     */
    dimension: pulumi.Input<string>;
    /**
     * Exclusive end of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be after startTime and within 100 days of it.
     */
    endTime: pulumi.Input<string>;
    /**
     * Advanced filters keyed by dimension (e.g., 'country', 'deviceType', 'pagePath', 'referrer', 'trafficSource', 'utmCampaign', 'os', 'language', 'locale', 'region', 'audienceIds', 'collectionId', 'itemSlug', 'pageId', 'dayOfWeek', 'timeOfDay', 'visitStatus', ...). Each entry supports 'eq', 'in', 'ne' and 'nin'. Filter a given dimension either here or with the matching single-value input, not both.
     */
    filters?: pulumi.Input<{[key: string]: pulumi.Input<inputs.AnalyticsDimensionFilterArgs>} | undefined>;
    /**
     * Maximum number of rows to return. Defaults to 25, up to a maximum of 100.
     */
    limit?: pulumi.Input<number | undefined>;
    /**
     * Unit of each row's count: 'session' or 'user'.
     */
    metricScope: pulumi.Input<string>;
    /**
     * Restrict the report to a single page path (e.g., '/pricing').
     */
    pagePath?: pulumi.Input<string | undefined>;
    /**
     * Restrict the report to a single referrer domain (e.g., 'google.com').
     */
    referrer?: pulumi.Input<string | undefined>;
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string).
     */
    siteId: pulumi.Input<string>;
    /**
     * Inclusive start of the reporting window. UTC timestamp in ISO 8601 / RFC 3339 format ending in 'Z' (e.g., '2026-04-01T00:00:00Z'). Numeric offsets are not accepted. Must be on or after 2025-04-09T00:00:00Z.
     */
    startTime: pulumi.Input<string>;
    /**
     * Restrict the report to a single traffic source code (e.g., 'SO' for Organic Search).
     */
    trafficSource?: pulumi.Input<string | undefined>;
    /**
     * Restrict the report to a single utm_campaign value.
     */
    utmCampaign?: pulumi.Input<string | undefined>;
    /**
     * Restrict the report to a single utm_medium value.
     */
    utmMedium?: pulumi.Input<string | undefined>;
    /**
     * Restrict the report to a single utm_source value.
     */
    utmSource?: pulumi.Input<string | undefined>;
}
