// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Lists all pages of a Webflow site with their metadata, following API pagination. Useful for discovering page IDs for the PageMetadata, PageContent and PageCustomCode resources. Requires the pages:read scope.
 */
export function getPages(args: GetPagesArgs, opts?: pulumi.InvokeOptions): Promise<GetPagesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("webflow:index:getPages", {
        "localeId": args.localeId,
        "siteId": args.siteId,
    }, opts);
}

export interface GetPagesArgs {
    /**
     * Optional locale ID. When omitted the primary locale is returned.
     */
    localeId?: string;
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string).
     */
    siteId: string;
}

export interface GetPagesResult {
    /**
     * All pages of the site.
     */
    readonly pages: outputs.PageRecord[];
    /**
     * The site ID that was listed.
     */
    readonly siteId: string;
}
/**
 * Lists all pages of a Webflow site with their metadata, following API pagination. Useful for discovering page IDs for the PageMetadata, PageContent and PageCustomCode resources. Requires the pages:read scope.
 */
export function getPagesOutput(args: GetPagesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPagesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("webflow:index:getPages", {
        "localeId": args.localeId,
        "siteId": args.siteId,
    }, opts);
}

export interface GetPagesOutputArgs {
    /**
     * Optional locale ID. When omitted the primary locale is returned.
     */
    localeId?: pulumi.Input<string | undefined>;
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string).
     */
    siteId: pulumi.Input<string>;
}
