// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a single Google Tag ID (Google Analytics 4, Google Tag, Google Ads or Campaign Manager) configured on a Webflow site via the Google Tag Manager integration API. Each resource manages one entry in the site's tag list, so multiple GoogleTag resources may target the same site. Tags on the site that are not managed by Pulumi are left untouched. Requires the 'sites:read' and 'sites:write' scopes. Webflow allows up to 25 tags per site and rejects legacy Universal Analytics 'UA-' IDs.
 */
export class GoogleTag extends pulumi.CustomResource {
    /**
     * Get an existing GoogleTag resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): GoogleTag {
        return new GoogleTag(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'webflow:index:GoogleTag';

    /**
     * Returns true if the given object is an instance of GoogleTag.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GoogleTag {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GoogleTag.__pulumiType;
    }

    /**
     * A human-readable label for the tag shown in the Webflow dashboard (e.g., 'Primary Google Analytics').
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * The display position Webflow reports for this tag. This reflects any automatic assignment or renormalization performed by Webflow and may differ from 'order'. Read-only.
     */
    declare public /*out*/ readonly effectiveOrder: pulumi.Output<number | undefined>;
    /**
     * Optional display position of the tag within the site's tag list. When omitted, Webflow assigns the position automatically (see 'effectiveOrder'). Webflow renormalizes positions after a tag is deleted, so only set this when you need to control ordering explicitly.
     */
    declare public readonly order: pulumi.Output<number | undefined>;
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). Changing this value replaces the resource.
     */
    declare public readonly siteId: pulumi.Output<string>;
    /**
     * The Google Tag ID to configure, e.g., 'G-1A2B3C4D5E' (GA4 measurement ID), 'GT-ABC123' (Google Tag), 'AW-123456789' (Google Ads) or 'DC-1234567' (Campaign Manager). Webflow rejects Universal Analytics 'UA-' IDs. Changing this value replaces the resource.
     */
    declare public readonly tagId: pulumi.Output<string>;

    /**
     * Create a GoogleTag resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GoogleTagArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            if (args?.siteId === undefined && !opts.urn) {
                throw new Error("Missing required property 'siteId'");
            }
            if (args?.tagId === undefined && !opts.urn) {
                throw new Error("Missing required property 'tagId'");
            }
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["order"] = args?.order;
            resourceInputs["siteId"] = args?.siteId;
            resourceInputs["tagId"] = args?.tagId;
            resourceInputs["effectiveOrder"] = undefined /*out*/;
        } else {
            resourceInputs["displayName"] = undefined /*out*/;
            resourceInputs["effectiveOrder"] = undefined /*out*/;
            resourceInputs["order"] = undefined /*out*/;
            resourceInputs["siteId"] = undefined /*out*/;
            resourceInputs["tagId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GoogleTag.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a GoogleTag resource.
 */
export interface GoogleTagArgs {
    /**
     * A human-readable label for the tag shown in the Webflow dashboard (e.g., 'Primary Google Analytics').
     */
    displayName: pulumi.Input<string>;
    /**
     * Optional display position of the tag within the site's tag list. When omitted, Webflow assigns the position automatically (see 'effectiveOrder'). Webflow renormalizes positions after a tag is deleted, so only set this when you need to control ordering explicitly.
     */
    order?: pulumi.Input<number | undefined>;
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). Changing this value replaces the resource.
     */
    siteId: pulumi.Input<string>;
    /**
     * The Google Tag ID to configure, e.g., 'G-1A2B3C4D5E' (GA4 measurement ID), 'GT-ABC123' (Google Tag), 'AW-123456789' (Google Ads) or 'DC-1234567' (Campaign Manager). Webflow rejects Universal Analytics 'UA-' IDs. Changing this value replaces the resource.
     */
    tagId: pulumi.Input<string>;
}
