// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { AssetArgs } from "./asset";
export type Asset = import("./asset").Asset;
export const Asset: typeof import("./asset").Asset = null as any;
utilities.lazyLoad(exports, ["Asset"], () => require("./asset"));

export { AssetFolderArgs } from "./assetFolder";
export type AssetFolder = import("./assetFolder").AssetFolder;
export const AssetFolder: typeof import("./assetFolder").AssetFolder = null as any;
utilities.lazyLoad(exports, ["AssetFolder"], () => require("./assetFolder"));

export { CollectionArgs } from "./collection";
export type Collection = import("./collection").Collection;
export const Collection: typeof import("./collection").Collection = null as any;
utilities.lazyLoad(exports, ["Collection"], () => require("./collection"));

export { CollectionFieldArgs } from "./collectionField";
export type CollectionField = import("./collectionField").CollectionField;
export const CollectionField: typeof import("./collectionField").CollectionField = null as any;
utilities.lazyLoad(exports, ["CollectionField"], () => require("./collectionField"));

export { CollectionItemArgs } from "./collectionItem";
export type CollectionItem = import("./collectionItem").CollectionItem;
export const CollectionItem: typeof import("./collectionItem").CollectionItem = null as any;
utilities.lazyLoad(exports, ["CollectionItem"], () => require("./collectionItem"));

export { EcommerceSettingsArgs } from "./ecommerceSettings";
export type EcommerceSettings = import("./ecommerceSettings").EcommerceSettings;
export const EcommerceSettings: typeof import("./ecommerceSettings").EcommerceSettings = null as any;
utilities.lazyLoad(exports, ["EcommerceSettings"], () => require("./ecommerceSettings"));

export { GetAnalyticsTimeOnPageArgs, GetAnalyticsTimeOnPageResult, GetAnalyticsTimeOnPageOutputArgs } from "./getAnalyticsTimeOnPage";
export const getAnalyticsTimeOnPage: typeof import("./getAnalyticsTimeOnPage").getAnalyticsTimeOnPage = null as any;
export const getAnalyticsTimeOnPageOutput: typeof import("./getAnalyticsTimeOnPage").getAnalyticsTimeOnPageOutput = null as any;
utilities.lazyLoad(exports, ["getAnalyticsTimeOnPage","getAnalyticsTimeOnPageOutput"], () => require("./getAnalyticsTimeOnPage"));

export { GetAnalyticsTopDimensionsArgs, GetAnalyticsTopDimensionsResult, GetAnalyticsTopDimensionsOutputArgs } from "./getAnalyticsTopDimensions";
export const getAnalyticsTopDimensions: typeof import("./getAnalyticsTopDimensions").getAnalyticsTopDimensions = null as any;
export const getAnalyticsTopDimensionsOutput: typeof import("./getAnalyticsTopDimensions").getAnalyticsTopDimensionsOutput = null as any;
utilities.lazyLoad(exports, ["getAnalyticsTopDimensions","getAnalyticsTopDimensionsOutput"], () => require("./getAnalyticsTopDimensions"));

export { GetAnalyticsTopEventsArgs, GetAnalyticsTopEventsResult, GetAnalyticsTopEventsOutputArgs } from "./getAnalyticsTopEvents";
export const getAnalyticsTopEvents: typeof import("./getAnalyticsTopEvents").getAnalyticsTopEvents = null as any;
export const getAnalyticsTopEventsOutput: typeof import("./getAnalyticsTopEvents").getAnalyticsTopEventsOutput = null as any;
utilities.lazyLoad(exports, ["getAnalyticsTopEvents","getAnalyticsTopEventsOutput"], () => require("./getAnalyticsTopEvents"));

export { GetAnalyticsTopPagesArgs, GetAnalyticsTopPagesResult, GetAnalyticsTopPagesOutputArgs } from "./getAnalyticsTopPages";
export const getAnalyticsTopPages: typeof import("./getAnalyticsTopPages").getAnalyticsTopPages = null as any;
export const getAnalyticsTopPagesOutput: typeof import("./getAnalyticsTopPages").getAnalyticsTopPagesOutput = null as any;
utilities.lazyLoad(exports, ["getAnalyticsTopPages","getAnalyticsTopPagesOutput"], () => require("./getAnalyticsTopPages"));

export { GetAnalyticsTrafficArgs, GetAnalyticsTrafficResult, GetAnalyticsTrafficOutputArgs } from "./getAnalyticsTraffic";
export const getAnalyticsTraffic: typeof import("./getAnalyticsTraffic").getAnalyticsTraffic = null as any;
export const getAnalyticsTrafficOutput: typeof import("./getAnalyticsTraffic").getAnalyticsTrafficOutput = null as any;
utilities.lazyLoad(exports, ["getAnalyticsTraffic","getAnalyticsTrafficOutput"], () => require("./getAnalyticsTraffic"));

export { GetAuthorizedUserArgs, GetAuthorizedUserResult } from "./getAuthorizedUser";
export const getAuthorizedUser: typeof import("./getAuthorizedUser").getAuthorizedUser = null as any;
export const getAuthorizedUserOutput: typeof import("./getAuthorizedUser").getAuthorizedUserOutput = null as any;
utilities.lazyLoad(exports, ["getAuthorizedUser","getAuthorizedUserOutput"], () => require("./getAuthorizedUser"));

export { GetPageArgs, GetPageResult, GetPageOutputArgs } from "./getPage";
export const getPage: typeof import("./getPage").getPage = null as any;
export const getPageOutput: typeof import("./getPage").getPageOutput = null as any;
utilities.lazyLoad(exports, ["getPage","getPageOutput"], () => require("./getPage"));

export { GetPageSchemaMarkupArgs, GetPageSchemaMarkupResult, GetPageSchemaMarkupOutputArgs } from "./getPageSchemaMarkup";
export const getPageSchemaMarkup: typeof import("./getPageSchemaMarkup").getPageSchemaMarkup = null as any;
export const getPageSchemaMarkupOutput: typeof import("./getPageSchemaMarkup").getPageSchemaMarkupOutput = null as any;
utilities.lazyLoad(exports, ["getPageSchemaMarkup","getPageSchemaMarkupOutput"], () => require("./getPageSchemaMarkup"));

export { GetPagesArgs, GetPagesResult, GetPagesOutputArgs } from "./getPages";
export const getPages: typeof import("./getPages").getPages = null as any;
export const getPagesOutput: typeof import("./getPages").getPagesOutput = null as any;
utilities.lazyLoad(exports, ["getPages","getPagesOutput"], () => require("./getPages"));

export { GetTokenInfoArgs, GetTokenInfoResult } from "./getTokenInfo";
export const getTokenInfo: typeof import("./getTokenInfo").getTokenInfo = null as any;
export const getTokenInfoOutput: typeof import("./getTokenInfo").getTokenInfoOutput = null as any;
utilities.lazyLoad(exports, ["getTokenInfo","getTokenInfoOutput"], () => require("./getTokenInfo"));

export { GoogleTagArgs } from "./googleTag";
export type GoogleTag = import("./googleTag").GoogleTag;
export const GoogleTag: typeof import("./googleTag").GoogleTag = null as any;
utilities.lazyLoad(exports, ["GoogleTag"], () => require("./googleTag"));

export { InlineScriptArgs } from "./inlineScript";
export type InlineScript = import("./inlineScript").InlineScript;
export const InlineScript: typeof import("./inlineScript").InlineScript = null as any;
utilities.lazyLoad(exports, ["InlineScript"], () => require("./inlineScript"));

export { PageContentArgs } from "./pageContent";
export type PageContent = import("./pageContent").PageContent;
export const PageContent: typeof import("./pageContent").PageContent = null as any;
utilities.lazyLoad(exports, ["PageContent"], () => require("./pageContent"));

export { PageCustomCodeArgs } from "./pageCustomCode";
export type PageCustomCode = import("./pageCustomCode").PageCustomCode;
export const PageCustomCode: typeof import("./pageCustomCode").PageCustomCode = null as any;
utilities.lazyLoad(exports, ["PageCustomCode"], () => require("./pageCustomCode"));

export { PageMetadataArgs } from "./pageMetadata";
export type PageMetadata = import("./pageMetadata").PageMetadata;
export const PageMetadata: typeof import("./pageMetadata").PageMetadata = null as any;
utilities.lazyLoad(exports, ["PageMetadata"], () => require("./pageMetadata"));

export { PageSchemaMarkupArgs } from "./pageSchemaMarkup";
export type PageSchemaMarkup = import("./pageSchemaMarkup").PageSchemaMarkup;
export const PageSchemaMarkup: typeof import("./pageSchemaMarkup").PageSchemaMarkup = null as any;
utilities.lazyLoad(exports, ["PageSchemaMarkup"], () => require("./pageSchemaMarkup"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { RedirectArgs } from "./redirect";
export type Redirect = import("./redirect").Redirect;
export const Redirect: typeof import("./redirect").Redirect = null as any;
utilities.lazyLoad(exports, ["Redirect"], () => require("./redirect"));

export { RegisteredScriptArgs } from "./registeredScript";
export type RegisteredScript = import("./registeredScript").RegisteredScript;
export const RegisteredScript: typeof import("./registeredScript").RegisteredScript = null as any;
utilities.lazyLoad(exports, ["RegisteredScript"], () => require("./registeredScript"));

export { RobotsTxtArgs } from "./robotsTxt";
export type RobotsTxt = import("./robotsTxt").RobotsTxt;
export const RobotsTxt: typeof import("./robotsTxt").RobotsTxt = null as any;
utilities.lazyLoad(exports, ["RobotsTxt"], () => require("./robotsTxt"));

export { SiteArgs } from "./site";
export type Site = import("./site").Site;
export const Site: typeof import("./site").Site = null as any;
utilities.lazyLoad(exports, ["Site"], () => require("./site"));

export { SiteCustomCodeArgs } from "./siteCustomCode";
export type SiteCustomCode = import("./siteCustomCode").SiteCustomCode;
export const SiteCustomCode: typeof import("./siteCustomCode").SiteCustomCode = null as any;
utilities.lazyLoad(exports, ["SiteCustomCode"], () => require("./siteCustomCode"));

export { WebhookArgs } from "./webhook";
export type Webhook = import("./webhook").Webhook;
export const Webhook: typeof import("./webhook").Webhook = null as any;
utilities.lazyLoad(exports, ["Webhook"], () => require("./webhook"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "webflow:index:Asset":
                return new Asset(name, <any>undefined, { urn })
            case "webflow:index:AssetFolder":
                return new AssetFolder(name, <any>undefined, { urn })
            case "webflow:index:Collection":
                return new Collection(name, <any>undefined, { urn })
            case "webflow:index:CollectionField":
                return new CollectionField(name, <any>undefined, { urn })
            case "webflow:index:CollectionItem":
                return new CollectionItem(name, <any>undefined, { urn })
            case "webflow:index:EcommerceSettings":
                return new EcommerceSettings(name, <any>undefined, { urn })
            case "webflow:index:GoogleTag":
                return new GoogleTag(name, <any>undefined, { urn })
            case "webflow:index:InlineScript":
                return new InlineScript(name, <any>undefined, { urn })
            case "webflow:index:PageContent":
                return new PageContent(name, <any>undefined, { urn })
            case "webflow:index:PageCustomCode":
                return new PageCustomCode(name, <any>undefined, { urn })
            case "webflow:index:PageMetadata":
                return new PageMetadata(name, <any>undefined, { urn })
            case "webflow:index:PageSchemaMarkup":
                return new PageSchemaMarkup(name, <any>undefined, { urn })
            case "webflow:index:Redirect":
                return new Redirect(name, <any>undefined, { urn })
            case "webflow:index:RegisteredScript":
                return new RegisteredScript(name, <any>undefined, { urn })
            case "webflow:index:RobotsTxt":
                return new RobotsTxt(name, <any>undefined, { urn })
            case "webflow:index:Site":
                return new Site(name, <any>undefined, { urn })
            case "webflow:index:SiteCustomCode":
                return new SiteCustomCode(name, <any>undefined, { urn })
            case "webflow:index:Webhook":
                return new Webhook(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("webflow", "index", _module)
pulumi.runtime.registerResourcePackage("webflow", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:webflow") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
