// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages custom code (JavaScript) scripts applied to a Webflow page (PUT /v2/pages/{page_id}/custom_code). This resource allows you to apply registered custom code scripts to specific pages. Scripts must first be registered using the RegisteredScript or InlineScript resource before they can be applied. All scripts in the configuration will be applied to the page; scripts not listed will be removed. Destroying the resource removes all applied code (DELETE /v2/pages/{page_id}/custom_code) but leaves the scripts registered.
 *
 * **Authentication:** this resource calls Webflow custom code endpoints, which require an OAuth Data Client app token with the `custom_code:read` and `custom_code:write` scopes. Webflow documents that these scopes are available only to Data Client apps: site API tokens cannot access custom code endpoints. Removing applied code (Delete, or dropping scripts from the list) additionally requires the `sites:write` (site custom code) or `pages:write` (page custom code) scope.
 */
export class PageCustomCode extends pulumi.CustomResource {
    /**
     * Get an existing PageCustomCode resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PageCustomCode {
        return new PageCustomCode(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'webflow:index:PageCustomCode';

    /**
     * Returns true if the given object is an instance of PageCustomCode.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PageCustomCode {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PageCustomCode.__pulumiType;
    }

    /**
     * The timestamp when the page custom code was first created (RFC3339 format). This is automatically set when the configuration is first created and is read-only.
     */
    declare public /*out*/ readonly createdOn: pulumi.Output<string | undefined>;
    /**
     * The timestamp when the page custom code was last updated (RFC3339 format). This is automatically set when the configuration is updated and is read-only.
     */
    declare public /*out*/ readonly lastUpdated: pulumi.Output<string | undefined>;
    /**
     * The Webflow page ID (24-character hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). You can find page IDs using the Webflow Pages API or in the Webflow designer. This field will be validated before making any API calls.
     */
    declare public readonly pageId: pulumi.Output<string>;
    /**
     * List of custom code scripts to apply to the page. Each script must reference a script ID and version that have been previously registered. All scripts in this list will be applied to the page; any scripts not listed will be removed from the page.
     */
    declare public readonly scripts: pulumi.Output<outputs.PageCustomCodeScript[]>;

    /**
     * Create a PageCustomCode resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PageCustomCodeArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.pageId === undefined && !opts.urn) {
                throw new Error("Missing required property 'pageId'");
            }
            if (args?.scripts === undefined && !opts.urn) {
                throw new Error("Missing required property 'scripts'");
            }
            resourceInputs["pageId"] = args?.pageId;
            resourceInputs["scripts"] = args?.scripts;
            resourceInputs["createdOn"] = undefined /*out*/;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        } else {
            resourceInputs["createdOn"] = undefined /*out*/;
            resourceInputs["lastUpdated"] = undefined /*out*/;
            resourceInputs["pageId"] = undefined /*out*/;
            resourceInputs["scripts"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PageCustomCode.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PageCustomCode resource.
 */
export interface PageCustomCodeArgs {
    /**
     * The Webflow page ID (24-character hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c4'). You can find page IDs using the Webflow Pages API or in the Webflow designer. This field will be validated before making any API calls.
     */
    pageId: pulumi.Input<string>;
    /**
     * List of custom code scripts to apply to the page. Each script must reference a script ID and version that have been previously registered. All scripts in this list will be applied to the page; any scripts not listed will be removed from the page.
     */
    scripts: pulumi.Input<pulumi.Input<inputs.PageCustomCodeScriptArgs>[]>;
}
