// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages HTTP redirects for a Webflow site. This resource allows you to define redirect rules for old URLs to new locations, supporting both permanent (301) and temporary (302) redirects.
 */
export class Redirect extends pulumi.CustomResource {
    /**
     * Get an existing Redirect resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Redirect {
        return new Redirect(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'webflow:index:Redirect';

    /**
     * Returns true if the given object is an instance of Redirect.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Redirect {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Redirect.__pulumiType;
    }

    /**
     * The timestamp when the redirect was created (RFC3339 format), when reported by the Webflow API. Read-only; empty when the API does not return it.
     */
    declare public /*out*/ readonly createdOn: pulumi.Output<string | undefined>;
    /**
     * The URL path to redirect to (e.g., '/new-page', '/home'). Must start with '/' and contain only valid URL characters. This is the location where users will be redirected when they visit the source path. Changing this value updates the redirect in place.
     */
    declare public readonly destinationPath: pulumi.Output<string>;
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     */
    declare public readonly siteId: pulumi.Output<string>;
    /**
     * The URL path to redirect from (e.g., '/old-page', '/blog/2023'). Must start with '/' and contain only valid URL characters (letters, numbers, hyphens, underscores, slashes, dots). Query strings and fragments are not allowed in the source path. Changing this value replaces the redirect.
     */
    declare public readonly sourcePath: pulumi.Output<string>;
    /**
     * The HTTP status code for the redirect. Must be either 301 or 302. 301 = permanent redirect (use when a page has moved permanently; search engines update their index). 302 = temporary redirect (use for maintenance or temporary page moves). Note: the Webflow redirects API does not currently report a status code, so this value is kept in Pulumi state and is not verified against Webflow.
     */
    declare public readonly statusCode: pulumi.Output<number>;

    /**
     * Create a Redirect resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RedirectArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.destinationPath === undefined && !opts.urn) {
                throw new Error("Missing required property 'destinationPath'");
            }
            if (args?.siteId === undefined && !opts.urn) {
                throw new Error("Missing required property 'siteId'");
            }
            if (args?.sourcePath === undefined && !opts.urn) {
                throw new Error("Missing required property 'sourcePath'");
            }
            if (args?.statusCode === undefined && !opts.urn) {
                throw new Error("Missing required property 'statusCode'");
            }
            resourceInputs["destinationPath"] = args?.destinationPath;
            resourceInputs["siteId"] = args?.siteId;
            resourceInputs["sourcePath"] = args?.sourcePath;
            resourceInputs["statusCode"] = args?.statusCode;
            resourceInputs["createdOn"] = undefined /*out*/;
        } else {
            resourceInputs["createdOn"] = undefined /*out*/;
            resourceInputs["destinationPath"] = undefined /*out*/;
            resourceInputs["siteId"] = undefined /*out*/;
            resourceInputs["sourcePath"] = undefined /*out*/;
            resourceInputs["statusCode"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Redirect.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Redirect resource.
 */
export interface RedirectArgs {
    /**
     * The URL path to redirect to (e.g., '/new-page', '/home'). Must start with '/' and contain only valid URL characters. This is the location where users will be redirected when they visit the source path. Changing this value updates the redirect in place.
     */
    destinationPath: pulumi.Input<string>;
    /**
     * The Webflow site ID (24-character lowercase hexadecimal string, e.g., '5f0c8c9e1c9d440000e8d8c3'). You can find your site ID in the Webflow dashboard under Site Settings. This field will be validated before making any API calls.
     */
    siteId: pulumi.Input<string>;
    /**
     * The URL path to redirect from (e.g., '/old-page', '/blog/2023'). Must start with '/' and contain only valid URL characters (letters, numbers, hyphens, underscores, slashes, dots). Query strings and fragments are not allowed in the source path. Changing this value replaces the redirect.
     */
    sourcePath: pulumi.Input<string>;
    /**
     * The HTTP status code for the redirect. Must be either 301 or 302. 301 = permanent redirect (use when a page has moved permanently; search engines update their index). 302 = temporary redirect (use for maintenance or temporary page moves). Note: the Webflow redirects API does not currently report a status code, so this value is kept in Pulumi state and is not verified against Webflow.
     */
    statusCode: pulumi.Input<number>;
}
